; Mika

; Constants -------------------------

; Overrides -------------------------

[TextureOverrideMikaPosition]
hash = 1876e82e
vb0 = ResourceMikaPosition

[TextureOverrideMikaBlend]
hash = b8a027a1
vb1 = ResourceMikaBlend
handling = skip
draw = 15202,0

[TextureOverrideMikaTexcoord]
hash = 285f6696
vb1 = ResourceMikaTexcoord

[TextureOverrideMikaVertexLimitRaise]
hash = 9d5bb5ff

[TextureOverrideMikaIB]
hash = 41760901
handling = skip
drawindexed = auto

[TextureOverrideMikaHead]
hash = 41760901
match_first_index = 0
ib = ResourceMikaHeadIB
ps-t0 = ResourceMikaHeadNormalMap
ps-t1 = ResourceMikaHeadDiffuse
ps-t2 = ResourceMikaHeadLightMap
run = CommandList\global\ORFix\ORFix

[TextureOverrideMikaBody]
hash = 41760901
match_first_index = 21072
ib = ResourceMikaBodyIB
ps-t0 = ResourceMikaBodyNormalMap
ps-t1 = ResourceMikaBodyDiffuse
ps-t2 = ResourceMikaBodyLightMap
run = CommandList\global\ORFix\ORFix

[TextureOverrideMikaDress]
hash = 41760901
match_first_index = 52122
ib = ResourceMikaDressIB
ps-t0 = ResourceMikaDressDiffuse
ps-t1 = ResourceMikaDressLightMap
run = CommandList\global\ORFix\NNFix

[TextureOverrideMikaFaceHeadDiffuse]
hash = 0026026f
ps-t0 = ResourceMikaFaceHeadDiffuse


; CommandList -----------------------

; Resources -------------------------

[ResourceMikaPosition]
type = Buffer
stride = 40
filename = MikaPosition.buf

[ResourceMikaBlend]
type = Buffer
stride = 32
filename = MikaBlend.buf

[ResourceMikaTexcoord]
type = Buffer
stride = 20
filename = MikaTexcoord.buf

[ResourceMikaHeadIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = MikaHead.ib

[ResourceMikaBodyIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = MikaBody.ib

[ResourceMikaDressIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = MikaDress.ib

[ResourceMikaHeadNormalMap]
filename = MikaHeadNormalMap.dds

[ResourceMikaHeadDiffuse]
filename = MikaHeadDiffuse.dds

[ResourceMikaHeadLightMap]
filename = MikaHeadLightMap.dds

[ResourceMikaBodyNormalMap]
filename = MikaBodyNormalMap.dds

[ResourceMikaBodyDiffuse]
filename = MikaBodyDiffuse.dds

[ResourceMikaBodyLightMap]
filename = MikaBodyLightMap.dds

[ResourceMikaDressDiffuse]
filename = MikaDressDiffuse.dds

[ResourceMikaDressLightMap]
filename = MikaDressLightMap.dds

[ResourceMikaFaceHeadDiffuse]
filename = MikaFaceHeadDiffuse.dds


; the identity mod of Mika: the game's own model out of its download folder (tmpmot5xggw), built by AGIDMGen
