; Lumine

; Constants -------------------------

; Overrides -------------------------

[TextureOverrideLuminePosition]
hash = 8239be13
vb0 = ResourceLuminePosition

[TextureOverrideLumineBlend]
hash = 8772fa81
vb1 = ResourceLumineBlend
handling = skip
draw = 12022,0

[TextureOverrideLumineTexcoord]
hash = 8d2c7c7c
vb1 = ResourceLumineTexcoord

[TextureOverrideLumineVertexLimitRaise]
hash = 846ff19c

[TextureOverrideLumineIB]
hash = e7612ed8
handling = skip
drawindexed = auto

[TextureOverrideLumineHead]
hash = e7612ed8
match_first_index = 0
ib = ResourceLumineHeadIB
ps-t0 = ResourceLumineHeadDiffuse
ps-t1 = ResourceLumineHeadLightMap
run = CommandList\global\ORFix\NNFix

[TextureOverrideLumineBody]
hash = e7612ed8
match_first_index = 6915
ib = ResourceLumineBodyIB
ps-t0 = ResourceLumineBodyDiffuse
ps-t1 = ResourceLumineBodyLightMap
run = CommandList\global\ORFix\NNFix

[TextureOverrideLumineDress]
hash = e7612ed8
match_first_index = 40413
ib = ResourceLumineDressIB
ps-t0 = ResourceLumineDressDiffuse
ps-t1 = ResourceLumineDressLightMap
run = CommandList\global\ORFix\NNFix

[TextureOverrideLumineFaceHeadDiffuse]
hash = cdabcf6f
ps-t0 = ResourceLumineFaceHeadDiffuse


; CommandList -----------------------

; Resources -------------------------

[ResourceLuminePosition]
type = Buffer
stride = 40
filename = LuminePosition.buf

[ResourceLumineBlend]
type = Buffer
stride = 32
filename = LumineBlend.buf

[ResourceLumineTexcoord]
type = Buffer
stride = 20
filename = LumineTexcoord.buf

[ResourceLumineHeadIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = LumineHead.ib

[ResourceLumineBodyIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = LumineBody.ib

[ResourceLumineDressIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = LumineDress.ib

[ResourceLumineHeadDiffuse]
filename = LumineHeadDiffuse.dds

[ResourceLumineHeadLightMap]
filename = LumineHeadLightMap.dds

[ResourceLumineBodyDiffuse]
filename = LumineBodyDiffuse.dds

[ResourceLumineBodyLightMap]
filename = LumineBodyLightMap.dds

[ResourceLumineDressDiffuse]
filename = LumineDressDiffuse.dds

[ResourceLumineDressLightMap]
filename = LumineDressLightMap.dds

[ResourceLumineFaceHeadDiffuse]
filename = LumineFaceHeadDiffuse.dds


; the identity mod of Lumine: the game's own model out of its download folder (GI/Lumine/4_0), built by AGIDMGen
