; Zhongli

; Constants -------------------------

; Overrides -------------------------

[TextureOverrideZhongliPosition]
hash = a75ba32e
vb0 = ResourceZhongliPosition

[TextureOverrideZhongliBlend]
hash = f0a40042
vb1 = ResourceZhongliBlend
handling = skip
draw = 11136,0

[TextureOverrideZhongliTexcoord]
hash = eb3aaca2
vb1 = ResourceZhongliTexcoord

[TextureOverrideZhongliVertexLimitRaise]
hash = 6fa3d7f4

[TextureOverrideZhongliIB]
hash = 4c8480f5
handling = skip
drawindexed = auto

[TextureOverrideZhongliHead]
hash = 4c8480f5
match_first_index = 0
ib = ResourceZhongliHeadIB
ps-t0 = ResourceZhongliHeadDiffuse
ps-t1 = ResourceZhongliHeadLightMap
run = CommandList\global\ORFix\NNFix

[TextureOverrideZhongliBody]
hash = 4c8480f5
match_first_index = 8976
ib = ResourceZhongliBodyIB
ps-t0 = ResourceZhongliBodyDiffuse
ps-t1 = ResourceZhongliBodyLightMap
run = CommandList\global\ORFix\NNFix

[TextureOverrideZhongliDress]
hash = 4c8480f5
match_first_index = 37530
ib = ResourceZhongliDressIB
ps-t0 = ResourceZhongliDressDiffuse
ps-t1 = ResourceZhongliDressLightMap
run = CommandList\global\ORFix\NNFix

[TextureOverrideZhongliFaceHeadDiffuse]
hash = 1db9961f
ps-t0 = ResourceZhongliFaceHeadDiffuse


; CommandList -----------------------

; Resources -------------------------

[ResourceZhongliPosition]
type = Buffer
stride = 40
filename = ZhongliPosition.buf

[ResourceZhongliBlend]
type = Buffer
stride = 32
filename = ZhongliBlend.buf

[ResourceZhongliTexcoord]
type = Buffer
stride = 20
filename = ZhongliTexcoord.buf

[ResourceZhongliHeadIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = ZhongliHead.ib

[ResourceZhongliBodyIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = ZhongliBody.ib

[ResourceZhongliDressIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = ZhongliDress.ib

[ResourceZhongliHeadDiffuse]
filename = ZhongliHeadDiffuse.dds

[ResourceZhongliHeadLightMap]
filename = ZhongliHeadLightMap.dds

[ResourceZhongliBodyDiffuse]
filename = ZhongliBodyDiffuse.dds

[ResourceZhongliBodyLightMap]
filename = ZhongliBodyLightMap.dds

[ResourceZhongliDressDiffuse]
filename = ZhongliDressDiffuse.dds

[ResourceZhongliDressLightMap]
filename = ZhongliDressLightMap.dds

[ResourceZhongliFaceHeadDiffuse]
filename = ZhongliFaceHeadDiffuse.dds


; the identity mod of Zhongli: the game's own model out of its download folder (GI/Zhongli/6_8), built by AGIDMGen
