; Ifa

; Constants -------------------------

; Overrides -------------------------

[TextureOverrideIfaBodyPosition]
hash = 845f14ca
vb0 = ResourceIfaBodyPosition

[TextureOverrideIfaBodyBlend]
hash = 2f2a744d
vb1 = ResourceIfaBodyBlend
handling = skip
draw = 22536,0

[TextureOverrideIfaBodyTexcoord]
hash = 77bf113b
vb1 = ResourceIfaBodyTexcoord

[TextureOverrideIfaBodyVertexLimitRaise]
hash = 7a45dc9e

[TextureOverrideIfaBodyIB]
hash = d561fadc
handling = skip
drawindexed = auto

[TextureOverrideIfaBodyA]
hash = d561fadc
match_first_index = 0
ib = ResourceIfaBodyAIB
ps-t0 = ResourceIfaBodyANormalMap
ps-t1 = ResourceIfaBodyADiffuse
ps-t2 = ResourceIfaBodyALightMap
run = CommandList\global\ORFix\ORFix

[TextureOverrideIfaBodyB]
hash = d561fadc
match_first_index = 48570
ib = ResourceIfaBodyBIB
ps-t0 = ResourceIfaBodyBNormalMap
ps-t1 = ResourceIfaBodyBDiffuse
ps-t2 = ResourceIfaBodyBLightMap
run = CommandList\global\ORFix\ORFix

[TextureOverrideIfaBodyC]
hash = d561fadc
match_first_index = 73152
ib = ResourceIfaBodyCIB
ps-t0 = ResourceIfaBodyCNormalMap
ps-t1 = ResourceIfaBodyCDiffuse
ps-t2 = ResourceIfaBodyCLightMap
run = CommandList\global\ORFix\ORFix

[TextureOverrideIfaFaceHeadDiffuse]
hash = 0f178795
ps-t0 = ResourceIfaFaceHeadDiffuse


; CommandList -----------------------

; Resources -------------------------

[ResourceIfaBodyPosition]
type = Buffer
stride = 40
filename = IfaBodyPosition.buf

[ResourceIfaBodyBlend]
type = Buffer
stride = 32
filename = IfaBodyBlend.buf

[ResourceIfaBodyTexcoord]
type = Buffer
stride = 20
filename = IfaBodyTexcoord.buf

[ResourceIfaBodyAIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = IfaBodyA.ib

[ResourceIfaBodyBIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = IfaBodyB.ib

[ResourceIfaBodyCIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = IfaBodyC.ib

[ResourceIfaBodyANormalMap]
filename = IfaBodyANormalMap.dds

[ResourceIfaBodyADiffuse]
filename = IfaBodyADiffuse.dds

[ResourceIfaBodyALightMap]
filename = IfaBodyALightMap.dds

[ResourceIfaBodyBNormalMap]
filename = IfaBodyBNormalMap.dds

[ResourceIfaBodyBDiffuse]
filename = IfaBodyBDiffuse.dds

[ResourceIfaBodyBLightMap]
filename = IfaBodyBLightMap.dds

[ResourceIfaBodyCNormalMap]
filename = IfaBodyCNormalMap.dds

[ResourceIfaBodyCDiffuse]
filename = IfaBodyCDiffuse.dds

[ResourceIfaBodyCLightMap]
filename = IfaBodyCLightMap.dds

[ResourceIfaFaceHeadDiffuse]
filename = IfaFaceADiffuse.dds


; the identity mod of Ifa: the game's own model out of its download folder (tmpoffbke00), built by AGIDMGen
