; KamisatoAyato

; Constants -------------------------

; Overrides -------------------------

[TextureOverrideKamisatoAyatoPosition]
hash = b473c856
vb0 = ResourceKamisatoAyatoPosition

[TextureOverrideKamisatoAyatoBlend]
hash = 19b13b6e
vb1 = ResourceKamisatoAyatoBlend
handling = skip
draw = 18595,0

[TextureOverrideKamisatoAyatoTexcoord]
hash = 2482a5ee
vb1 = ResourceKamisatoAyatoTexcoord

[TextureOverrideKamisatoAyatoVertexLimitRaise]
hash = 36fca030

[TextureOverrideKamisatoAyatoIB]
hash = e59b09d6
handling = skip
drawindexed = auto

[TextureOverrideKamisatoAyatoHead]
hash = e59b09d6
match_first_index = 0
ib = ResourceKamisatoAyatoHeadIB
ps-t0 = ResourceKamisatoAyatoHeadDiffuse
ps-t1 = ResourceKamisatoAyatoHeadLightMap
run = CommandList\global\ORFix\NNFix

[TextureOverrideKamisatoAyatoBody]
hash = e59b09d6
match_first_index = 29769
ib = ResourceKamisatoAyatoBodyIB
ps-t0 = ResourceKamisatoAyatoBodyDiffuse
ps-t1 = ResourceKamisatoAyatoBodyLightMap
run = CommandList\global\ORFix\NNFix

[TextureOverrideKamisatoAyatoDress]
hash = e59b09d6
match_first_index = 66183
ib = ResourceKamisatoAyatoDressIB
ps-t0 = ResourceKamisatoAyatoDressDiffuse
ps-t1 = ResourceKamisatoAyatoDressLightMap
run = CommandList\global\ORFix\NNFix

[TextureOverrideKamisatoAyatoFaceHeadDiffuse]
hash = 6e40e741
ps-t0 = ResourceKamisatoAyatoFaceHeadDiffuse


; CommandList -----------------------

; Resources -------------------------

[ResourceKamisatoAyatoPosition]
type = Buffer
stride = 40
filename = KamisatoAyatoPosition.buf

[ResourceKamisatoAyatoBlend]
type = Buffer
stride = 32
filename = KamisatoAyatoBlend.buf

[ResourceKamisatoAyatoTexcoord]
type = Buffer
stride = 20
filename = KamisatoAyatoTexcoord.buf

[ResourceKamisatoAyatoHeadIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = KamisatoAyatoHead.ib

[ResourceKamisatoAyatoBodyIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = KamisatoAyatoBody.ib

[ResourceKamisatoAyatoDressIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = KamisatoAyatoDress.ib

[ResourceKamisatoAyatoHeadDiffuse]
filename = KamisatoAyatoHeadDiffuse.dds

[ResourceKamisatoAyatoHeadLightMap]
filename = KamisatoAyatoHeadLightMap.dds

[ResourceKamisatoAyatoBodyDiffuse]
filename = KamisatoAyatoBodyDiffuse.dds

[ResourceKamisatoAyatoBodyLightMap]
filename = KamisatoAyatoBodyLightMap.dds

[ResourceKamisatoAyatoDressDiffuse]
filename = KamisatoAyatoDressDiffuse.dds

[ResourceKamisatoAyatoDressLightMap]
filename = KamisatoAyatoDressLightMap.dds

[ResourceKamisatoAyatoFaceHeadDiffuse]
filename = KamisatoAyatoFaceHeadDiffuse.dds


; the identity mod of KamisatoAyato: the game's own model out of its download folder (GI/KamisatoAyato/6_8), built by AGIDMGen
