; MonaCN

; Constants -------------------------

; Overrides -------------------------

[TextureOverrideMonaCNPosition]
hash = 515f3ce6
vb0 = ResourceMonaCNPosition

[TextureOverrideMonaCNBlend]
hash = bad2731b
vb1 = ResourceMonaCNBlend
handling = skip
draw = 13333,0

[TextureOverrideMonaCNTexcoord]
hash = e543af5d
vb1 = ResourceMonaCNTexcoord

[TextureOverrideMonaCNVertexLimitRaise]
hash = c814ad67

[TextureOverrideMonaCNIB]
hash = d5ad8084
handling = skip
drawindexed = auto

[TextureOverrideMonaCNHead]
hash = d5ad8084
match_first_index = 0
ib = ResourceMonaCNHeadIB
ps-t0 = ResourceMonaCNHeadDiffuse
ps-t1 = ResourceMonaCNHeadLightMap
run = CommandList\global\ORFix\NNFix

[TextureOverrideMonaCNBody]
hash = d5ad8084
match_first_index = 17688
ib = ResourceMonaCNBodyIB
ps-t0 = ResourceMonaCNBodyDiffuse
ps-t1 = ResourceMonaCNBodyLightMap
run = CommandList\global\ORFix\NNFix

[TextureOverrideMonaCNFaceHeadDiffuse]
hash = 8e116301
ps-t0 = ResourceMonaCNFaceHeadDiffuse


; CommandList -----------------------

; Resources -------------------------

[ResourceMonaCNPosition]
type = Buffer
stride = 40
filename = MonaCNPosition.buf

[ResourceMonaCNBlend]
type = Buffer
stride = 32
filename = MonaCNBlend.buf

[ResourceMonaCNTexcoord]
type = Buffer
stride = 12
filename = MonaCNTexcoord.buf

[ResourceMonaCNHeadIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = MonaCNHead.ib

[ResourceMonaCNBodyIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = MonaCNBody.ib

[ResourceMonaCNHeadDiffuse]
filename = MonaCNHeadDiffuse.dds

[ResourceMonaCNHeadLightMap]
filename = MonaCNHeadLightMap.dds

[ResourceMonaCNBodyDiffuse]
filename = MonaCNBodyDiffuse.dds

[ResourceMonaCNBodyLightMap]
filename = MonaCNBodyLightMap.dds

[ResourceMonaCNFaceHeadDiffuse]
filename = MonaCNFaceHeadDiffuse.dds


; the identity mod of MonaCN: the game's own model out of its download folder (tmpyhi1o21_), built by AGIDMGen
