; YelanTranquil

; Constants -------------------------

; Overrides -------------------------

[TextureOverrideYelanTranquilBangPosition]
hash = c0dc5c2f
vb0 = ResourceYelanTranquilBangPosition

[TextureOverrideYelanTranquilBangBlend]
hash = 5d532cca
vb1 = ResourceYelanTranquilBangBlend
handling = skip
draw = 2256,0

[TextureOverrideYelanTranquilBangTexcoord]
hash = d5db917d
vb1 = ResourceYelanTranquilBangTexcoord

[TextureOverrideYelanTranquilBangVertexLimitRaise]
hash = 11b90d23

[TextureOverrideYelanTranquilBangIB]
hash = 648d61dd
handling = skip
drawindexed = auto

[TextureOverrideYelanTranquilBangA]
hash = 648d61dd
match_first_index = 0
ib = ResourceYelanTranquilBangAIB
ps-t0 = ResourceYelanTranquilBodyANormalMap
ps-t1 = ResourceYelanTranquilBodyADiffuse
ps-t2 = ResourceYelanTranquilBodyALightMap
run = CommandList\global\ORFix\ORFix

[TextureOverrideYelanTranquilBodyPosition]
hash = 02c325ef
vb0 = ResourceYelanTranquilBodyPosition

[TextureOverrideYelanTranquilBodyBlend]
hash = 244a4b2f
vb1 = ResourceYelanTranquilBodyBlend
handling = skip
draw = 25954,0

[TextureOverrideYelanTranquilBodyTexcoord]
hash = c772811d
vb1 = ResourceYelanTranquilBodyTexcoord

[TextureOverrideYelanTranquilBodyVertexLimitRaise]
hash = 3a7b10bb

[TextureOverrideYelanTranquilBodyIB]
hash = 611d6168
handling = skip
drawindexed = auto

[TextureOverrideYelanTranquilBodyA]
hash = 611d6168
match_first_index = 0
ib = ResourceYelanTranquilBodyAIB
ps-t0 = ResourceYelanTranquilBodyANormalMap
ps-t1 = ResourceYelanTranquilBodyADiffuse
ps-t2 = ResourceYelanTranquilBodyALightMap
run = CommandList\global\ORFix\ORFix

[TextureOverrideYelanTranquilBodyB]
hash = 611d6168
match_first_index = 53631
ib = ResourceYelanTranquilBodyBIB
ps-t0 = ResourceYelanTranquilBodyBNormalMap
ps-t1 = ResourceYelanTranquilBodyBDiffuse
ps-t2 = ResourceYelanTranquilBodyBLightMap
run = CommandList\global\ORFix\ORFix

[TextureOverrideYelanTranquilBodyC]
hash = 611d6168
match_first_index = 67374
ib = ResourceYelanTranquilBodyCIB
ps-t0 = ResourceYelanTranquilBodyCDiffuse
ps-t1 = ResourceYelanTranquilBodyCLightMap
run = CommandList\global\ORFix\NNFix

[TextureOverrideYelanTranquilEyePosition]
hash = 6bc61bb3
vb0 = ResourceYelanTranquilEyePosition

[TextureOverrideYelanTranquilEyeBlend]
hash = 10056b37
vb1 = ResourceYelanTranquilEyeBlend
handling = skip
draw = 120,0

[TextureOverrideYelanTranquilEyeTexcoord]
hash = e23e5a53
vb1 = ResourceYelanTranquilEyeTexcoord

[TextureOverrideYelanTranquilEyeVertexLimitRaise]
hash = 61b441bd

[TextureOverrideYelanTranquilEyeIB]
hash = 54bc082e
handling = skip
drawindexed = auto

[TextureOverrideYelanTranquilEyeA]
hash = 54bc082e
match_first_index = 0
ib = ResourceYelanTranquilEyeAIB
ps-t0 = ResourceYelanTranquilBodyADiffuse
ps-t1 = ResourceYelanTranquilBodyALightMap
run = CommandList\global\ORFix\NNFix

[TextureOverrideYelanTranquilFaceHeadDiffuse]
hash = e8ad6095
ps-t0 = ResourceYelanTranquilFaceHeadDiffuse


; CommandList -----------------------

; Resources -------------------------

[ResourceYelanTranquilBangPosition]
type = Buffer
stride = 40
filename = YelanTranquilBangPosition.buf

[ResourceYelanTranquilBangBlend]
type = Buffer
stride = 32
filename = YelanTranquilBangBlend.buf

[ResourceYelanTranquilBangTexcoord]
type = Buffer
stride = 20
filename = YelanTranquilBangTexcoord.buf

[ResourceYelanTranquilBodyPosition]
type = Buffer
stride = 40
filename = YelanTranquilBodyPosition.buf

[ResourceYelanTranquilBodyBlend]
type = Buffer
stride = 32
filename = YelanTranquilBodyBlend.buf

[ResourceYelanTranquilBodyTexcoord]
type = Buffer
stride = 20
filename = YelanTranquilBodyTexcoord.buf

[ResourceYelanTranquilEyePosition]
type = Buffer
stride = 40
filename = YelanTranquilEyePosition.buf

[ResourceYelanTranquilEyeBlend]
type = Buffer
stride = 32
filename = YelanTranquilEyeBlend.buf

[ResourceYelanTranquilEyeTexcoord]
type = Buffer
stride = 12
filename = YelanTranquilEyeTexcoord.buf

[ResourceYelanTranquilBangAIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = YelanTranquilBangA.ib

[ResourceYelanTranquilBodyAIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = YelanTranquilBodyA.ib

[ResourceYelanTranquilBodyBIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = YelanTranquilBodyB.ib

[ResourceYelanTranquilBodyCIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = YelanTranquilBodyC.ib

[ResourceYelanTranquilEyeAIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = YelanTranquilEyeA.ib

[ResourceYelanTranquilBodyADiffuse]
filename = YelanTranquilBodyADiffuse.dds

[ResourceYelanTranquilBodyALightMap]
filename = YelanTranquilBodyALightMap.dds

[ResourceYelanTranquilBodyANormalMap]
filename = YelanTranquilBodyANormalMap.dds

[ResourceYelanTranquilBodyBDiffuse]
filename = YelanTranquilBodyBDiffuse.dds

[ResourceYelanTranquilBodyBLightMap]
filename = YelanTranquilBodyBLightMap.dds

[ResourceYelanTranquilBodyBNormalMap]
filename = YelanTranquilBodyBNormalMap.dds

[ResourceYelanTranquilBodyCDiffuse]
filename = YelanTranquilBodyCDiffuse.dds

[ResourceYelanTranquilBodyCLightMap]
filename = YelanTranquilBodyCLightMap.dds

[ResourceYelanTranquilFaceHeadDiffuse]
filename = YelanTranquilFaceHeadDiffuse.dds


; the identity mod of YelanTranquil: the game's own model out of its download folder (tmpkznho1fo), built by AGIDMGen
