; Jahoda

; Constants -------------------------

; Overrides -------------------------

[TextureOverrideJahodaBangsPosition]
hash = d5b59e2a
vb0 = ResourceJahodaBangsPosition

[TextureOverrideJahodaBangsBlend]
hash = fa0543c2
vb1 = ResourceJahodaBangsBlend
handling = skip
draw = 2320,0

[TextureOverrideJahodaBangsTexcoord]
hash = 541ffdb3
vb1 = ResourceJahodaBangsTexcoord

[TextureOverrideJahodaBangsVertexLimitRaise]
hash = 5ab5f780

[TextureOverrideJahodaBangsIB]
hash = 722ea690
handling = skip
drawindexed = auto

[TextureOverrideJahodaBangsA]
hash = 722ea690
match_first_index = 0
ib = ResourceJahodaBangsAIB
ps-t0 = ResourceJahodaBangsANormalMap
ps-t1 = ResourceJahodaBangsADiffuse
ps-t2 = ResourceJahodaBangsALightMap
run = CommandList\global\ORFix\ORFix

[TextureOverrideJahodaEyesPosition]
hash = 7db15cbb
vb0 = ResourceJahodaEyesPosition

[TextureOverrideJahodaEyesBlend]
hash = b1cf8713
vb1 = ResourceJahodaEyesBlend
handling = skip
draw = 120,0

[TextureOverrideJahodaEyesTexcoord]
hash = 79776c3d
vb1 = ResourceJahodaEyesTexcoord

[TextureOverrideJahodaEyesVertexLimitRaise]
hash = 61b441bd

[TextureOverrideJahodaEyesIB]
hash = 3aebadc3
handling = skip
drawindexed = auto

[TextureOverrideJahodaEyesA]
hash = 3aebadc3
match_first_index = 0
ib = ResourceJahodaEyesAIB
ps-t0 = ResourceJahodaEyesADiffuse
ps-t1 = ResourceJahodaEyesALightMap
run = CommandList\global\ORFix\NNFix

[TextureOverrideJahodaBodyPosition]
hash = 71ba92fa
vb0 = ResourceJahodaBodyPosition

[TextureOverrideJahodaBodyBlend]
hash = aa3263e5
vb1 = ResourceJahodaBodyBlend
handling = skip
draw = 25373,0

[TextureOverrideJahodaBodyTexcoord]
hash = fcf8a9b7
vb1 = ResourceJahodaBodyTexcoord

[TextureOverrideJahodaBodyVertexLimitRaise]
hash = c1cfd2f8

[TextureOverrideJahodaBodyIB]
hash = 901f0350
handling = skip
drawindexed = auto

[TextureOverrideJahodaBodyA]
hash = 901f0350
match_first_index = 0
ib = ResourceJahodaBodyAIB
ps-t0 = ResourceJahodaBodyANormalMap
ps-t1 = ResourceJahodaBodyADiffuse
ps-t2 = ResourceJahodaBodyALightMap
run = CommandList\global\ORFix\ORFix

[TextureOverrideJahodaBodyB]
hash = 901f0350
match_first_index = 35808
ib = ResourceJahodaBodyBIB
ps-t0 = ResourceJahodaBodyBNormalMap
ps-t1 = ResourceJahodaBodyBDiffuse
ps-t2 = ResourceJahodaBodyBLightMap
run = CommandList\global\ORFix\ORFix

[TextureOverrideJahodaBodyC]
hash = 901f0350
match_first_index = 86649
ib = ResourceJahodaBodyCIB
ps-t0 = ResourceJahodaBodyCDiffuse
run = CommandList\global\ORFix\NNFix

[TextureOverrideJahodaBodyD]
hash = 901f0350
match_first_index = 87237
ib = ResourceJahodaBodyDIB
ps-t0 = ResourceJahodaBodyDDiffuse
ps-t1 = ResourceJahodaBodyDLightMap
run = CommandList\global\ORFix\NNFix

[TextureOverrideJahodaFaceHeadDiffuse]
hash = 15229b27
ps-t0 = ResourceJahodaFaceHeadDiffuse


; CommandList -----------------------

; Resources -------------------------

[ResourceJahodaBangsPosition]
type = Buffer
stride = 40
filename = JahodaBangsPosition.buf

[ResourceJahodaBangsBlend]
type = Buffer
stride = 32
filename = JahodaBangsBlend.buf

[ResourceJahodaBangsTexcoord]
type = Buffer
stride = 12
filename = JahodaBangsTexcoord.buf

[ResourceJahodaEyesPosition]
type = Buffer
stride = 40
filename = JahodaEyesPosition.buf

[ResourceJahodaEyesBlend]
type = Buffer
stride = 32
filename = JahodaEyesBlend.buf

[ResourceJahodaEyesTexcoord]
type = Buffer
stride = 12
filename = JahodaEyesTexcoord.buf

[ResourceJahodaBodyPosition]
type = Buffer
stride = 40
filename = JahodaBodyPosition.buf

[ResourceJahodaBodyBlend]
type = Buffer
stride = 32
filename = JahodaBodyBlend.buf

[ResourceJahodaBodyTexcoord]
type = Buffer
stride = 28
filename = JahodaBodyTexcoord.buf

[ResourceJahodaBangsAIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = JahodaBangsA.ib

[ResourceJahodaEyesAIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = JahodaEyesA.ib

[ResourceJahodaBodyAIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = JahodaBodyA.ib

[ResourceJahodaBodyBIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = JahodaBodyB.ib

[ResourceJahodaBodyCIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = JahodaBodyC.ib

[ResourceJahodaBodyDIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = JahodaBodyD.ib

[ResourceJahodaBangsALightMap]
filename = JahodaBangsALightMap.dds

[ResourceJahodaBangsANormalMap]
filename = JahodaBangsANormalMap.dds

[ResourceJahodaBangsADiffuse]
filename = JahodaBangsADiffuse.dds

[ResourceJahodaEyesALightMap]
filename = JahodaEyesALightMap.dds

[ResourceJahodaEyesADiffuse]
filename = JahodaEyesADiffuse.dds

[ResourceJahodaBodyALightMap]
filename = JahodaBodyALightMap.dds

[ResourceJahodaBodyANormalMap]
filename = JahodaBodyANormalMap.dds

[ResourceJahodaBodyADiffuse]
filename = JahodaBodyADiffuse.dds

[ResourceJahodaBodyBLightMap]
filename = JahodaBodyBLightMap.dds

[ResourceJahodaBodyBNormalMap]
filename = JahodaBodyBNormalMap.dds

[ResourceJahodaBodyBDiffuse]
filename = JahodaBodyBDiffuse.dds

[ResourceJahodaBodyCDiffuse]
filename = JahodaBodyCDiffuse.dds

[ResourceJahodaBodyDLightMap]
filename = JahodaBodyDLightMap.dds

[ResourceJahodaBodyDDiffuse]
filename = JahodaBodyDDiffuse.dds

[ResourceJahodaFaceHeadDiffuse]
filename = JahodaFaceADiffuse.dds


; the identity mod of Jahoda: the game's own model out of its download folder (tmpr_e135u7), built by AGIDMGen
