; KiraraBoots

; Constants -------------------------

; Overrides -------------------------

[TextureOverrideKiraraBootsPosition]
hash = f8013ba9
vb0 = ResourceKiraraBootsPosition

[TextureOverrideKiraraBootsBlend]
hash = 53a2502b
vb1 = ResourceKiraraBootsBlend
handling = skip
draw = 20854,0

[TextureOverrideKiraraBootsTexcoord]
hash = 596e8fe0
vb1 = ResourceKiraraBootsTexcoord

[TextureOverrideKiraraBootsVertexLimitRaise]
hash = 4955fc99

[TextureOverrideKiraraBootsIB]
hash = 846979e2
handling = skip
drawindexed = auto

[TextureOverrideKiraraBootsHead]
hash = 846979e2
match_first_index = 0
ib = ResourceKiraraBootsHeadIB
ps-t0 = ResourceKiraraBootsHeadNormalMap
ps-t1 = ResourceKiraraBootsHeadDiffuse
ps-t2 = ResourceKiraraBootsHeadLightMap
run = CommandList\global\ORFix\ORFix

[TextureOverrideKiraraBootsBody]
hash = 846979e2
match_first_index = 36804
ib = ResourceKiraraBootsBodyIB
ps-t0 = ResourceKiraraBootsBodyNormalMap
ps-t1 = ResourceKiraraBootsBodyDiffuse
ps-t2 = ResourceKiraraBootsBodyLightMap
run = CommandList\global\ORFix\ORFix

[TextureOverrideKiraraBootsDress]
hash = 846979e2
match_first_index = 80295
ib = ResourceKiraraBootsDressIB
ps-t0 = ResourceKiraraBootsDressDiffuse
ps-t1 = ResourceKiraraBootsDressLightMap
run = CommandList\global\ORFix\NNFix

[TextureOverrideKiraraBootsFaceHeadDiffuse]
hash = 6eb20522
ps-t0 = ResourceKiraraBootsFaceHeadDiffuse


; CommandList -----------------------

; Resources -------------------------

[ResourceKiraraBootsPosition]
type = Buffer
stride = 40
filename = KiraraBootsPosition.buf

[ResourceKiraraBootsBlend]
type = Buffer
stride = 32
filename = KiraraBootsBlend.buf

[ResourceKiraraBootsTexcoord]
type = Buffer
stride = 20
filename = KiraraBootsTexcoord.buf

[ResourceKiraraBootsHeadIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = KiraraBootsHead.ib

[ResourceKiraraBootsBodyIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = KiraraBootsBody.ib

[ResourceKiraraBootsDressIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = KiraraBootsDress.ib

[ResourceKiraraBootsHeadDiffuse]
filename = KiraraBootsHeadDiffuse.dds

[ResourceKiraraBootsHeadLightMap]
filename = KiraraBootsHeadLightMap.dds

[ResourceKiraraBootsHeadNormalMap]
filename = KiraraBootsHeadNormalMap.dds

[ResourceKiraraBootsBodyDiffuse]
filename = KiraraBootsBodyDiffuse.dds

[ResourceKiraraBootsBodyLightMap]
filename = KiraraBootsBodyLightMap.dds

[ResourceKiraraBootsBodyNormalMap]
filename = KiraraBootsBodyNormalMap.dds

[ResourceKiraraBootsDressDiffuse]
filename = KiraraBootsDressDiffuse.dds

[ResourceKiraraBootsDressLightMap]
filename = KiraraBootsDressLightMap.dds

[ResourceKiraraBootsFaceHeadDiffuse]
filename = KiraraBootsFaceHeadDiffuse.dds


; the identity mod of KiraraBoots: the game's own model out of its download folder (GI/KiraraBoots/4_8), built by AGIDMGen
