; XianglingCheer

; Constants -------------------------

; Overrides -------------------------

[TextureOverrideXianglingCheerPosition]
hash = 05a65c3f
vb0 = ResourceXianglingCheerPosition

[TextureOverrideXianglingCheerBlend]
hash = bd659168
vb1 = ResourceXianglingCheerBlend
handling = skip
draw = 22151,0

[TextureOverrideXianglingCheerTexcoord]
hash = c679abfe
vb1 = ResourceXianglingCheerTexcoord

[TextureOverrideXianglingCheerVertexLimitRaise]
hash = e71f5012

[TextureOverrideXianglingCheerIB]
hash = cc7a4851
handling = skip
drawindexed = auto

[TextureOverrideXianglingCheerHead]
hash = cc7a4851
match_first_index = 0
ib = ResourceXianglingCheerHeadIB
ps-t0 = ResourceXianglingCheerHeadNormalMap
ps-t1 = ResourceXianglingCheerHeadDiffuse
ps-t2 = ResourceXianglingCheerHeadLightMap
run = CommandList\global\ORFix\ORFix

[TextureOverrideXianglingCheerBody]
hash = cc7a4851
match_first_index = 46374
ib = ResourceXianglingCheerBodyIB
ps-t0 = ResourceXianglingCheerBodyNormalMap
ps-t1 = ResourceXianglingCheerBodyDiffuse
ps-t2 = ResourceXianglingCheerBodyLightMap
run = CommandList\global\ORFix\ORFix


; CommandList -----------------------

; Resources -------------------------

[ResourceXianglingCheerPosition]
type = Buffer
stride = 40
filename = XianglingCheerPosition.buf

[ResourceXianglingCheerBlend]
type = Buffer
stride = 32
filename = XianglingCheerBlend.buf

[ResourceXianglingCheerTexcoord]
type = Buffer
stride = 12
filename = XianglingCheerTexcoord.buf

[ResourceXianglingCheerHeadIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = XianglingCheerHead.ib

[ResourceXianglingCheerBodyIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = XianglingCheerBody.ib

[ResourceXianglingCheerHeadDiffuse]
filename = XianglingCheerHeadDiffuse.dds

[ResourceXianglingCheerHeadLightMap]
filename = XianglingCheerHeadLightMap.dds

[ResourceXianglingCheerHeadNormalMap]
filename = XianglingCheerHeadNormalMap.dds

[ResourceXianglingCheerBodyDiffuse]
filename = XianglingCheerBodyDiffuse.dds

[ResourceXianglingCheerBodyLightMap]
filename = XianglingCheerBodyLightMap.dds

[ResourceXianglingCheerBodyNormalMap]
filename = XianglingCheerBodyNormalMap.dds


; the identity mod of XianglingCheer: the game's own model out of its download folder (tmp6s5lj64k), built by AGIDMGen
