; GanyuTwilight

; Constants -------------------------

; Overrides -------------------------

[TextureOverrideGanyuTwilightPosition]
hash = 9b3f356e
vb0 = ResourceGanyuTwilightPosition

[TextureOverrideGanyuTwilightBlend]
hash = 9a5c01d2
vb1 = ResourceGanyuTwilightBlend
handling = skip
draw = 24118,0

[TextureOverrideGanyuTwilightTexcoord]
hash = 5ff2f1d1
vb1 = ResourceGanyuTwilightTexcoord

[TextureOverrideGanyuTwilightVertexLimitRaise]
hash = 1ad9c181

[TextureOverrideGanyuTwilightIB]
hash = cb283c86
handling = skip
drawindexed = auto

[TextureOverrideGanyuTwilightHead]
hash = cb283c86
match_first_index = 0
ib = ResourceGanyuTwilightHeadIB
ps-t0 = ResourceGanyuTwilightHeadNormalMap
ps-t1 = ResourceGanyuTwilightHeadDiffuse
ps-t2 = ResourceGanyuTwilightHeadLightMap
run = CommandList\global\ORFix\ORFix

[TextureOverrideGanyuTwilightBody]
hash = cb283c86
match_first_index = 50817
ib = ResourceGanyuTwilightBodyIB
ps-t0 = ResourceGanyuTwilightBodyNormalMap
ps-t1 = ResourceGanyuTwilightBodyDiffuse
ps-t2 = ResourceGanyuTwilightBodyLightMap
run = CommandList\global\ORFix\ORFix

[TextureOverrideGanyuTwilightDress]
hash = cb283c86
match_first_index = 74235
ib = ResourceGanyuTwilightDressIB
ps-t0 = ResourceGanyuTwilightDressNormalMap
ps-t1 = ResourceGanyuTwilightDressDiffuse
ps-t2 = ResourceGanyuTwilightDressLightMap
run = CommandList\global\ORFix\ORFix


; CommandList -----------------------

; Resources -------------------------

[ResourceGanyuTwilightPosition]
type = Buffer
stride = 40
filename = GanyuTwilightPosition.buf

[ResourceGanyuTwilightBlend]
type = Buffer
stride = 32
filename = GanyuTwilightBlend.buf

[ResourceGanyuTwilightTexcoord]
type = Buffer
stride = 20
filename = GanyuTwilightTexcoord.buf

[ResourceGanyuTwilightHeadIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = GanyuTwilightHead.ib

[ResourceGanyuTwilightBodyIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = GanyuTwilightBody.ib

[ResourceGanyuTwilightDressIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = GanyuTwilightDress.ib

[ResourceGanyuTwilightHeadNormalMap]
filename = GanyuTwilightHeadNormalMap.dds

[ResourceGanyuTwilightHeadDiffuse]
filename = GanyuTwilightHeadDiffuse.dds

[ResourceGanyuTwilightHeadLightMap]
filename = GanyuTwilightHeadLightMap.dds

[ResourceGanyuTwilightHeadMetalMap]
filename = GanyuTwilightHeadMetalMap.dds

[ResourceGanyuTwilightBodyNormalMap]
filename = GanyuTwilightBodyNormalMap.dds

[ResourceGanyuTwilightBodyDiffuse]
filename = GanyuTwilightBodyDiffuse.dds

[ResourceGanyuTwilightBodyLightMap]
filename = GanyuTwilightBodyLightMap.dds

[ResourceGanyuTwilightDressNormalMap]
filename = GanyuTwilightDressNormalMap.dds

[ResourceGanyuTwilightDressDiffuse]
filename = GanyuTwilightDressDiffuse.dds

[ResourceGanyuTwilightDressLightMap]
filename = GanyuTwilightDressLightMap.dds


; the identity mod of GanyuTwilight: the game's own model out of its download folder (GI/GanyuTwilight/6_8), built by AGIDMGen
