; Flins

; Constants -------------------------

; Overrides -------------------------

[TextureOverrideFlinsBangsPosition]
hash = 4c608bb6
vb0 = ResourceFlinsBangsPosition

[TextureOverrideFlinsBangsBlend]
hash = f2c61779
vb1 = ResourceFlinsBangsBlend
handling = skip
draw = 1252,0

[TextureOverrideFlinsBangsTexcoord]
hash = c9f003bd
vb1 = ResourceFlinsBangsTexcoord

[TextureOverrideFlinsBangsVertexLimitRaise]
hash = 7a1cfc2c

[TextureOverrideFlinsBangsIB]
hash = 36713af5
handling = skip
drawindexed = auto

[TextureOverrideFlinsBangsA]
hash = 36713af5
match_first_index = 0
ib = ResourceFlinsBangsAIB
ps-t0 = ResourceFlinsBangsANormalMap
ps-t1 = ResourceFlinsBangsADiffuse
ps-t2 = ResourceFlinsBangsALightMap
run = CommandList\global\ORFix\ORFix

[TextureOverrideFlinsEyesPosition]
hash = a718160c
vb0 = ResourceFlinsEyesPosition

[TextureOverrideFlinsEyesBlend]
hash = b8cff159
vb1 = ResourceFlinsEyesBlend
handling = skip
draw = 156,0

[TextureOverrideFlinsEyesTexcoord]
hash = fdc60590
vb1 = ResourceFlinsEyesTexcoord

[TextureOverrideFlinsEyesVertexLimitRaise]
hash = 1eeb3d05

[TextureOverrideFlinsEyesIB]
hash = e7085600
handling = skip
drawindexed = auto

[TextureOverrideFlinsEyesA]
hash = e7085600
match_first_index = 0
ib = ResourceFlinsEyesAIB
ps-t0 = ResourceFlinsEyesADiffuse
ps-t1 = ResourceFlinsEyesALightMap
run = CommandList\global\ORFix\NNFix

[TextureOverrideFlinsBodyPosition]
hash = da9f1463
vb0 = ResourceFlinsBodyPosition

[TextureOverrideFlinsBodyBlend]
hash = fe2e3d94
vb1 = ResourceFlinsBodyBlend
handling = skip
draw = 27233,0

[TextureOverrideFlinsBodyTexcoord]
hash = f550227a
vb1 = ResourceFlinsBodyTexcoord

[TextureOverrideFlinsBodyVertexLimitRaise]
hash = 72626f38

[TextureOverrideFlinsBodyIB]
hash = cdb045fc
handling = skip
drawindexed = auto

[TextureOverrideFlinsBodyA]
hash = cdb045fc
match_first_index = 0
ib = ResourceFlinsBodyAIB
ps-t0 = ResourceFlinsBodyANormalMap
ps-t1 = ResourceFlinsBodyADiffuse
ps-t2 = ResourceFlinsBodyALightMap
run = CommandList\global\ORFix\ORFix

[TextureOverrideFlinsBodyB]
hash = cdb045fc
match_first_index = 28425
ib = ResourceFlinsBodyBIB
ps-t0 = ResourceFlinsBodyBNormalMap
ps-t1 = ResourceFlinsBodyBDiffuse
ps-t2 = ResourceFlinsBodyBLightMap
run = CommandList\global\ORFix\ORFix

[TextureOverrideFlinsBodyC]
hash = cdb045fc
match_first_index = 76071
ib = ResourceFlinsBodyCIB
ps-t0 = ResourceFlinsBodyCNormalMap
ps-t1 = ResourceFlinsBodyCDiffuse
ps-t2 = ResourceFlinsBodyCLightMap
run = CommandList\global\ORFix\ORFix

[TextureOverrideFlinsLanternPosition]
hash = 86287c40
vb0 = ResourceFlinsLanternPosition

[TextureOverrideFlinsLanternBlend]
hash = ba317690
vb1 = ResourceFlinsLanternBlend
handling = skip
draw = 2412,0

[TextureOverrideFlinsLanternTexcoord]
hash = 4aa0462c
vb1 = ResourceFlinsLanternTexcoord

[TextureOverrideFlinsLanternVertexLimitRaise]
hash = e666d6ae

[TextureOverrideFlinsLanternIB]
hash = cf410a0d
handling = skip
drawindexed = auto

[TextureOverrideFlinsLanternA]
hash = cf410a0d
match_first_index = 0
ib = ResourceFlinsLanternAIB
ps-t0 = ResourceFlinsLanternADiffuse
ps-t1 = ResourceFlinsLanternALightMap
run = CommandList\global\ORFix\NNFix

[TextureOverrideFlinsLanternB]
hash = cf410a0d
match_first_index = 5298
ib = ResourceFlinsLanternBIB

[TextureOverrideFlinsFaceHeadDiffuse]
hash = 132ea2a8
ps-t0 = ResourceFlinsFaceHeadDiffuse


; CommandList -----------------------

; Resources -------------------------

[ResourceFlinsBangsPosition]
type = Buffer
stride = 40
filename = FlinsBangsPosition.buf

[ResourceFlinsBangsBlend]
type = Buffer
stride = 32
filename = FlinsBangsBlend.buf

[ResourceFlinsBangsTexcoord]
type = Buffer
stride = 12
filename = FlinsBangsTexcoord.buf

[ResourceFlinsEyesPosition]
type = Buffer
stride = 40
filename = FlinsEyesPosition.buf

[ResourceFlinsEyesBlend]
type = Buffer
stride = 32
filename = FlinsEyesBlend.buf

[ResourceFlinsEyesTexcoord]
type = Buffer
stride = 12
filename = FlinsEyesTexcoord.buf

[ResourceFlinsBodyPosition]
type = Buffer
stride = 40
filename = FlinsBodyPosition.buf

[ResourceFlinsBodyBlend]
type = Buffer
stride = 32
filename = FlinsBodyBlend.buf

[ResourceFlinsBodyTexcoord]
type = Buffer
stride = 28
filename = FlinsBodyTexcoord.buf

[ResourceFlinsLanternPosition]
type = Buffer
stride = 40
filename = FlinsLanternPosition.buf

[ResourceFlinsLanternBlend]
type = Buffer
stride = 32
filename = FlinsLanternBlend.buf

[ResourceFlinsLanternTexcoord]
type = Buffer
stride = 20
filename = FlinsLanternTexcoord.buf

[ResourceFlinsBangsAIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = FlinsBangsA.ib

[ResourceFlinsEyesAIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = FlinsEyesA.ib

[ResourceFlinsBodyAIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = FlinsBodyA.ib

[ResourceFlinsBodyBIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = FlinsBodyB.ib

[ResourceFlinsBodyCIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = FlinsBodyC.ib

[ResourceFlinsLanternAIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = FlinsLanternA.ib

[ResourceFlinsLanternBIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = FlinsLanternB.ib

[ResourceFlinsBangsALightMap]
filename = FlinsBangsALightMap.dds

[ResourceFlinsBangsANormalMap]
filename = FlinsBangsANormalMap.dds

[ResourceFlinsBangsADiffuse]
filename = FlinsBangsADiffuse.dds

[ResourceFlinsEyesALightMap]
filename = FlinsEyesALightMap.dds

[ResourceFlinsEyesADiffuse]
filename = FlinsEyesADiffuse.dds

[ResourceFlinsBodyALightMap]
filename = FlinsBodyALightMap.dds

[ResourceFlinsBodyANormalMap]
filename = FlinsBodyANormalMap.dds

[ResourceFlinsBodyADiffuse]
filename = FlinsBodyADiffuse.dds

[ResourceFlinsBodyBLightMap]
filename = FlinsBodyBLightMap.dds

[ResourceFlinsBodyBNormalMap]
filename = FlinsBodyBNormalMap.dds

[ResourceFlinsBodyBDiffuse]
filename = FlinsBodyBDiffuse.dds

[ResourceFlinsBodyCNormalMap]
filename = FlinsBodyCNormalMap.dds

[ResourceFlinsBodyCDiffuse]
filename = FlinsBodyCDiffuse.dds

[ResourceFlinsBodyCLightMap]
filename = FlinsBodyCLightMap.dds

[ResourceFlinsLanternADiffuse]
filename = FlinsLanternADiffuse.dds

[ResourceFlinsLanternALightMap]
filename = FlinsLanternALightMap.dds

[ResourceFlinsFaceHeadDiffuse]
filename = FlinsFaceADiffuse.dds


; the identity mod of Flins: the game's own model out of its download folder (tmp6q5vd94c), built by AGIDMGen
