; Mizuki

; Constants -------------------------

; Overrides -------------------------

[TextureOverrideMizukiPosition]
hash = bbdaf598
vb0 = ResourceMizukiPosition

[TextureOverrideMizukiBlend]
hash = bca4f2b2
vb1 = ResourceMizukiBlend
handling = skip
draw = 22226,0

[TextureOverrideMizukiTexcoord]
hash = ce21e3a1
vb1 = ResourceMizukiTexcoord

[TextureOverrideMizukiVertexLimitRaise]
hash = e36be83b

[TextureOverrideMizukiIB]
hash = ec1ed3c9
handling = skip
drawindexed = auto

[TextureOverrideMizukiHead]
hash = ec1ed3c9
match_first_index = 0
ib = ResourceMizukiHeadIB
ps-t0 = ResourceMizukiHeadNormalMap
ps-t1 = ResourceMizukiHeadDiffuse
ps-t2 = ResourceMizukiHeadLightMap
run = CommandList\global\ORFix\ORFix

[TextureOverrideMizukiBody]
hash = ec1ed3c9
match_first_index = 44274
ib = ResourceMizukiBodyIB
ps-t0 = ResourceMizukiBodyNormalMap
ps-t1 = ResourceMizukiBodyDiffuse
ps-t2 = ResourceMizukiBodyLightMap
run = CommandList\global\ORFix\ORFix

[TextureOverrideMizukiDress]
hash = ec1ed3c9
match_first_index = 85404
ib = ResourceMizukiDressIB
ps-t0 = ResourceMizukiDressNormalMap
ps-t1 = ResourceMizukiDressDiffuse
ps-t2 = ResourceMizukiDressLightMap
run = CommandList\global\ORFix\ORFix

[TextureOverrideMizukiFaceHeadDiffuse]
hash = a10efc40
ps-t0 = ResourceMizukiFaceHeadDiffuse


; CommandList -----------------------

; Resources -------------------------

[ResourceMizukiPosition]
type = Buffer
stride = 40
filename = MizukiPosition.buf

[ResourceMizukiBlend]
type = Buffer
stride = 32
filename = MizukiBlend.buf

[ResourceMizukiTexcoord]
type = Buffer
stride = 20
filename = MizukiTexcoord.buf

[ResourceMizukiHeadIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = MizukiHead.ib

[ResourceMizukiBodyIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = MizukiBody.ib

[ResourceMizukiDressIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = MizukiDress.ib

[ResourceMizukiHeadNormalMap]
filename = MizukiHeadNormalMap.dds

[ResourceMizukiHeadDiffuse]
filename = MizukiHeadDiffuse.dds

[ResourceMizukiHeadLightMap]
filename = MizukiHeadLightMap.dds

[ResourceMizukiBodyNormalMap]
filename = MizukiBodyNormalMap.dds

[ResourceMizukiBodyDiffuse]
filename = MizukiBodyDiffuse.dds

[ResourceMizukiBodyLightMap]
filename = MizukiBodyLightMap.dds

[ResourceMizukiDressNormalMap]
filename = MizukiDressNormalMap.dds

[ResourceMizukiDressDiffuse]
filename = MizukiDressDiffuse.dds

[ResourceMizukiDressLightMap]
filename = MizukiDressLightMap.dds

[ResourceMizukiFaceHeadDiffuse]
filename = MizukiFaceHeadDiffuse.dds


; the identity mod of Mizuki: the game's own model out of its download folder (tmpavk84fah), built by AGIDMGen
