; Alhaitham

; Constants -------------------------

; Overrides -------------------------

[TextureOverrideAlhaithamPosition]
hash = 3ef08385
vb0 = ResourceAlhaithamPosition

[TextureOverrideAlhaithamBlend]
hash = 1d1783dd
vb1 = ResourceAlhaithamBlend
handling = skip
draw = 19989,0

[TextureOverrideAlhaithamTexcoord]
hash = be0197c5
vb1 = ResourceAlhaithamTexcoord

[TextureOverrideAlhaithamVertexLimitRaise]
hash = f9152211

[TextureOverrideAlhaithamIB]
hash = 639d1fb8
handling = skip
drawindexed = auto

[TextureOverrideAlhaithamHead]
hash = 639d1fb8
match_first_index = 0
ib = ResourceAlhaithamHeadIB
ps-t0 = ResourceAlhaithamHeadNormalMap
ps-t1 = ResourceAlhaithamHeadDiffuse
ps-t2 = ResourceAlhaithamHeadLightMap
run = CommandList\global\ORFix\ORFix

[TextureOverrideAlhaithamBody]
hash = 639d1fb8
match_first_index = 28278
ib = ResourceAlhaithamBodyIB
ps-t0 = ResourceAlhaithamBodyNormalMap
ps-t1 = ResourceAlhaithamBodyDiffuse
ps-t2 = ResourceAlhaithamBodyLightMap
run = CommandList\global\ORFix\ORFix

[TextureOverrideAlhaithamDress]
hash = 639d1fb8
match_first_index = 71181
ib = ResourceAlhaithamDressIB
ps-t0 = ResourceAlhaithamDressNormalMap
ps-t1 = ResourceAlhaithamDressDiffuse
ps-t2 = ResourceAlhaithamDressLightMap
run = CommandList\global\ORFix\ORFix

[TextureOverrideAlhaithamFaceHeadDiffuse]
hash = 315022f1
ps-t0 = ResourceAlhaithamFaceHeadDiffuse


; CommandList -----------------------

; Resources -------------------------

[ResourceAlhaithamPosition]
type = Buffer
stride = 40
filename = AlhaithamPosition.buf

[ResourceAlhaithamBlend]
type = Buffer
stride = 32
filename = AlhaithamBlend.buf

[ResourceAlhaithamTexcoord]
type = Buffer
stride = 20
filename = AlhaithamTexcoord.buf

[ResourceAlhaithamHeadIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = AlhaithamHead.ib

[ResourceAlhaithamBodyIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = AlhaithamBody.ib

[ResourceAlhaithamDressIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = AlhaithamDress.ib

[ResourceAlhaithamHeadNormalMap]
filename = AlhaithamHeadNormalMap.dds

[ResourceAlhaithamHeadDiffuse]
filename = AlhaithamHeadDiffuse.dds

[ResourceAlhaithamHeadLightMap]
filename = AlhaithamHeadLightMap.dds

[ResourceAlhaithamBodyNormalMap]
filename = AlhaithamBodyNormalMap.dds

[ResourceAlhaithamBodyDiffuse]
filename = AlhaithamBodyDiffuse.dds

[ResourceAlhaithamBodyLightMap]
filename = AlhaithamBodyLightMap.dds

[ResourceAlhaithamDressNormalMap]
filename = AlhaithamDressNormalMap.dds

[ResourceAlhaithamDressDiffuse]
filename = AlhaithamDressDiffuse.dds

[ResourceAlhaithamDressLightMap]
filename = AlhaithamDressLightMap.dds

[ResourceAlhaithamFaceHeadDiffuse]
filename = AlhaithamFaceHeadDiffuse.dds


; the identity mod of Alhaitham: the game's own model out of its download folder (GI/Alhaitham/6_8), built by AGIDMGen
