; Noelle

; Constants -------------------------

; Overrides -------------------------

[TextureOverrideNoellePosition]
hash = d1384d15
vb0 = ResourceNoellePosition

[TextureOverrideNoelleBlend]
hash = 1517291d
vb1 = ResourceNoelleBlend
handling = skip
draw = 15965,0

[TextureOverrideNoelleTexcoord]
hash = 8f1eff2c
vb1 = ResourceNoelleTexcoord

[TextureOverrideNoelleVertexLimitRaise]
hash = def7af36

[TextureOverrideNoelleIB]
hash = 9cf0789e
handling = skip
drawindexed = auto

[TextureOverrideNoelleHead]
hash = 9cf0789e
match_first_index = 0
ib = ResourceNoelleHeadIB
ps-t0 = ResourceNoelleHeadDiffuse
ps-t1 = ResourceNoelleHeadLightMap
run = CommandList\global\ORFix\NNFix

[TextureOverrideNoelleBody]
hash = 9cf0789e
match_first_index = 12915
ib = ResourceNoelleBodyIB
ps-t0 = ResourceNoelleBodyDiffuse
ps-t1 = ResourceNoelleBodyLightMap
run = CommandList\global\ORFix\NNFix

[TextureOverrideNoelleDress]
hash = 9cf0789e
match_first_index = 47910
ib = ResourceNoelleDressIB
ps-t0 = ResourceNoelleDressDiffuse
ps-t1 = ResourceNoelleDressLightMap
run = CommandList\global\ORFix\NNFix

[TextureOverrideNoelleFaceHeadDiffuse]
hash = 355f2735
ps-t0 = ResourceNoelleFaceHeadDiffuse


; CommandList -----------------------

; Resources -------------------------

[ResourceNoellePosition]
type = Buffer
stride = 40
filename = NoellePosition.buf

[ResourceNoelleBlend]
type = Buffer
stride = 32
filename = NoelleBlend.buf

[ResourceNoelleTexcoord]
type = Buffer
stride = 20
filename = NoelleTexcoord.buf

[ResourceNoelleHeadIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = NoelleHead.ib

[ResourceNoelleBodyIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = NoelleBody.ib

[ResourceNoelleDressIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = NoelleDress.ib

[ResourceNoelleHeadDiffuse]
filename = NoelleHeadDiffuse.dds

[ResourceNoelleHeadLightMap]
filename = NoelleHeadLightMap.dds

[ResourceNoelleBodyDiffuse]
filename = NoelleBodyDiffuse.dds

[ResourceNoelleBodyLightMap]
filename = NoelleBodyLightMap.dds

[ResourceNoelleDressDiffuse]
filename = NoelleDressDiffuse.dds

[ResourceNoelleDressLightMap]
filename = NoelleDressLightMap.dds

[ResourceNoelleFaceHeadDiffuse]
filename = NoelleFaceHeadDiffuse.dds


; the identity mod of Noelle: the game's own model out of its download folder (GI/Noelle/6_8), built by AGIDMGen
