; RosariaCN

; Constants -------------------------

; Overrides -------------------------

[TextureOverrideRosariaCNPosition]
hash = 59a1f8b1
vb0 = ResourceRosariaCNPosition

[TextureOverrideRosariaCNBlend]
hash = a7bee046
vb1 = ResourceRosariaCNBlend
handling = skip
draw = 13992,0

[TextureOverrideRosariaCNTexcoord]
hash = 86e0d16b
vb1 = ResourceRosariaCNTexcoord

[TextureOverrideRosariaCNVertexLimitRaise]
hash = 7a318f3d

[TextureOverrideRosariaCNIB]
hash = bdca273e
handling = skip
drawindexed = auto

[TextureOverrideRosariaCNHead]
hash = bdca273e
match_first_index = 0
ib = ResourceRosariaCNHeadIB
ps-t0 = ResourceRosariaCNHeadDiffuse
ps-t1 = ResourceRosariaCNHeadLightMap
run = CommandList\global\ORFix\NNFix

[TextureOverrideRosariaCNBody]
hash = bdca273e
match_first_index = 11025
ib = ResourceRosariaCNBodyIB
ps-t0 = ResourceRosariaCNBodyDiffuse
ps-t1 = ResourceRosariaCNBodyLightMap
run = CommandList\global\ORFix\NNFix

[TextureOverrideRosariaCNDress]
hash = bdca273e
match_first_index = 46539
ib = ResourceRosariaCNDressIB
ps-t0 = ResourceRosariaCNDressDiffuse
ps-t1 = ResourceRosariaCNDressLightMap
run = CommandList\global\ORFix\NNFix

[TextureOverrideRosariaCNExtra]
hash = bdca273e
match_first_index = 48441
ib = ResourceRosariaCNExtraIB
ps-t0 = ResourceRosariaCNExtraDiffuse
ps-t1 = ResourceRosariaCNExtraLightMap
run = CommandList\global\ORFix\NNFix

[TextureOverrideRosariaCNFaceHeadDiffuse]
hash = 2abd61ee
ps-t0 = ResourceRosariaCNFaceHeadDiffuse


; CommandList -----------------------

; Resources -------------------------

[ResourceRosariaCNPosition]
type = Buffer
stride = 40
filename = RosariaCNPosition.buf

[ResourceRosariaCNBlend]
type = Buffer
stride = 32
filename = RosariaCNBlend.buf

[ResourceRosariaCNTexcoord]
type = Buffer
stride = 20
filename = RosariaCNTexcoord.buf

[ResourceRosariaCNHeadIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = RosariaCNHead.ib

[ResourceRosariaCNBodyIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = RosariaCNBody.ib

[ResourceRosariaCNDressIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = RosariaCNDress.ib

[ResourceRosariaCNExtraIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = RosariaCNExtra.ib

[ResourceRosariaCNHeadDiffuse]
filename = RosariaCNHeadDiffuse.dds

[ResourceRosariaCNHeadLightMap]
filename = RosariaCNHeadLightMap.dds

[ResourceRosariaCNBodyDiffuse]
filename = RosariaCNBodyDiffuse.dds

[ResourceRosariaCNBodyLightMap]
filename = RosariaCNBodyLightMap.dds

[ResourceRosariaCNDressDiffuse]
filename = RosariaCNDressDiffuse.dds

[ResourceRosariaCNDressLightMap]
filename = RosariaCNDressLightMap.dds

[ResourceRosariaCNExtraDiffuse]
filename = RosariaCNExtraDiffuse.dds

[ResourceRosariaCNExtraLightMap]
filename = RosariaCNExtraLightMap.dds

[ResourceRosariaCNFaceHeadDiffuse]
filename = RosariaCNFaceHeadDiffuse.dds


; the identity mod of RosariaCN: the game's own model out of its download folder (GI/RosariaCN/6_8), built by AGIDMGen
