; Venti

; Constants -------------------------

; Overrides -------------------------

[TextureOverrideVentiPosition]
hash = 09a91a5c
vb0 = ResourceVentiPosition

[TextureOverrideVentiBlend]
hash = a6823bb3
vb1 = ResourceVentiBlend
handling = skip
draw = 13695,0

[TextureOverrideVentiTexcoord]
hash = 6568ac68
vb1 = ResourceVentiTexcoord

[TextureOverrideVentiVertexLimitRaise]
hash = 0d36f587

[TextureOverrideVentiIB]
hash = 1afcf31d
handling = skip
drawindexed = auto

[TextureOverrideVentiHead]
hash = 1afcf31d
match_first_index = 0
ib = ResourceVentiHeadIB
ps-t0 = ResourceVentiHeadDiffuse
ps-t1 = ResourceVentiHeadLightMap
run = CommandList\global\ORFix\NNFix

[TextureOverrideVentiBody]
hash = 1afcf31d
match_first_index = 7419
ib = ResourceVentiBodyIB
ps-t0 = ResourceVentiBodyDiffuse
ps-t1 = ResourceVentiBodyLightMap
run = CommandList\global\ORFix\NNFix

[TextureOverrideVentiFaceHeadDiffuse]
hash = 841b5b0c
ps-t0 = ResourceVentiFaceHeadDiffuse


; CommandList -----------------------

; Resources -------------------------

[ResourceVentiPosition]
type = Buffer
stride = 40
filename = VentiPosition.buf

[ResourceVentiBlend]
type = Buffer
stride = 32
filename = VentiBlend.buf

[ResourceVentiTexcoord]
type = Buffer
stride = 12
filename = VentiTexcoord.buf

[ResourceVentiHeadIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = VentiHead.ib

[ResourceVentiBodyIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = VentiBody.ib

[ResourceVentiHeadDiffuse]
filename = VentiHeadDiffuse.dds

[ResourceVentiHeadLightMap]
filename = VentiHeadLightMap.dds

[ResourceVentiBodyDiffuse]
filename = VentiBodyDiffuse.dds

[ResourceVentiBodyLightMap]
filename = VentiBodyLightMap.dds

[ResourceVentiFaceHeadDiffuse]
filename = VentiFaceHeadDiffuse.dds


; the identity mod of Venti: the game's own model out of its download folder (tmp5filfss2), built by AGIDMGen
