; AmberCN

; Constants -------------------------

; Overrides -------------------------

[TextureOverrideAmberCNPosition]
hash = 557b2eff
vb0 = ResourceAmberCNPosition

[TextureOverrideAmberCNBlend]
hash = f35340d5
vb1 = ResourceAmberCNBlend
handling = skip
draw = 10514,0

[TextureOverrideAmberCNTexcoord]
hash = dbc594b6
vb1 = ResourceAmberCNTexcoord

[TextureOverrideAmberCNVertexLimitRaise]
hash = 53eff008

[TextureOverrideAmberCNIB]
hash = b41d4d94
handling = skip
drawindexed = auto

[TextureOverrideAmberCNHead]
hash = b41d4d94
match_first_index = 0
ib = ResourceAmberCNHeadIB
ps-t0 = ResourceAmberCNHeadDiffuse
ps-t1 = ResourceAmberCNHeadLightMap
run = CommandList\global\ORFix\NNFix

[TextureOverrideAmberCNBody]
hash = b41d4d94
match_first_index = 5670
ib = ResourceAmberCNBodyIB
ps-t0 = ResourceAmberCNBodyDiffuse
ps-t1 = ResourceAmberCNBodyLightMap
run = CommandList\global\ORFix\NNFix

[TextureOverrideAmberCNFaceHeadDiffuse]
hash = 1d064079
ps-t0 = ResourceAmberCNFaceHeadDiffuse


; CommandList -----------------------

; Resources -------------------------

[ResourceAmberCNPosition]
type = Buffer
stride = 40
filename = AmberCNPosition.buf

[ResourceAmberCNBlend]
type = Buffer
stride = 32
filename = AmberCNBlend.buf

[ResourceAmberCNTexcoord]
type = Buffer
stride = 12
filename = AmberCNTexcoord.buf

[ResourceAmberCNHeadIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = AmberCNHead.ib

[ResourceAmberCNBodyIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = AmberCNBody.ib

[ResourceAmberCNHeadDiffuse]
filename = AmberCNHeadDiffuse.dds

[ResourceAmberCNHeadLightMap]
filename = AmberCNHeadLightMap.dds

[ResourceAmberCNBodyDiffuse]
filename = AmberCNBodyDiffuse.dds

[ResourceAmberCNBodyLightMap]
filename = AmberCNBodyLightMap.dds

[ResourceAmberCNFaceHeadDiffuse]
filename = AmberCNFaceHeadDiffuse.dds


; the identity mod of AmberCN: the game's own model out of its download folder (GI/AmberCN/6_8), built by AGIDMGen
