from ..AGRemapUtils import VersionReplace, RanDateTimeReplace, RanHashReplace, BuiltDateTimeReplace, BuildHashReplace, ScriptPostamble


# the values only this builder fills in, beside AGRemapUtils' own placeholders
DependenciesReplace = "{{Dependencies}}"
MainFuncReplace = "{{Main Func}}"

ScriptBuilderName = "ScriptBuilder"
ScriptBuilderVersion = "1.0.0"
ScriptBuilderAuthors = "Albert Gold#2696"
ScriptBuilderUrl = "https://github.com/Alex-Au1/Anime-Game-Identity-Mod-Generator/tree/main/Tools/ScriptBuilder"


ScriptPreamble = f"""
#
# ===== Note =====
#
# This script was auto-generated by AGIDMGen's {ScriptBuilderName} tool, which transforms the
#   library's source code into a single script, for running AGIDMGen without installing it
#
# For more info, check out the Github to {ScriptBuilderName} at:
# {ScriptBuilderUrl}
#
# ***** {ScriptBuilderName} Stats *****
#
# Version: {VersionReplace}
# Authors: {ScriptBuilderAuthors}
# Datetime Ran: {RanDateTimeReplace}
# Run Hash: {RanHashReplace}
#
# *******************************
# ================
#
# ########## START OF AUTO-GENERATED SCRIPT ##########
"""


ScriptPreambleScriptStats = f"""
#
# ***** AGIDMGen Script Stats *****
#
# Version: {VersionReplace}
# Authors: {ScriptBuilderAuthors}
# Datetime Compiled: {BuiltDateTimeReplace}
# Build Hash: {BuildHashReplace}
#
# *********************************
#

"""

# the lines of the preambles that change on every build, which a staleness check leaves out
VolatilePreambleLines = ("# Datetime Ran: ", "# Run Hash: ", "# Datetime Compiled: ", "# Build Hash: ")


# ScriptDependencies: Installs the packages the library is built on before anything imports them
#
# note: the library itself is compiled into the script, but numpy and AG Remap's API (FixRaidenBoss2,
#   a compiled package) cannot be. They are installed with pip the first time the script runs, so a user
#   who has never used pip only needs python itself
ScriptDependencies = f"""
import importlib, importlib.metadata, importlib.util, re, subprocess, sys


# ScriptRequirements: What the script needs installed, as (module to import, requirement for pip)
ScriptRequirements = {DependenciesReplace}


def scriptVersionTuple(version: str):
    match = re.match(r"\\d+(\\.\\d+)*", version)
    return tuple(int(part) for part in match.group(0).split(".")) if (match is not None) else ()


def installScriptRequirements():
    missing = []
    for module, requirement in ScriptRequirements:
        if (importlib.util.find_spec(module) is None):
            missing.append(requirement)
            continue

        # a package reachable without pip (eg. through PYTHONPATH) has no version to read, and is trusted
        try:
            installed = importlib.metadata.version(module)
        except importlib.metadata.PackageNotFoundError:
            continue

        minimum = requirement.partition(">=")[2]
        if (minimum and scriptVersionTuple(installed) < scriptVersionTuple(minimum)):
            missing.append(requirement)

    if (not missing):
        return

    print(f"Installing what this script needs: {{', '.join(missing)}}...")
    try:
        subprocess.check_call([sys.executable, "-m", "pip", "install"] + missing)
    except (OSError, subprocess.CalledProcessError):
        # quoted, since a shell reads the '>' of a requirement as a redirection
        command = " ".join(f'"{{part}}"' for part in [sys.executable, "-m", "pip", "install"] + missing)
        print(f"Could not install {{', '.join(missing)}}. Install them yourself with: {{command}}")
        sys.exit(1)

    importlib.invalidate_caches()


installScriptRequirements()
"""


ScriptMainDriver = f"""

# Main Driver Code
if __name__ == "__main__":
    sys.exit({MainFuncReplace}())
"""
