; Nefer

; Constants -------------------------

; Overrides -------------------------

[TextureOverrideNeferBangsPosition]
hash = 1bf11413
vb0 = ResourceNeferBangsPosition

[TextureOverrideNeferBangsBlend]
hash = 84f23015
vb1 = ResourceNeferBangsBlend
handling = skip
draw = 1613,0

[TextureOverrideNeferBangsTexcoord]
hash = 2d424e7d
vb1 = ResourceNeferBangsTexcoord

[TextureOverrideNeferBangsVertexLimitRaise]
hash = afdeba01

[TextureOverrideNeferBangsIB]
hash = 5a665e02
handling = skip
drawindexed = auto

[TextureOverrideNeferBangsA]
hash = 5a665e02
match_first_index = 0
ib = ResourceNeferBangsAIB
ps-t0 = ResourceNeferBangsANormalMap
ps-t1 = ResourceNeferBangsADiffuse
ps-t2 = ResourceNeferBangsALightMap
run = CommandList\global\ORFix\ORFix

[TextureOverrideNeferBodyPosition]
hash = be085382
vb0 = ResourceNeferBodyPosition

[TextureOverrideNeferBodyBlend]
hash = c034288c
vb1 = ResourceNeferBodyBlend
handling = skip
draw = 25614,0

[TextureOverrideNeferBodyTexcoord]
hash = c0fc7abd
vb1 = ResourceNeferBodyTexcoord

[TextureOverrideNeferBodyVertexLimitRaise]
hash = 540e6acf

[TextureOverrideNeferBodyIB]
hash = 606a6e40
handling = skip
drawindexed = auto

[TextureOverrideNeferBodyA]
hash = 606a6e40
match_first_index = 0
ib = ResourceNeferBodyAIB
ps-t0 = ResourceNeferBodyANormalMap
ps-t1 = ResourceNeferBodyADiffuse
ps-t2 = ResourceNeferBodyALightMap
run = CommandList\global\ORFix\ORFix

[TextureOverrideNeferBodyB]
hash = 606a6e40
match_first_index = 31560
ib = ResourceNeferBodyBIB
ps-t0 = ResourceNeferBodyBNormalMap
ps-t1 = ResourceNeferBodyBDiffuse
ps-t2 = ResourceNeferBodyBLightMap
run = CommandList\global\ORFix\ORFix

[TextureOverrideNeferBodyC]
hash = 606a6e40
match_first_index = 77442
ib = ResourceNeferBodyCIB
ps-t0 = ResourceNeferBodyCNormalMap
ps-t1 = ResourceNeferBodyCDiffuse
ps-t2 = ResourceNeferBodyCLightMap
run = CommandList\global\ORFix\ORFix

[TextureOverrideNeferCapeSidePosition]
hash = 5a2cf942
vb0 = ResourceNeferCapeSidePosition

[TextureOverrideNeferCapeSideBlend]
hash = 568970ae
vb1 = ResourceNeferCapeSideBlend
handling = skip
draw = 1540,0

[TextureOverrideNeferCapeSideTexcoord]
hash = 22e34fe0
vb1 = ResourceNeferCapeSideTexcoord

[TextureOverrideNeferCapeSideVertexLimitRaise]
hash = 29a6299d

[TextureOverrideNeferCapeSideIB]
hash = 345cb65a
handling = skip
drawindexed = auto

[TextureOverrideNeferCapeSideA]
hash = 345cb65a
match_first_index = 0
ib = ResourceNeferCapeSideAIB
ps-t0 = ResourceNeferCapeSideANormalMap
ps-t1 = ResourceNeferCapeSideADiffuse
ps-t2 = ResourceNeferCapeSideALightMap
run = CommandList\global\ORFix\ORFix

[TextureOverrideNeferCapeMiddlePosition]
hash = e3f60e00
vb0 = ResourceNeferCapeMiddlePosition

[TextureOverrideNeferCapeMiddleBlend]
hash = d699e47c
vb1 = ResourceNeferCapeMiddleBlend
handling = skip
draw = 312,0

[TextureOverrideNeferCapeMiddleTexcoord]
hash = c6f5059c
vb1 = ResourceNeferCapeMiddleTexcoord

[TextureOverrideNeferCapeMiddleVertexLimitRaise]
hash = 03672763

[TextureOverrideNeferCapeMiddleIB]
hash = e46f6e57
handling = skip
drawindexed = auto

[TextureOverrideNeferCapeMiddleA]
hash = e46f6e57
match_first_index = 0
ib = ResourceNeferCapeMiddleAIB
ps-t0 = ResourceNeferCapeMiddleANormalMap
ps-t1 = ResourceNeferCapeMiddleADiffuse
ps-t2 = ResourceNeferCapeMiddleALightMap
run = CommandList\global\ORFix\ORFix

[TextureOverrideNeferCapeGlowPosition]
hash = 004b76c5
vb0 = ResourceNeferCapeGlowPosition

[TextureOverrideNeferCapeGlowBlend]
hash = b0a5d3cc
vb1 = ResourceNeferCapeGlowBlend
handling = skip
draw = 368,0

[TextureOverrideNeferCapeGlowTexcoord]
hash = 3eed22cd
vb1 = ResourceNeferCapeGlowTexcoord

[TextureOverrideNeferCapeGlowVertexLimitRaise]
hash = cb6b3186

[TextureOverrideNeferCapeGlowIB]
hash = cd690a66
handling = skip
drawindexed = auto

[TextureOverrideNeferCapeGlowA]
hash = cd690a66
match_first_index = 0
ib = ResourceNeferCapeGlowAIB
ps-t0 = ResourceNeferCapeGlowANormalMap
ps-t1 = ResourceNeferCapeGlowADiffuse
ps-t2 = ResourceNeferCapeGlowALightMap
run = CommandList\global\ORFix\ORFix

[TextureOverrideNeferEyesPosition]
hash = e6b32dac
vb0 = ResourceNeferEyesPosition

[TextureOverrideNeferEyesBlend]
hash = 1defa9a0
vb1 = ResourceNeferEyesBlend
handling = skip
draw = 194,0

[TextureOverrideNeferEyesTexcoord]
hash = 592ef93b
vb1 = ResourceNeferEyesTexcoord

[TextureOverrideNeferEyesVertexLimitRaise]
hash = acfe1118

[TextureOverrideNeferEyesIB]
hash = 6a090a16
handling = skip
drawindexed = auto

[TextureOverrideNeferEyesA]
hash = 6a090a16
match_first_index = 0
ib = ResourceNeferEyesAIB
ps-t0 = ResourceNeferEyesADiffuse
ps-t1 = ResourceNeferEyesALightMap
run = CommandList\global\ORFix\NNFix

[TextureOverrideNeferFaceHeadDiffuse]
hash = 36ff6c29
ps-t0 = ResourceNeferFaceHeadDiffuse


; CommandList -----------------------

; Resources -------------------------

[ResourceNeferBangsPosition]
type = Buffer
stride = 40
filename = NeferBangsPosition.buf

[ResourceNeferBangsBlend]
type = Buffer
stride = 32
filename = NeferBangsBlend.buf

[ResourceNeferBangsTexcoord]
type = Buffer
stride = 12
filename = NeferBangsTexcoord.buf

[ResourceNeferBodyPosition]
type = Buffer
stride = 40
filename = NeferBodyPosition.buf

[ResourceNeferBodyBlend]
type = Buffer
stride = 32
filename = NeferBodyBlend.buf

[ResourceNeferBodyTexcoord]
type = Buffer
stride = 20
filename = NeferBodyTexcoord.buf

[ResourceNeferCapeSidePosition]
type = Buffer
stride = 40
filename = NeferCapeSidePosition.buf

[ResourceNeferCapeSideBlend]
type = Buffer
stride = 32
filename = NeferCapeSideBlend.buf

[ResourceNeferCapeSideTexcoord]
type = Buffer
stride = 12
filename = NeferCapeSideTexcoord.buf

[ResourceNeferCapeMiddlePosition]
type = Buffer
stride = 40
filename = NeferCapeMiddlePosition.buf

[ResourceNeferCapeMiddleBlend]
type = Buffer
stride = 32
filename = NeferCapeMiddleBlend.buf

[ResourceNeferCapeMiddleTexcoord]
type = Buffer
stride = 12
filename = NeferCapeMiddleTexcoord.buf

[ResourceNeferCapeGlowPosition]
type = Buffer
stride = 40
filename = NeferCapeGlowPosition.buf

[ResourceNeferCapeGlowBlend]
type = Buffer
stride = 32
filename = NeferCapeGlowBlend.buf

[ResourceNeferCapeGlowTexcoord]
type = Buffer
stride = 12
filename = NeferCapeGlowTexcoord.buf

[ResourceNeferEyesPosition]
type = Buffer
stride = 40
filename = NeferEyesPosition.buf

[ResourceNeferEyesBlend]
type = Buffer
stride = 32
filename = NeferEyesBlend.buf

[ResourceNeferEyesTexcoord]
type = Buffer
stride = 12
filename = NeferEyesTexcoord.buf

[ResourceNeferBangsAIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = NeferBangsA.ib

[ResourceNeferBodyAIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = NeferBodyA.ib

[ResourceNeferBodyBIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = NeferBodyB.ib

[ResourceNeferBodyCIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = NeferBodyC.ib

[ResourceNeferCapeSideAIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = NeferCapeSideA.ib

[ResourceNeferCapeMiddleAIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = NeferCapeMiddleA.ib

[ResourceNeferCapeGlowAIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = NeferCapeGlowA.ib

[ResourceNeferEyesAIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = NeferEyesA.ib

[ResourceNeferBangsALightMap]
filename = NeferBangsALightMap.dds

[ResourceNeferBangsANormalMap]
filename = NeferBangsANormalMap.dds

[ResourceNeferBangsADiffuse]
filename = NeferBangsADiffuse.dds

[ResourceNeferBodyALightMap]
filename = NeferBodyALightMap.dds

[ResourceNeferBodyANormalMap]
filename = NeferBodyANormalMap.dds

[ResourceNeferBodyADiffuse]
filename = NeferBodyADiffuse.dds

[ResourceNeferBodyBLightMap]
filename = NeferBodyBLightMap.dds

[ResourceNeferBodyBNormalMap]
filename = NeferBodyBNormalMap.dds

[ResourceNeferBodyBDiffuse]
filename = NeferBodyBDiffuse.dds

[ResourceNeferBodyCLightMap]
filename = NeferBodyCLightMap.dds

[ResourceNeferBodyCNormalMap]
filename = NeferBodyCNormalMap.dds

[ResourceNeferBodyCDiffuse]
filename = NeferBodyCDiffuse.dds

[ResourceNeferCapeSideALightMap]
filename = NeferCapeSideALightMap.dds

[ResourceNeferCapeSideANormalMap]
filename = NeferCapeSideANormalMap.dds

[ResourceNeferCapeSideADiffuse]
filename = NeferCapeSideADiffuse.dds

[ResourceNeferCapeMiddleALightMap]
filename = NeferCapeMiddleALightMap.dds

[ResourceNeferCapeMiddleANormalMap]
filename = NeferCapeMiddleANormalMap.dds

[ResourceNeferCapeMiddleADiffuse]
filename = NeferCapeMiddleADiffuse.dds

[ResourceNeferCapeGlowALightMap]
filename = NeferCapeGlowALightMap.dds

[ResourceNeferCapeGlowANormalMap]
filename = NeferCapeGlowANormalMap.dds

[ResourceNeferCapeGlowADiffuse]
filename = NeferCapeGlowADiffuse.dds

[ResourceNeferEyesALightMap]
filename = NeferEyesALightMap.dds

[ResourceNeferEyesADiffuse]
filename = NeferEyesADiffuse.dds

[ResourceNeferFaceHeadDiffuse]
filename = NeferFaceADiffuse.dds


; the identity mod of Nefer: the game's own model out of its download folder (tmp52r6pymd), built by AGIDMGen
