; KaeyaSailwind

; Constants -------------------------

; Overrides -------------------------

[TextureOverrideKaeyaSailwindPosition]
hash = b9b77eff
vb0 = ResourceKaeyaSailwindPosition

[TextureOverrideKaeyaSailwindBlend]
hash = e026c9ae
vb1 = ResourceKaeyaSailwindBlend
handling = skip
draw = 21365,0

[TextureOverrideKaeyaSailwindTexcoord]
hash = 74dce34a
vb1 = ResourceKaeyaSailwindTexcoord

[TextureOverrideKaeyaSailwindVertexLimitRaise]
hash = bdb6e3b7

[TextureOverrideKaeyaSailwindIB]
hash = 59f2a0f2
handling = skip
drawindexed = auto

[TextureOverrideKaeyaSailwindHead]
hash = 59f2a0f2
match_first_index = 0
ib = ResourceKaeyaSailwindHeadIB
ps-t0 = ResourceKaeyaSailwindHeadDiffuse
ps-t1 = ResourceKaeyaSailwindHeadLightMap
run = CommandList\global\ORFix\NNFix

[TextureOverrideKaeyaSailwindBody]
hash = 59f2a0f2
match_first_index = 23109
ib = ResourceKaeyaSailwindBodyIB
ps-t0 = ResourceKaeyaSailwindBodyDiffuse
ps-t1 = ResourceKaeyaSailwindBodyLightMap
run = CommandList\global\ORFix\NNFix

[TextureOverrideKaeyaSailwindDress]
hash = 59f2a0f2
match_first_index = 76839
ib = ResourceKaeyaSailwindDressIB
ps-t0 = ResourceKaeyaSailwindDressDiffuse
ps-t1 = ResourceKaeyaSailwindDressLightMap
run = CommandList\global\ORFix\NNFix

[TextureOverrideKaeyaSailwindFaceHeadDiffuse]
hash = 4e6a8e9d
ps-t0 = ResourceKaeyaSailwindFaceHeadDiffuse


; CommandList -----------------------

; Resources -------------------------

[ResourceKaeyaSailwindPosition]
type = Buffer
stride = 40
filename = KaeyaSailwindPosition.buf

[ResourceKaeyaSailwindBlend]
type = Buffer
stride = 32
filename = KaeyaSailwindBlend.buf

[ResourceKaeyaSailwindTexcoord]
type = Buffer
stride = 20
filename = KaeyaSailwindTexcoord.buf

[ResourceKaeyaSailwindHeadIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = KaeyaSailwindHead.ib

[ResourceKaeyaSailwindBodyIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = KaeyaSailwindBody.ib

[ResourceKaeyaSailwindDressIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = KaeyaSailwindDress.ib

[ResourceKaeyaSailwindHeadDiffuse]
filename = KaeyaSailwindHeadDiffuse.dds

[ResourceKaeyaSailwindHeadLightMap]
filename = KaeyaSailwindHeadLightMap.dds

[ResourceKaeyaSailwindHeadMetalMap]
filename = KaeyaSailwindHeadMetalMap.dds

[ResourceKaeyaSailwindBodyDiffuse]
filename = KaeyaSailwindBodyDiffuse.dds

[ResourceKaeyaSailwindBodyLightMap]
filename = KaeyaSailwindBodyLightMap.dds

[ResourceKaeyaSailwindBodyMetalMap]
filename = KaeyaSailwindBodyMetalMap.dds

[ResourceKaeyaSailwindDressDiffuse]
filename = KaeyaSailwindDressDiffuse.dds

[ResourceKaeyaSailwindDressLightMap]
filename = KaeyaSailwindDressLightMap.dds

[ResourceKaeyaSailwindDressMetalMap]
filename = KaeyaSailwindDressMetalMap.dds

[ResourceKaeyaSailwindFaceHeadDiffuse]
filename = KaeyaSailwindFaceHeadDiffuse.dds


; the identity mod of KaeyaSailwind: the game's own model out of its download folder (GI/KaeyaSailwind/6_8), built by AGIDMGen
