; Kinich

; Constants -------------------------

; Overrides -------------------------

[TextureOverrideKinichPosition]
hash = 42796c33
vb0 = ResourceKinichPosition

[TextureOverrideKinichBlend]
hash = b0e783a9
vb1 = ResourceKinichBlend
handling = skip
draw = 27185,0

[TextureOverrideKinichTexcoord]
hash = c7ac7533
vb1 = ResourceKinichTexcoord

[TextureOverrideKinichVertexLimitRaise]
hash = e8208df7

[TextureOverrideKinichIB]
hash = bceefe19
handling = skip
drawindexed = auto

[TextureOverrideKinichHead]
hash = bceefe19
match_first_index = 0
ib = ResourceKinichHeadIB
ps-t0 = ResourceKinichHeadNormalMap
ps-t1 = ResourceKinichHeadDiffuse
ps-t2 = ResourceKinichHeadLightMap
run = CommandList\global\ORFix\ORFix

[TextureOverrideKinichBody]
hash = bceefe19
match_first_index = 51039
ib = ResourceKinichBodyIB
ps-t0 = ResourceKinichBodyNormalMap
ps-t1 = ResourceKinichBodyDiffuse
ps-t2 = ResourceKinichBodyLightMap
run = CommandList\global\ORFix\ORFix

[TextureOverrideKinichFaceHeadDiffuse]
hash = 849c6d75
ps-t0 = ResourceKinichFaceHeadDiffuse


; CommandList -----------------------

; Resources -------------------------

[ResourceKinichPosition]
type = Buffer
stride = 40
filename = KinichPosition.buf

[ResourceKinichBlend]
type = Buffer
stride = 32
filename = KinichBlend.buf

[ResourceKinichTexcoord]
type = Buffer
stride = 12
filename = KinichTexcoord.buf

[ResourceKinichHeadIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = KinichHead.ib

[ResourceKinichBodyIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = KinichBody.ib

[ResourceKinichHeadNormalMap]
filename = KinichHeadNormalMap.dds

[ResourceKinichHeadDiffuse]
filename = KinichHeadDiffuse.dds

[ResourceKinichHeadLightMap]
filename = KinichHeadLightMap.dds

[ResourceKinichBodyNormalMap]
filename = KinichBodyNormalMap.dds

[ResourceKinichBodyDiffuse]
filename = KinichBodyDiffuse.dds

[ResourceKinichBodyLightMap]
filename = KinichBodyLightMap.dds

[ResourceKinichFaceHeadDiffuse]
filename = KinichFaceHeadDiffuse.dds


; the identity mod of Kinich: the game's own model out of its download folder (tmpp1uqixa2), built by AGIDMGen
