; Chongyun

; Constants -------------------------

; Overrides -------------------------

[TextureOverrideChongyunPosition]
hash = 489e3621
vb0 = ResourceChongyunPosition

[TextureOverrideChongyunBlend]
hash = 2f997aab
vb1 = ResourceChongyunBlend
handling = skip
draw = 12027,0

[TextureOverrideChongyunTexcoord]
hash = 93136ff7
vb1 = ResourceChongyunTexcoord

[TextureOverrideChongyunVertexLimitRaise]
hash = 2ceb44ef

[TextureOverrideChongyunIB]
hash = 0c6dd2d6
handling = skip
drawindexed = auto

[TextureOverrideChongyunHead]
hash = 0c6dd2d6
match_first_index = 0
ib = ResourceChongyunHeadIB
ps-t0 = ResourceChongyunHeadDiffuse
ps-t1 = ResourceChongyunHeadLightMap
run = CommandList\global\ORFix\NNFix

[TextureOverrideChongyunBody]
hash = 0c6dd2d6
match_first_index = 13656
ib = ResourceChongyunBodyIB
ps-t0 = ResourceChongyunBodyDiffuse
ps-t1 = ResourceChongyunBodyLightMap
run = CommandList\global\ORFix\NNFix

[TextureOverrideChongyunFaceHeadDiffuse]
hash = b8f33342
ps-t0 = ResourceChongyunFaceHeadDiffuse


; CommandList -----------------------

; Resources -------------------------

[ResourceChongyunPosition]
type = Buffer
stride = 40
filename = ChongyunPosition.buf

[ResourceChongyunBlend]
type = Buffer
stride = 32
filename = ChongyunBlend.buf

[ResourceChongyunTexcoord]
type = Buffer
stride = 12
filename = ChongyunTexcoord.buf

[ResourceChongyunHeadIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = ChongyunHead.ib

[ResourceChongyunBodyIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = ChongyunBody.ib

[ResourceChongyunHeadDiffuse]
filename = ChongyunHeadDiffuse.dds

[ResourceChongyunHeadLightMap]
filename = ChongyunHeadLightMap.dds

[ResourceChongyunBodyDiffuse]
filename = ChongyunBodyDiffuse.dds

[ResourceChongyunBodyLightMap]
filename = ChongyunBodyLightMap.dds

[ResourceChongyunFaceHeadDiffuse]
filename = ChongyunFaceHeadDiffuse.dds


; the identity mod of Chongyun: the game's own model out of its download folder (tmpk880vynw), built by AGIDMGen
