; Iansan

; Constants -------------------------

; Overrides -------------------------

[TextureOverrideIansanPosition]
hash = 6891e2e2
vb0 = ResourceIansanPosition

[TextureOverrideIansanBlend]
hash = 8ad596c6
vb1 = ResourceIansanBlend
handling = skip
draw = 22742,0

[TextureOverrideIansanTexcoord]
hash = 0f6cf75b
vb1 = ResourceIansanTexcoord

[TextureOverrideIansanVertexLimitRaise]
hash = 7820204c

[TextureOverrideIansanIB]
hash = b5263389
handling = skip
drawindexed = auto

[TextureOverrideIansanHead]
hash = b5263389
match_first_index = 0
ib = ResourceIansanHeadIB
ps-t0 = ResourceIansanHeadNormalMap
ps-t1 = ResourceIansanHeadDiffuse
ps-t2 = ResourceIansanHeadLightMap
run = CommandList\global\ORFix\ORFix

[TextureOverrideIansanBody]
hash = b5263389
match_first_index = 33132
ib = ResourceIansanBodyIB
ps-t0 = ResourceIansanBodyNormalMap
ps-t1 = ResourceIansanBodyDiffuse
ps-t2 = ResourceIansanBodyLightMap
run = CommandList\global\ORFix\ORFix

[TextureOverrideIansanDress]
hash = b5263389
match_first_index = 79230
ib = ResourceIansanDressIB
ps-t0 = ResourceIansanDressNormalMap
ps-t1 = ResourceIansanDressDiffuse
ps-t2 = ResourceIansanDressLightMap
run = CommandList\global\ORFix\ORFix

[TextureOverrideIansanFaceHeadDiffuse]
hash = 00bdf455
ps-t0 = ResourceIansanFaceHeadDiffuse


; CommandList -----------------------

; Resources -------------------------

[ResourceIansanPosition]
type = Buffer
stride = 40
filename = IansanPosition.buf

[ResourceIansanBlend]
type = Buffer
stride = 32
filename = IansanBlend.buf

[ResourceIansanTexcoord]
type = Buffer
stride = 20
filename = IansanTexcoord.buf

[ResourceIansanHeadIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = IansanHead.ib

[ResourceIansanBodyIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = IansanBody.ib

[ResourceIansanDressIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = IansanDress.ib

[ResourceIansanHeadNormalMap]
filename = IansanHeadNormalMap.dds

[ResourceIansanHeadDiffuse]
filename = IansanHeadDiffuse.dds

[ResourceIansanHeadLightMap]
filename = IansanHeadLightMap.dds

[ResourceIansanBodyNormalMap]
filename = IansanBodyNormalMap.dds

[ResourceIansanBodyDiffuse]
filename = IansanBodyDiffuse.dds

[ResourceIansanBodyLightMap]
filename = IansanBodyLightMap.dds

[ResourceIansanDressNormalMap]
filename = IansanDressNormalMap.dds

[ResourceIansanDressDiffuse]
filename = IansanDressDiffuse.dds

[ResourceIansanDressLightMap]
filename = IansanDressLightMap.dds

[ResourceIansanFaceHeadDiffuse]
filename = IansanFaceHeadDiffuse.dds


; the identity mod of Iansan: the game's own model out of its download folder (tmp84e1qfp8), built by AGIDMGen
