; XingqiuBamboo

; Constants -------------------------

; Overrides -------------------------

[TextureOverrideXingqiuBambooPosition]
hash = cc158a1e
vb0 = ResourceXingqiuBambooPosition

[TextureOverrideXingqiuBambooBlend]
hash = 07c7c5b6
vb1 = ResourceXingqiuBambooBlend
handling = skip
draw = 20494,0

[TextureOverrideXingqiuBambooTexcoord]
hash = 41426386
vb1 = ResourceXingqiuBambooTexcoord

[TextureOverrideXingqiuBambooVertexLimitRaise]
hash = 3944dfbd

[TextureOverrideXingqiuBambooIB]
hash = 76df4025
handling = skip
drawindexed = auto

[TextureOverrideXingqiuBambooHead]
hash = 76df4025
match_first_index = 0
ib = ResourceXingqiuBambooHeadIB
ps-t0 = ResourceXingqiuBambooHeadDiffuse
ps-t1 = ResourceXingqiuBambooHeadLightMap
run = CommandList\global\ORFix\NNFix

[TextureOverrideXingqiuBambooBody]
hash = 76df4025
match_first_index = 32508
ib = ResourceXingqiuBambooBodyIB
ps-t0 = ResourceXingqiuBambooBodyDiffuse
ps-t1 = ResourceXingqiuBambooBodyLightMap
run = CommandList\global\ORFix\NNFix

[TextureOverrideXingqiuBambooDress]
hash = 76df4025
match_first_index = 62103
ib = ResourceXingqiuBambooDressIB
ps-t0 = ResourceXingqiuBambooDressDiffuse
ps-t1 = ResourceXingqiuBambooDressLightMap
run = CommandList\global\ORFix\NNFix


; CommandList -----------------------

; Resources -------------------------

[ResourceXingqiuBambooPosition]
type = Buffer
stride = 40
filename = XingqiuBambooPosition.buf

[ResourceXingqiuBambooBlend]
type = Buffer
stride = 32
filename = XingqiuBambooBlend.buf

[ResourceXingqiuBambooTexcoord]
type = Buffer
stride = 20
filename = XingqiuBambooTexcoord.buf

[ResourceXingqiuBambooHeadIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = XingqiuBambooHead.ib

[ResourceXingqiuBambooBodyIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = XingqiuBambooBody.ib

[ResourceXingqiuBambooDressIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = XingqiuBambooDress.ib

[ResourceXingqiuBambooHeadDiffuse]
filename = XingqiuBambooHeadDiffuse.dds

[ResourceXingqiuBambooHeadLightMap]
filename = XingqiuBambooHeadLightMap.dds

[ResourceXingqiuBambooBodyDiffuse]
filename = XingqiuBambooBodyDiffuse.dds

[ResourceXingqiuBambooBodyLightMap]
filename = XingqiuBambooBodyLightMap.dds

[ResourceXingqiuBambooBodyMetalMap]
filename = XingqiuBambooBodyMetalMap.dds

[ResourceXingqiuBambooDressDiffuse]
filename = XingqiuBambooDressDiffuse.dds

[ResourceXingqiuBambooDressLightMap]
filename = XingqiuBambooDressLightMap.dds

[ResourceXingqiuBambooDressMetalMap]
filename = XingqiuBambooDressMetalMap.dds


; the identity mod of XingqiuBamboo: the game's own model out of its download folder (tmpe79tc9a3), built by AGIDMGen
