; AratakiItto

; Constants -------------------------

; Overrides -------------------------

[TextureOverrideAratakiIttoPosition]
hash = 3e61a41f
vb0 = ResourceAratakiIttoPosition

[TextureOverrideAratakiIttoBlend]
hash = f186e87b
vb1 = ResourceAratakiIttoBlend
handling = skip
draw = 17853,0

[TextureOverrideAratakiIttoTexcoord]
hash = 5bcab405
vb1 = ResourceAratakiIttoTexcoord

[TextureOverrideAratakiIttoVertexLimitRaise]
hash = 57a9ae8b

[TextureOverrideAratakiIttoIB]
hash = be597118
handling = skip
drawindexed = auto

[TextureOverrideAratakiIttoHead]
hash = be597118
match_first_index = 0
ib = ResourceAratakiIttoHeadIB
ps-t0 = ResourceAratakiIttoHeadDiffuse
ps-t1 = ResourceAratakiIttoHeadLightMap
run = CommandList\global\ORFix\NNFix

[TextureOverrideAratakiIttoBody]
hash = be597118
match_first_index = 26520
ib = ResourceAratakiIttoBodyIB
ps-t0 = ResourceAratakiIttoBodyDiffuse
ps-t1 = ResourceAratakiIttoBodyLightMap
run = CommandList\global\ORFix\NNFix

[TextureOverrideAratakiIttoFaceHeadDiffuse]
hash = 5eb50bfb
ps-t0 = ResourceAratakiIttoFaceHeadDiffuse


; CommandList -----------------------

; Resources -------------------------

[ResourceAratakiIttoPosition]
type = Buffer
stride = 40
filename = AratakiIttoPosition.buf

[ResourceAratakiIttoBlend]
type = Buffer
stride = 32
filename = AratakiIttoBlend.buf

[ResourceAratakiIttoTexcoord]
type = Buffer
stride = 12
filename = AratakiIttoTexcoord.buf

[ResourceAratakiIttoHeadIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = AratakiIttoHead.ib

[ResourceAratakiIttoBodyIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = AratakiIttoBody.ib

[ResourceAratakiIttoHeadDiffuse]
filename = AratakiIttoHeadDiffuse.dds

[ResourceAratakiIttoHeadLightMap]
filename = AratakiIttoHeadLightMap.dds

[ResourceAratakiIttoBodyDiffuse]
filename = AratakiIttoBodyDiffuse.dds

[ResourceAratakiIttoBodyLightMap]
filename = AratakiIttoBodyLightMap.dds

[ResourceAratakiIttoFaceHeadDiffuse]
filename = AratakiIttoFaceHeadDiffuse.dds


; the identity mod of AratakiItto: the game's own model out of its download folder (tmpmqu7n12v), built by AGIDMGen
