; CherryHuTao

; Constants -------------------------

; Overrides -------------------------

[TextureOverrideCherryHuTaoPosition]
hash = a78db232
vb0 = ResourceCherryHuTaoPosition

[TextureOverrideCherryHuTaoBlend]
hash = 6e718139
vb1 = ResourceCherryHuTaoBlend
handling = skip
draw = 23136,0

[TextureOverrideCherryHuTaoTexcoord]
hash = 4b14b10e
vb1 = ResourceCherryHuTaoTexcoord

[TextureOverrideCherryHuTaoVertexLimitRaise]
hash = 6715905e

[TextureOverrideCherryHuTaoIB]
hash = 92fce51e
handling = skip
drawindexed = auto

[TextureOverrideCherryHuTaoHead]
hash = 92fce51e
match_first_index = 0
ib = ResourceCherryHuTaoHeadIB
ps-t0 = ResourceCherryHuTaoHeadDiffuse
ps-t1 = ResourceCherryHuTaoHeadLightMap
run = CommandList\global\ORFix\NNFix

[TextureOverrideCherryHuTaoBody]
hash = 92fce51e
match_first_index = 43968
ib = ResourceCherryHuTaoBodyIB
ps-t0 = ResourceCherryHuTaoBodyDiffuse
ps-t1 = ResourceCherryHuTaoBodyLightMap
run = CommandList\global\ORFix\NNFix

[TextureOverrideCherryHuTaoDress]
hash = 92fce51e
match_first_index = 77301
ib = ResourceCherryHuTaoDressIB
ps-t0 = ResourceCherryHuTaoDressDiffuse
ps-t1 = ResourceCherryHuTaoDressLightMap
run = CommandList\global\ORFix\NNFix

[TextureOverrideCherryHuTaoExtra]
hash = 92fce51e
match_first_index = 86808
ib = ResourceCherryHuTaoExtraIB
ps-t0 = ResourceCherryHuTaoExtraDiffuse
run = CommandList\global\ORFix\NNFix


; CommandList -----------------------

; Resources -------------------------

[ResourceCherryHuTaoPosition]
type = Buffer
stride = 40
filename = CherryHuTaoPosition.buf

[ResourceCherryHuTaoBlend]
type = Buffer
stride = 32
filename = CherryHuTaoBlend.buf

[ResourceCherryHuTaoTexcoord]
type = Buffer
stride = 28
filename = CherryHuTaoTexcoord.buf

[ResourceCherryHuTaoHeadIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = CherryHuTaoHead.ib

[ResourceCherryHuTaoBodyIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = CherryHuTaoBody.ib

[ResourceCherryHuTaoDressIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = CherryHuTaoDress.ib

[ResourceCherryHuTaoExtraIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = CherryHuTaoExtra.ib

[ResourceCherryHuTaoHeadDiffuse]
filename = CherryHuTaoHeadDiffuse.dds

[ResourceCherryHuTaoHeadLightMap]
filename = CherryHuTaoHeadLightMap.dds

[ResourceCherryHuTaoBodyDiffuse]
filename = CherryHuTaoBodyDiffuse.dds

[ResourceCherryHuTaoBodyLightMap]
filename = CherryHuTaoBodyLightMap.dds

[ResourceCherryHuTaoDressDiffuse]
filename = CherryHuTaoDressDiffuse.dds

[ResourceCherryHuTaoDressLightMap]
filename = CherryHuTaoDressLightMap.dds

[ResourceCherryHuTaoExtraDiffuse]
filename = CherryHuTaoExtraDiffuse.dds


; the identity mod of CherryHuTao: the game's own model out of its download folder (GI/CherryHuTao/5_3), built by AGIDMGen
