; Lisa

; Constants -------------------------

; Overrides -------------------------

[TextureOverrideLisaPosition]
hash = 2a557add
vb0 = ResourceLisaPosition

[TextureOverrideLisaBlend]
hash = 8bfa989d
vb1 = ResourceLisaBlend
handling = skip
draw = 13644,0

[TextureOverrideLisaTexcoord]
hash = 92b87c71
vb1 = ResourceLisaTexcoord

[TextureOverrideLisaVertexLimitRaise]
hash = e6af2c6d

[TextureOverrideLisaIB]
hash = 518a6840
handling = skip
drawindexed = auto

[TextureOverrideLisaHead]
hash = 518a6840
match_first_index = 0
ib = ResourceLisaHeadIB
ps-t0 = ResourceLisaHeadDiffuse
ps-t1 = ResourceLisaHeadLightMap
run = CommandList\global\ORFix\NNFix

[TextureOverrideLisaBody]
hash = 518a6840
match_first_index = 16815
ib = ResourceLisaBodyIB
ps-t0 = ResourceLisaBodyDiffuse
ps-t1 = ResourceLisaBodyLightMap
run = CommandList\global\ORFix\NNFix

[TextureOverrideLisaDress]
hash = 518a6840
match_first_index = 45873
ib = ResourceLisaDressIB
ps-t0 = ResourceLisaDressDiffuse
ps-t1 = ResourceLisaDressLightMap
run = CommandList\global\ORFix\NNFix

[TextureOverrideLisaFaceHeadDiffuse]
hash = 66bea1c9
ps-t0 = ResourceLisaFaceHeadDiffuse


; CommandList -----------------------

; Resources -------------------------

[ResourceLisaPosition]
type = Buffer
stride = 40
filename = LisaPosition.buf

[ResourceLisaBlend]
type = Buffer
stride = 32
filename = LisaBlend.buf

[ResourceLisaTexcoord]
type = Buffer
stride = 20
filename = LisaTexcoord.buf

[ResourceLisaHeadIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = LisaHead.ib

[ResourceLisaBodyIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = LisaBody.ib

[ResourceLisaDressIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = LisaDress.ib

[ResourceLisaHeadDiffuse]
filename = LisaHeadDiffuse.dds

[ResourceLisaHeadLightMap]
filename = LisaHeadLightMap.dds

[ResourceLisaBodyDiffuse]
filename = LisaBodyDiffuse.dds

[ResourceLisaBodyLightMap]
filename = LisaBodyLightMap.dds

[ResourceLisaDressDiffuse]
filename = LisaDressDiffuse.dds

[ResourceLisaDressLightMap]
filename = LisaDressLightMap.dds

[ResourceLisaFaceHeadDiffuse]
filename = LisaFaceHeadDiffuse.dds


; the identity mod of Lisa: the game's own model out of its download folder (GI/Lisa/6_8), built by AGIDMGen
