; Thoma

; Constants -------------------------

; Overrides -------------------------

[TextureOverrideThomaPosition]
hash = 24ecd71a
vb0 = ResourceThomaPosition

[TextureOverrideThomaBlend]
hash = 1fb4b2dd
vb1 = ResourceThomaBlend
handling = skip
draw = 13558,0

[TextureOverrideThomaTexcoord]
hash = 1b428e0a
vb1 = ResourceThomaTexcoord

[TextureOverrideThomaVertexLimitRaise]
hash = ba27d574

[TextureOverrideThomaIB]
hash = b2155854
handling = skip
drawindexed = auto

[TextureOverrideThomaHead]
hash = b2155854
match_first_index = 0
ib = ResourceThomaHeadIB
ps-t0 = ResourceThomaHeadDiffuse
ps-t1 = ResourceThomaHeadLightMap
run = CommandList\global\ORFix\NNFix

[TextureOverrideThomaBody]
hash = b2155854
match_first_index = 10782
ib = ResourceThomaBodyIB
ps-t0 = ResourceThomaBodyDiffuse
ps-t1 = ResourceThomaBodyLightMap
run = CommandList\global\ORFix\NNFix

[TextureOverrideThomaDress]
hash = b2155854
match_first_index = 45258
ib = ResourceThomaDressIB
ps-t0 = ResourceThomaDressDiffuse
ps-t1 = ResourceThomaDressLightMap
run = CommandList\global\ORFix\NNFix

[TextureOverrideThomaFaceHeadDiffuse]
hash = ac81584f
ps-t0 = ResourceThomaFaceHeadDiffuse


; CommandList -----------------------

; Resources -------------------------

[ResourceThomaPosition]
type = Buffer
stride = 40
filename = ThomaPosition.buf

[ResourceThomaBlend]
type = Buffer
stride = 32
filename = ThomaBlend.buf

[ResourceThomaTexcoord]
type = Buffer
stride = 20
filename = ThomaTexcoord.buf

[ResourceThomaHeadIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = ThomaHead.ib

[ResourceThomaBodyIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = ThomaBody.ib

[ResourceThomaDressIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = ThomaDress.ib

[ResourceThomaHeadDiffuse]
filename = ThomaHeadDiffuse.dds

[ResourceThomaHeadLightMap]
filename = ThomaHeadLightMap.dds

[ResourceThomaBodyDiffuse]
filename = ThomaBodyDiffuse.dds

[ResourceThomaBodyLightMap]
filename = ThomaBodyLightMap.dds

[ResourceThomaDressDiffuse]
filename = ThomaDressDiffuse.dds

[ResourceThomaDressLightMap]
filename = ThomaDressLightMap.dds

[ResourceThomaFaceHeadDiffuse]
filename = ThomaFaceHeadDiffuse.dds


; the identity mod of Thoma: the game's own model out of its download folder (tmputihebw_), built by AGIDMGen
