; Sigewinne

; Constants -------------------------

; Overrides -------------------------

[TextureOverrideSigewinnePosition]
hash = c883a144
vb0 = ResourceSigewinnePosition

[TextureOverrideSigewinneBlend]
hash = 1855ae41
vb1 = ResourceSigewinneBlend
handling = skip
draw = 16975,0

[TextureOverrideSigewinneTexcoord]
hash = defddf41
vb1 = ResourceSigewinneTexcoord

[TextureOverrideSigewinneVertexLimitRaise]
hash = c32376aa

[TextureOverrideSigewinneIB]
hash = 072fe941
handling = skip
drawindexed = auto

[TextureOverrideSigewinneHead]
hash = 072fe941
match_first_index = 0
ib = ResourceSigewinneHeadIB
ps-t0 = ResourceSigewinneHeadNormalMap
ps-t1 = ResourceSigewinneHeadDiffuse
ps-t2 = ResourceSigewinneHeadLightMap
run = CommandList\global\ORFix\ORFix

[TextureOverrideSigewinneBody]
hash = 072fe941
match_first_index = 25077
ib = ResourceSigewinneBodyIB
ps-t0 = ResourceSigewinneBodyNormalMap
ps-t1 = ResourceSigewinneBodyDiffuse
ps-t2 = ResourceSigewinneBodyLightMap
run = CommandList\global\ORFix\ORFix

[TextureOverrideSigewinneFaceHeadDiffuse]
hash = 44ec805d
ps-t0 = ResourceSigewinneFaceHeadDiffuse


; CommandList -----------------------

; Resources -------------------------

[ResourceSigewinnePosition]
type = Buffer
stride = 40
filename = SigewinnePosition.buf

[ResourceSigewinneBlend]
type = Buffer
stride = 32
filename = SigewinneBlend.buf

[ResourceSigewinneTexcoord]
type = Buffer
stride = 12
filename = SigewinneTexcoord.buf

[ResourceSigewinneHeadIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = SigewinneHead.ib

[ResourceSigewinneBodyIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = SigewinneBody.ib

[ResourceSigewinneHeadNormalMap]
filename = SigewinneHeadNormalMap.dds

[ResourceSigewinneHeadDiffuse]
filename = SigewinneHeadDiffuse.dds

[ResourceSigewinneHeadLightMap]
filename = SigewinneHeadLightMap.dds

[ResourceSigewinneBodyNormalMap]
filename = SigewinneBodyNormalMap.dds

[ResourceSigewinneBodyDiffuse]
filename = SigewinneBodyDiffuse.dds

[ResourceSigewinneBodyLightMap]
filename = SigewinneBodyLightMap.dds

[ResourceSigewinneFaceHeadDiffuse]
filename = SigewinneFaceHeadDiffuse.dds


; the identity mod of Sigewinne: the game's own model out of its download folder (tmpchg_hyqs), built by AGIDMGen
