; SangonomiyaKokomi

; Constants -------------------------

; Overrides -------------------------

[TextureOverrideSangonomiyaKokomiPosition]
hash = dde4750a
vb0 = ResourceSangonomiyaKokomiPosition

[TextureOverrideSangonomiyaKokomiBlend]
hash = 7b61fb15
vb1 = ResourceSangonomiyaKokomiBlend
handling = skip
draw = 13790,0

[TextureOverrideSangonomiyaKokomiTexcoord]
hash = 4ed0c9f8
vb1 = ResourceSangonomiyaKokomiTexcoord

[TextureOverrideSangonomiyaKokomiVertexLimitRaise]
hash = 66c6fb0a

[TextureOverrideSangonomiyaKokomiIB]
hash = 74900c81
handling = skip
drawindexed = auto

[TextureOverrideSangonomiyaKokomiHead]
hash = 74900c81
match_first_index = 0
ib = ResourceSangonomiyaKokomiHeadIB
ps-t0 = ResourceSangonomiyaKokomiHeadDiffuse
ps-t1 = ResourceSangonomiyaKokomiHeadLightMap
run = CommandList\global\ORFix\NNFix

[TextureOverrideSangonomiyaKokomiBody]
hash = 74900c81
match_first_index = 26424
ib = ResourceSangonomiyaKokomiBodyIB
ps-t0 = ResourceSangonomiyaKokomiBodyDiffuse
ps-t1 = ResourceSangonomiyaKokomiBodyLightMap
run = CommandList\global\ORFix\NNFix

[TextureOverrideSangonomiyaKokomiDress]
hash = 74900c81
match_first_index = 52290
ib = ResourceSangonomiyaKokomiDressIB
ps-t0 = ResourceSangonomiyaKokomiDressDiffuse
ps-t1 = ResourceSangonomiyaKokomiDressLightMap
run = CommandList\global\ORFix\NNFix

[TextureOverrideSangonomiyaKokomiFaceHeadDiffuse]
hash = 394fb133
ps-t0 = ResourceSangonomiyaKokomiFaceHeadDiffuse


; CommandList -----------------------

; Resources -------------------------

[ResourceSangonomiyaKokomiPosition]
type = Buffer
stride = 40
filename = SangonomiyaKokomiPosition.buf

[ResourceSangonomiyaKokomiBlend]
type = Buffer
stride = 32
filename = SangonomiyaKokomiBlend.buf

[ResourceSangonomiyaKokomiTexcoord]
type = Buffer
stride = 20
filename = SangonomiyaKokomiTexcoord.buf

[ResourceSangonomiyaKokomiHeadIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = SangonomiyaKokomiHead.ib

[ResourceSangonomiyaKokomiBodyIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = SangonomiyaKokomiBody.ib

[ResourceSangonomiyaKokomiDressIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = SangonomiyaKokomiDress.ib

[ResourceSangonomiyaKokomiHeadDiffuse]
filename = SangonomiyaKokomiHeadDiffuse.dds

[ResourceSangonomiyaKokomiHeadLightMap]
filename = SangonomiyaKokomiHeadLightMap.dds

[ResourceSangonomiyaKokomiBodyDiffuse]
filename = SangonomiyaKokomiBodyDiffuse.dds

[ResourceSangonomiyaKokomiBodyLightMap]
filename = SangonomiyaKokomiBodyLightMap.dds

[ResourceSangonomiyaKokomiDressDiffuse]
filename = SangonomiyaKokomiDressDiffuse.dds

[ResourceSangonomiyaKokomiDressLightMap]
filename = SangonomiyaKokomiDressLightMap.dds

[ResourceSangonomiyaKokomiFaceHeadDiffuse]
filename = SangonomiyaKokomiFaceHeadDiffuse.dds


; the identity mod of SangonomiyaKokomi: the game's own model out of its download folder (GI/SangonomiyaKokomi/6_8), built by AGIDMGen
