; Freminet

; Constants -------------------------

; Overrides -------------------------

[TextureOverrideFreminetPosition]
hash = 86559a85
vb0 = ResourceFreminetPosition

[TextureOverrideFreminetBlend]
hash = dc9e9ad0
vb1 = ResourceFreminetBlend
handling = skip
draw = 25318,0

[TextureOverrideFreminetTexcoord]
hash = 4000c72b
vb1 = ResourceFreminetTexcoord

[TextureOverrideFreminetVertexLimitRaise]
hash = 7bf55145

[TextureOverrideFreminetIB]
hash = 6d40de64
handling = skip
drawindexed = auto

[TextureOverrideFreminetHead]
hash = 6d40de64
match_first_index = 0
ib = ResourceFreminetHeadIB
ps-t0 = ResourceFreminetHeadNormalMap
ps-t1 = ResourceFreminetHeadDiffuse
ps-t2 = ResourceFreminetHeadLightMap
run = CommandList\global\ORFix\ORFix

[TextureOverrideFreminetBody]
hash = 6d40de64
match_first_index = 36975
ib = ResourceFreminetBodyIB
ps-t0 = ResourceFreminetBodyNormalMap
ps-t1 = ResourceFreminetBodyDiffuse
ps-t2 = ResourceFreminetBodyLightMap
run = CommandList\global\ORFix\ORFix

[TextureOverrideFreminetFaceHeadDiffuse]
hash = e35468b8
ps-t0 = ResourceFreminetFaceHeadDiffuse


; CommandList -----------------------

; Resources -------------------------

[ResourceFreminetPosition]
type = Buffer
stride = 40
filename = FreminetPosition.buf

[ResourceFreminetBlend]
type = Buffer
stride = 32
filename = FreminetBlend.buf

[ResourceFreminetTexcoord]
type = Buffer
stride = 12
filename = FreminetTexcoord.buf

[ResourceFreminetHeadIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = FreminetHead.ib

[ResourceFreminetBodyIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = FreminetBody.ib

[ResourceFreminetHeadNormalMap]
filename = FreminetHeadNormalMap.dds

[ResourceFreminetHeadDiffuse]
filename = FreminetHeadDiffuse.dds

[ResourceFreminetHeadLightMap]
filename = FreminetHeadLightMap.dds

[ResourceFreminetBodyNormalMap]
filename = FreminetBodyNormalMap.dds

[ResourceFreminetBodyDiffuse]
filename = FreminetBodyDiffuse.dds

[ResourceFreminetBodyLightMap]
filename = FreminetBodyLightMap.dds

[ResourceFreminetFaceHeadDiffuse]
filename = FreminetFaceHeadDiffuse.dds


; the identity mod of Freminet: the game's own model out of its download folder (GI/Freminet/6_8), built by AGIDMGen
