; Candace

; Constants -------------------------

; Overrides -------------------------

[TextureOverrideCandacePosition]
hash = 9cee8711
vb0 = ResourceCandacePosition

[TextureOverrideCandaceBlend]
hash = e5fd4e8a
vb1 = ResourceCandaceBlend
handling = skip
draw = 16369,0

[TextureOverrideCandaceTexcoord]
hash = 729f8219
vb1 = ResourceCandaceTexcoord

[TextureOverrideCandaceVertexLimitRaise]
hash = 593cbad4

[TextureOverrideCandaceIB]
hash = a84cc930
handling = skip
drawindexed = auto

[TextureOverrideCandaceHead]
hash = a84cc930
match_first_index = 0
ib = ResourceCandaceHeadIB
ps-t0 = ResourceCandaceHeadNormalMap
ps-t1 = ResourceCandaceHeadDiffuse
ps-t2 = ResourceCandaceHeadLightMap
run = CommandList\global\ORFix\ORFix

[TextureOverrideCandaceBody]
hash = a84cc930
match_first_index = 32682
ib = ResourceCandaceBodyIB
ps-t0 = ResourceCandaceBodyNormalMap
ps-t1 = ResourceCandaceBodyDiffuse
ps-t2 = ResourceCandaceBodyLightMap
run = CommandList\global\ORFix\ORFix

[TextureOverrideCandaceDress]
hash = a84cc930
match_first_index = 58719
ib = ResourceCandaceDressIB
ps-t0 = ResourceCandaceDressNormalMap
ps-t1 = ResourceCandaceDressDiffuse
ps-t2 = ResourceCandaceDressLightMap
run = CommandList\global\ORFix\ORFix

[TextureOverrideCandaceFaceHeadDiffuse]
hash = 01eb6d46
ps-t0 = ResourceCandaceFaceHeadDiffuse


; CommandList -----------------------

; Resources -------------------------

[ResourceCandacePosition]
type = Buffer
stride = 40
filename = CandacePosition.buf

[ResourceCandaceBlend]
type = Buffer
stride = 32
filename = CandaceBlend.buf

[ResourceCandaceTexcoord]
type = Buffer
stride = 20
filename = CandaceTexcoord.buf

[ResourceCandaceHeadIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = CandaceHead.ib

[ResourceCandaceBodyIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = CandaceBody.ib

[ResourceCandaceDressIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = CandaceDress.ib

[ResourceCandaceHeadNormalMap]
filename = CandaceHeadNormalMap.dds

[ResourceCandaceHeadDiffuse]
filename = CandaceHeadDiffuse.dds

[ResourceCandaceHeadLightMap]
filename = CandaceHeadLightMap.dds

[ResourceCandaceBodyNormalMap]
filename = CandaceBodyNormalMap.dds

[ResourceCandaceBodyDiffuse]
filename = CandaceBodyDiffuse.dds

[ResourceCandaceBodyLightMap]
filename = CandaceBodyLightMap.dds

[ResourceCandaceDressNormalMap]
filename = CandaceDressNormalMap.dds

[ResourceCandaceDressDiffuse]
filename = CandaceDressDiffuse.dds

[ResourceCandaceDressLightMap]
filename = CandaceDressLightMap.dds

[ResourceCandaceFaceHeadDiffuse]
filename = CandaceFaceHeadDiffuse.dds


; the identity mod of Candace: the game's own model out of its download folder (tmpn7gs33kx), built by AGIDMGen
