; CharlotteHurlock

; Constants -------------------------

; Overrides -------------------------

[TextureOverrideCharlotteHurlockBangsPosition]
hash = 53d723bf
vb0 = ResourceCharlotteHurlockBangsPosition

[TextureOverrideCharlotteHurlockBangsBlend]
hash = 88e539c7
vb1 = ResourceCharlotteHurlockBangsBlend
handling = skip
draw = 1840,0

[TextureOverrideCharlotteHurlockBangsTexcoord]
hash = 78468110
vb1 = ResourceCharlotteHurlockBangsTexcoord

[TextureOverrideCharlotteHurlockBangsVertexLimitRaise]
hash = 270e0ffd

[TextureOverrideCharlotteHurlockBangsIB]
hash = 60af405e
handling = skip
drawindexed = auto

[TextureOverrideCharlotteHurlockBangsA]
hash = 60af405e
match_first_index = 0
ib = ResourceCharlotteHurlockBangsAIB
ps-t0 = ResourceCharlotteHurlockBodyANormalMap
ps-t1 = ResourceCharlotteHurlockBodyADiffuse
ps-t2 = ResourceCharlotteHurlockBodyALightMap
run = CommandList\global\ORFix\ORFix

[TextureOverrideCharlotteHurlockBodyPosition]
hash = e35ce2c4
vb0 = ResourceCharlotteHurlockBodyPosition

[TextureOverrideCharlotteHurlockBodyBlend]
hash = d3a63a25
vb1 = ResourceCharlotteHurlockBodyBlend
handling = skip
draw = 30214,0

[TextureOverrideCharlotteHurlockBodyTexcoord]
hash = 637e74a3
vb1 = ResourceCharlotteHurlockBodyTexcoord

[TextureOverrideCharlotteHurlockBodyVertexLimitRaise]
hash = f45bbdaf

[TextureOverrideCharlotteHurlockBodyIB]
hash = 5d42c20a
handling = skip
drawindexed = auto

[TextureOverrideCharlotteHurlockBodyA]
hash = 5d42c20a
match_first_index = 0
ib = ResourceCharlotteHurlockBodyAIB
ps-t0 = ResourceCharlotteHurlockBodyANormalMap
ps-t1 = ResourceCharlotteHurlockBodyADiffuse
ps-t2 = ResourceCharlotteHurlockBodyALightMap
run = CommandList\global\ORFix\ORFix

[TextureOverrideCharlotteHurlockBodyB]
hash = 5d42c20a
match_first_index = 53529
ib = ResourceCharlotteHurlockBodyBIB
ps-t0 = ResourceCharlotteHurlockBodyBNormalMap
ps-t1 = ResourceCharlotteHurlockBodyBDiffuse
ps-t2 = ResourceCharlotteHurlockBodyBLightMap
run = CommandList\global\ORFix\ORFix

[TextureOverrideCharlotteHurlockBodyC]
hash = 5d42c20a
match_first_index = 99756
ib = ResourceCharlotteHurlockBodyCIB
ps-t0 = ResourceCharlotteHurlockBodyBDiffuse
ps-t1 = ResourceCharlotteHurlockBodyBLightMap
run = CommandList\global\ORFix\NNFix

[TextureOverrideCharlotteHurlockBodyD]
hash = 5d42c20a
match_first_index = 103914
ib = ResourceCharlotteHurlockBodyDIB
ps-t0 = ResourceCharlotteHurlockBodyANormalMap
ps-t1 = ResourceCharlotteHurlockBodyADiffuse
ps-t2 = ResourceCharlotteHurlockBodyALightMap
run = CommandList\global\ORFix\ORFix

[TextureOverrideCharlotteHurlockBodyE]
hash = 5d42c20a
match_first_index = 104172
ib = ResourceCharlotteHurlockBodyEIB

[TextureOverrideCharlotteHurlockCameraPosition]
hash = 1ec056e4
vb0 = ResourceCharlotteHurlockCameraPosition

[TextureOverrideCharlotteHurlockCameraBlend]
hash = c1923b49
vb1 = ResourceCharlotteHurlockCameraBlend
handling = skip
draw = 1435,0

[TextureOverrideCharlotteHurlockCameraTexcoord]
hash = 18514e5e
vb1 = ResourceCharlotteHurlockCameraTexcoord

[TextureOverrideCharlotteHurlockCameraVertexLimitRaise]
hash = 127d2fe8

[TextureOverrideCharlotteHurlockCameraIB]
hash = f7f00837
handling = skip
drawindexed = auto

[TextureOverrideCharlotteHurlockCameraA]
hash = f7f00837
match_first_index = 0
ib = ResourceCharlotteHurlockCameraAIB

[TextureOverrideCharlotteHurlockEyesPosition]
hash = c813722b
vb0 = ResourceCharlotteHurlockEyesPosition

[TextureOverrideCharlotteHurlockEyesBlend]
hash = bd6d3bcd
vb1 = ResourceCharlotteHurlockEyesBlend
handling = skip
draw = 120,0

[TextureOverrideCharlotteHurlockEyesTexcoord]
hash = c37b323a
vb1 = ResourceCharlotteHurlockEyesTexcoord

[TextureOverrideCharlotteHurlockEyesVertexLimitRaise]
hash = 61b441bd

[TextureOverrideCharlotteHurlockEyesIB]
hash = a64cdb3d
handling = skip
drawindexed = auto

[TextureOverrideCharlotteHurlockEyesA]
hash = a64cdb3d
match_first_index = 0
ib = ResourceCharlotteHurlockEyesAIB
ps-t0 = ResourceCharlotteHurlockBodyBDiffuse
ps-t1 = ResourceCharlotteHurlockBodyBLightMap
run = CommandList\global\ORFix\NNFix

[TextureOverrideCharlotteHurlockFaceHeadDiffuse]
hash = 58d9859b
ps-t0 = ResourceCharlotteHurlockFaceHeadDiffuse


; CommandList -----------------------

; Resources -------------------------

[ResourceCharlotteHurlockBangsPosition]
type = Buffer
stride = 40
filename = CharlotteHurlockBangsPosition.buf

[ResourceCharlotteHurlockBangsBlend]
type = Buffer
stride = 32
filename = CharlotteHurlockBangsBlend.buf

[ResourceCharlotteHurlockBangsTexcoord]
type = Buffer
stride = 12
filename = CharlotteHurlockBangsTexcoord.buf

[ResourceCharlotteHurlockBodyPosition]
type = Buffer
stride = 40
filename = CharlotteHurlockBodyPosition.buf

[ResourceCharlotteHurlockBodyBlend]
type = Buffer
stride = 32
filename = CharlotteHurlockBodyBlend.buf

[ResourceCharlotteHurlockBodyTexcoord]
type = Buffer
stride = 20
filename = CharlotteHurlockBodyTexcoord.buf

[ResourceCharlotteHurlockCameraPosition]
type = Buffer
stride = 40
filename = CharlotteHurlockCameraPosition.buf

[ResourceCharlotteHurlockCameraBlend]
type = Buffer
stride = 32
filename = CharlotteHurlockCameraBlend.buf

[ResourceCharlotteHurlockCameraTexcoord]
type = Buffer
stride = 20
filename = CharlotteHurlockCameraTexcoord.buf

[ResourceCharlotteHurlockEyesPosition]
type = Buffer
stride = 40
filename = CharlotteHurlockEyesPosition.buf

[ResourceCharlotteHurlockEyesBlend]
type = Buffer
stride = 32
filename = CharlotteHurlockEyesBlend.buf

[ResourceCharlotteHurlockEyesTexcoord]
type = Buffer
stride = 12
filename = CharlotteHurlockEyesTexcoord.buf

[ResourceCharlotteHurlockBangsAIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = CharlotteHurlockBangsA.ib

[ResourceCharlotteHurlockBodyAIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = CharlotteHurlockBodyA.ib

[ResourceCharlotteHurlockBodyBIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = CharlotteHurlockBodyB.ib

[ResourceCharlotteHurlockBodyCIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = CharlotteHurlockBodyC.ib

[ResourceCharlotteHurlockBodyDIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = CharlotteHurlockBodyD.ib

[ResourceCharlotteHurlockBodyEIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = CharlotteHurlockBodyE.ib

[ResourceCharlotteHurlockCameraAIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = CharlotteHurlockCameraA.ib

[ResourceCharlotteHurlockEyesAIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = CharlotteHurlockEyesA.ib

[ResourceCharlotteHurlockBodyADiffuse]
filename = CharlotteHurlockBodyADiffuse.dds

[ResourceCharlotteHurlockBodyALightMap]
filename = CharlotteHurlockBodyALightMap.dds

[ResourceCharlotteHurlockBodyANormalMap]
filename = CharlotteHurlockBodyANormalMap.dds

[ResourceCharlotteHurlockBodyBDiffuse]
filename = CharlotteHurlockBodyBDiffuse.dds

[ResourceCharlotteHurlockBodyBLightMap]
filename = CharlotteHurlockBodyBLightMap.dds

[ResourceCharlotteHurlockBodyBNormalMap]
filename = CharlotteHurlockBodyBNormalMap.dds

[ResourceCharlotteHurlockFaceHeadDiffuse]
filename = CharlotteHurlockFaceHeadDiffuse.dds


; the identity mod of CharlotteHurlock: the game's own model out of its download folder (GI/CharlotteHurlock/6_7), built by AGIDMGen
