; Nicole

; Constants -------------------------

; Overrides -------------------------

[TextureOverrideNicoleBangsPosition]
hash = 91d035b7
vb0 = ResourceNicoleBangsPosition

[TextureOverrideNicoleBangsBlend]
hash = 27a56b4a
vb1 = ResourceNicoleBangsBlend
handling = skip
draw = 3054,0

[TextureOverrideNicoleBangsTexcoord]
hash = f9e9a87d
vb1 = ResourceNicoleBangsTexcoord

[TextureOverrideNicoleBangsVertexLimitRaise]
hash = 445ee11a

[TextureOverrideNicoleBangsIB]
hash = 34111581
handling = skip
drawindexed = auto

[TextureOverrideNicoleBangsA]
hash = 34111581
match_first_index = 0
ib = ResourceNicoleBangsAIB
ps-t0 = ResourceNicoleBangsANormalMap
ps-t1 = ResourceNicoleBangsADiffuse
ps-t2 = ResourceNicoleBangsALightMap
run = CommandList\global\ORFix\ORFix

[TextureOverrideNicoleEyesPosition]
hash = 62762793
vb0 = ResourceNicoleEyesPosition

[TextureOverrideNicoleEyesBlend]
hash = 3a96677f
vb1 = ResourceNicoleEyesBlend
handling = skip
draw = 400,0

[TextureOverrideNicoleEyesTexcoord]
hash = aebdf0cb
vb1 = ResourceNicoleEyesTexcoord

[TextureOverrideNicoleEyesVertexLimitRaise]
hash = 87bc97df

[TextureOverrideNicoleEyesIB]
hash = 610d42a2
handling = skip
drawindexed = auto

[TextureOverrideNicoleEyesA]
hash = 610d42a2
match_first_index = 0
ib = ResourceNicoleEyesAIB
ps-t0 = ResourceNicoleEyesADiffuse
ps-t1 = ResourceNicoleEyesALightMap
run = CommandList\global\ORFix\NNFix

[TextureOverrideNicoleBodyPosition]
hash = b4ea829d
vb0 = ResourceNicoleBodyPosition

[TextureOverrideNicoleBodyBlend]
hash = afc461e8
vb1 = ResourceNicoleBodyBlend
handling = skip
draw = 26221,0

[TextureOverrideNicoleBodyTexcoord]
hash = c4fd584b
vb1 = ResourceNicoleBodyTexcoord

[TextureOverrideNicoleBodyVertexLimitRaise]
hash = 8fc7e980

[TextureOverrideNicoleBodyIB]
hash = 9c998b05
handling = skip
drawindexed = auto

[TextureOverrideNicoleBodyA]
hash = 9c998b05
match_first_index = 0
ib = ResourceNicoleBodyAIB
ps-t0 = ResourceNicoleBodyANormalMap
ps-t1 = ResourceNicoleBodyADiffuse
ps-t2 = ResourceNicoleBodyALightMap
run = CommandList\global\ORFix\ORFix

[TextureOverrideNicoleBodyB]
hash = 9c998b05
match_first_index = 22074
ib = ResourceNicoleBodyBIB
ps-t0 = ResourceNicoleBodyBNormalMap
ps-t1 = ResourceNicoleBodyBDiffuse
ps-t2 = ResourceNicoleBodyBLightMap
run = CommandList\global\ORFix\ORFix

[TextureOverrideNicoleBodyC]
hash = 9c998b05
match_first_index = 48978
ib = ResourceNicoleBodyCIB
ps-t0 = ResourceNicoleBodyCDiffuse
ps-t1 = ResourceNicoleBodyCLightMap
run = CommandList\global\ORFix\NNFix

[TextureOverrideNicoleBodyD]
hash = 9c998b05
match_first_index = 53148
ib = ResourceNicoleBodyDIB
ps-t0 = ResourceNicoleBodyDNormalMap
ps-t1 = ResourceNicoleBodyDDiffuse
ps-t2 = ResourceNicoleBodyDLightMap
run = CommandList\global\ORFix\ORFix

[TextureOverrideNicoleHatPosition]
hash = 2378c951
vb0 = ResourceNicoleHatPosition

[TextureOverrideNicoleHatBlend]
hash = 47ca2e48
vb1 = ResourceNicoleHatBlend
handling = skip
draw = 1251,0

[TextureOverrideNicoleHatTexcoord]
hash = 2f65feba
vb1 = ResourceNicoleHatTexcoord

[TextureOverrideNicoleHatVertexLimitRaise]
hash = 18094500

[TextureOverrideNicoleHatIB]
hash = dbdd589f
handling = skip
drawindexed = auto

[TextureOverrideNicoleHatA]
hash = dbdd589f
match_first_index = 0
ib = ResourceNicoleHatAIB
ps-t0 = ResourceNicoleHatANormalMap
ps-t1 = ResourceNicoleHatADiffuse
ps-t2 = ResourceNicoleHatALightMap
run = CommandList\global\ORFix\ORFix

[TextureOverrideNicoleHatB]
hash = dbdd589f
match_first_index = 2214
ib = ResourceNicoleHatBIB
ps-t0 = ResourceNicoleHatBNormalMap
ps-t1 = ResourceNicoleHatBDiffuse
ps-t2 = ResourceNicoleHatBLightMap
run = CommandList\global\ORFix\ORFix

[TextureOverrideNicoleChestPiecePosition]
hash = b18ea0e5
vb0 = ResourceNicoleChestPiecePosition

[TextureOverrideNicoleChestPieceBlend]
hash = 8981b4c5
vb1 = ResourceNicoleChestPieceBlend
handling = skip
draw = 1101,0

[TextureOverrideNicoleChestPieceTexcoord]
hash = f73c8217
vb1 = ResourceNicoleChestPieceTexcoord

[TextureOverrideNicoleChestPieceVertexLimitRaise]
hash = fc6182fb

[TextureOverrideNicoleChestPieceIB]
hash = b7fd8da9
handling = skip
drawindexed = auto

[TextureOverrideNicoleChestPieceA]
hash = b7fd8da9
match_first_index = 0
ib = ResourceNicoleChestPieceAIB
ps-t0 = ResourceNicoleChestPieceANormalMap
ps-t1 = ResourceNicoleChestPieceADiffuse
ps-t2 = ResourceNicoleChestPieceALightMap
run = CommandList\global\ORFix\ORFix

[TextureOverrideNicoleChestPieceB]
hash = b7fd8da9
match_first_index = 432
ib = ResourceNicoleChestPieceBIB
ps-t0 = ResourceNicoleChestPieceBNormalMap
ps-t1 = ResourceNicoleChestPieceBDiffuse
ps-t2 = ResourceNicoleChestPieceBLightMap
run = CommandList\global\ORFix\ORFix

[TextureOverrideNicoleFaceHeadDiffuse]
hash = 2c2698af
ps-t0 = ResourceNicoleFaceHeadDiffuse


; CommandList -----------------------

; Resources -------------------------

[ResourceNicoleBangsPosition]
type = Buffer
stride = 40
filename = NicoleBangsPosition.buf

[ResourceNicoleBangsBlend]
type = Buffer
stride = 32
filename = NicoleBangsBlend.buf

[ResourceNicoleBangsTexcoord]
type = Buffer
stride = 12
filename = NicoleBangsTexcoord.buf

[ResourceNicoleEyesPosition]
type = Buffer
stride = 40
filename = NicoleEyesPosition.buf

[ResourceNicoleEyesBlend]
type = Buffer
stride = 32
filename = NicoleEyesBlend.buf

[ResourceNicoleEyesTexcoord]
type = Buffer
stride = 12
filename = NicoleEyesTexcoord.buf

[ResourceNicoleBodyPosition]
type = Buffer
stride = 40
filename = NicoleBodyPosition.buf

[ResourceNicoleBodyBlend]
type = Buffer
stride = 32
filename = NicoleBodyBlend.buf

[ResourceNicoleBodyTexcoord]
type = Buffer
stride = 28
filename = NicoleBodyTexcoord.buf

[ResourceNicoleHatPosition]
type = Buffer
stride = 40
filename = NicoleHatPosition.buf

[ResourceNicoleHatBlend]
type = Buffer
stride = 32
filename = NicoleHatBlend.buf

[ResourceNicoleHatTexcoord]
type = Buffer
stride = 12
filename = NicoleHatTexcoord.buf

[ResourceNicoleChestPiecePosition]
type = Buffer
stride = 40
filename = NicoleChestPiecePosition.buf

[ResourceNicoleChestPieceBlend]
type = Buffer
stride = 32
filename = NicoleChestPieceBlend.buf

[ResourceNicoleChestPieceTexcoord]
type = Buffer
stride = 20
filename = NicoleChestPieceTexcoord.buf

[ResourceNicoleBangsAIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = NicoleBangsA.ib

[ResourceNicoleEyesAIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = NicoleEyesA.ib

[ResourceNicoleBodyAIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = NicoleBodyA.ib

[ResourceNicoleBodyBIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = NicoleBodyB.ib

[ResourceNicoleBodyCIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = NicoleBodyC.ib

[ResourceNicoleBodyDIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = NicoleBodyD.ib

[ResourceNicoleHatAIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = NicoleHatA.ib

[ResourceNicoleHatBIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = NicoleHatB.ib

[ResourceNicoleChestPieceAIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = NicoleChestPieceA.ib

[ResourceNicoleChestPieceBIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = NicoleChestPieceB.ib

[ResourceNicoleBangsALightMap]
filename = NicoleBangsALightMap.dds

[ResourceNicoleBangsANormalMap]
filename = NicoleBangsANormalMap.dds

[ResourceNicoleBangsADiffuse]
filename = NicoleBangsADiffuse.dds

[ResourceNicoleEyesALightMap]
filename = NicoleEyesALightMap.dds

[ResourceNicoleEyesADiffuse]
filename = NicoleEyesADiffuse.dds

[ResourceNicoleBodyALightMap]
filename = NicoleBodyALightMap.dds

[ResourceNicoleBodyANormalMap]
filename = NicoleBodyANormalMap.dds

[ResourceNicoleBodyADiffuse]
filename = NicoleBodyADiffuse.dds

[ResourceNicoleBodyBLightMap]
filename = NicoleBodyBLightMap.dds

[ResourceNicoleBodyBNormalMap]
filename = NicoleBodyBNormalMap.dds

[ResourceNicoleBodyBDiffuse]
filename = NicoleBodyBDiffuse.dds

[ResourceNicoleBodyCLightMap]
filename = NicoleBodyCLightMap.dds

[ResourceNicoleBodyCDiffuse]
filename = NicoleBodyCDiffuse.dds

[ResourceNicoleBodyDLightMap]
filename = NicoleBodyDLightMap.dds

[ResourceNicoleBodyDNormalMap]
filename = NicoleBodyDNormalMap.dds

[ResourceNicoleBodyDDiffuse]
filename = NicoleBodyDDiffuse.dds

[ResourceNicoleHatALightMap]
filename = NicoleHatALightMap.dds

[ResourceNicoleHatANormalMap]
filename = NicoleHatANormalMap.dds

[ResourceNicoleHatADiffuse]
filename = NicoleHatADiffuse.dds

[ResourceNicoleHatBLightMap]
filename = NicoleHatBLightMap.dds

[ResourceNicoleHatBNormalMap]
filename = NicoleHatBNormalMap.dds

[ResourceNicoleHatBDiffuse]
filename = NicoleHatBDiffuse.dds

[ResourceNicoleChestPieceALightMap]
filename = NicoleChestPieceALightMap.dds

[ResourceNicoleChestPieceANormalMap]
filename = NicoleChestPieceANormalMap.dds

[ResourceNicoleChestPieceADiffuse]
filename = NicoleChestPieceADiffuse.dds

[ResourceNicoleChestPieceBLightMap]
filename = NicoleChestPieceBLightMap.dds

[ResourceNicoleChestPieceBNormalMap]
filename = NicoleChestPieceBNormalMap.dds

[ResourceNicoleChestPieceBDiffuse]
filename = NicoleChestPieceBDiffuse.dds

[ResourceNicoleFaceHeadDiffuse]
filename = NicoleFaceADiffuse.dds


; the identity mod of Nicole: the game's own model out of its download folder (tmpvfznsai1), built by AGIDMGen
