; KaedeharaKazuha

; Constants -------------------------

; Overrides -------------------------

[TextureOverrideKaedeharaKazuhaPosition]
hash = 7c0c47b3
vb0 = ResourceKaedeharaKazuhaPosition

[TextureOverrideKaedeharaKazuhaBlend]
hash = 28a1fab0
vb1 = ResourceKaedeharaKazuhaBlend
handling = skip
draw = 12189,0

[TextureOverrideKaedeharaKazuhaTexcoord]
hash = 5f7534b6
vb1 = ResourceKaedeharaKazuhaTexcoord

[TextureOverrideKaedeharaKazuhaVertexLimitRaise]
hash = 58b0e678

[TextureOverrideKaedeharaKazuhaIB]
hash = 356cdbde
handling = skip
drawindexed = auto

[TextureOverrideKaedeharaKazuhaHead]
hash = 356cdbde
match_first_index = 0
ib = ResourceKaedeharaKazuhaHeadIB
ps-t0 = ResourceKaedeharaKazuhaHeadDiffuse
ps-t1 = ResourceKaedeharaKazuhaHeadLightMap
run = CommandList\global\ORFix\NNFix

[TextureOverrideKaedeharaKazuhaBody]
hash = 356cdbde
match_first_index = 7923
ib = ResourceKaedeharaKazuhaBodyIB
ps-t0 = ResourceKaedeharaKazuhaBodyDiffuse
ps-t1 = ResourceKaedeharaKazuhaBodyLightMap
run = CommandList\global\ORFix\NNFix

[TextureOverrideKaedeharaKazuhaDress]
hash = 356cdbde
match_first_index = 47775
ib = ResourceKaedeharaKazuhaDressIB
ps-t0 = ResourceKaedeharaKazuhaDressDiffuse
ps-t1 = ResourceKaedeharaKazuhaDressLightMap
run = CommandList\global\ORFix\NNFix

[TextureOverrideKaedeharaKazuhaFaceHeadDiffuse]
hash = 986b4815
ps-t0 = ResourceKaedeharaKazuhaFaceHeadDiffuse


; CommandList -----------------------

; Resources -------------------------

[ResourceKaedeharaKazuhaPosition]
type = Buffer
stride = 40
filename = KaedeharaKazuhaPosition.buf

[ResourceKaedeharaKazuhaBlend]
type = Buffer
stride = 32
filename = KaedeharaKazuhaBlend.buf

[ResourceKaedeharaKazuhaTexcoord]
type = Buffer
stride = 20
filename = KaedeharaKazuhaTexcoord.buf

[ResourceKaedeharaKazuhaHeadIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = KaedeharaKazuhaHead.ib

[ResourceKaedeharaKazuhaBodyIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = KaedeharaKazuhaBody.ib

[ResourceKaedeharaKazuhaDressIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = KaedeharaKazuhaDress.ib

[ResourceKaedeharaKazuhaHeadDiffuse]
filename = KaedeharaKazuhaHeadDiffuse.dds

[ResourceKaedeharaKazuhaHeadLightMap]
filename = KaedeharaKazuhaHeadLightMap.dds

[ResourceKaedeharaKazuhaBodyDiffuse]
filename = KaedeharaKazuhaBodyDiffuse.dds

[ResourceKaedeharaKazuhaBodyLightMap]
filename = KaedeharaKazuhaBodyLightMap.dds

[ResourceKaedeharaKazuhaDressDiffuse]
filename = KaedeharaKazuhaDressDiffuse.dds

[ResourceKaedeharaKazuhaDressLightMap]
filename = KaedeharaKazuhaDressLightMap.dds

[ResourceKaedeharaKazuhaFaceHeadDiffuse]
filename = KaedeharaKazuhaFaceHeadDiffuse.dds


; the identity mod of KaedeharaKazuha: the game's own model out of its download folder (GI/KaedeharaKazuha/6_8), built by AGIDMGen
