; BarbaraSummertime

; Constants -------------------------

; Overrides -------------------------

[TextureOverrideBarbaraSummertimePosition]
hash = 8b9e7c22
vb0 = ResourceBarbaraSummertimePosition

[TextureOverrideBarbaraSummertimeBlend]
hash = 639d62b6
vb1 = ResourceBarbaraSummertimeBlend
handling = skip
draw = 13580,0

[TextureOverrideBarbaraSummertimeTexcoord]
hash = 27057f58
vb1 = ResourceBarbaraSummertimeTexcoord

[TextureOverrideBarbaraSummertimeVertexLimitRaise]
hash = e9199599

[TextureOverrideBarbaraSummertimeIB]
hash = 9cc5a563
handling = skip
drawindexed = auto

[TextureOverrideBarbaraSummertimeHead]
hash = 9cc5a563
match_first_index = 0
ib = ResourceBarbaraSummertimeHeadIB
ps-t0 = ResourceBarbaraSummertimeHeadDiffuse
ps-t1 = ResourceBarbaraSummertimeHeadLightMap
run = CommandList\global\ORFix\NNFix

[TextureOverrideBarbaraSummertimeBody]
hash = 9cc5a563
match_first_index = 11943
ib = ResourceBarbaraSummertimeBodyIB
ps-t0 = ResourceBarbaraSummertimeBodyDiffuse
ps-t1 = ResourceBarbaraSummertimeBodyLightMap
run = CommandList\global\ORFix\NNFix

[TextureOverrideBarbaraSummertimeDress]
hash = 9cc5a563
match_first_index = 45333
ib = ResourceBarbaraSummertimeDressIB
ps-t0 = ResourceBarbaraSummertimeDressDiffuse
ps-t1 = ResourceBarbaraSummertimeDressLightMap
run = CommandList\global\ORFix\NNFix

[TextureOverrideBarbaraSummertimeFaceHeadDiffuse]
hash = 72a0dee8
ps-t0 = ResourceBarbaraSummertimeFaceHeadDiffuse


; CommandList -----------------------

; Resources -------------------------

[ResourceBarbaraSummertimePosition]
type = Buffer
stride = 40
filename = BarbaraSummertimePosition.buf

[ResourceBarbaraSummertimeBlend]
type = Buffer
stride = 32
filename = BarbaraSummertimeBlend.buf

[ResourceBarbaraSummertimeTexcoord]
type = Buffer
stride = 20
filename = BarbaraSummertimeTexcoord.buf

[ResourceBarbaraSummertimeHeadIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = BarbaraSummertimeHead.ib

[ResourceBarbaraSummertimeBodyIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = BarbaraSummertimeBody.ib

[ResourceBarbaraSummertimeDressIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = BarbaraSummertimeDress.ib

[ResourceBarbaraSummertimeHeadDiffuse]
filename = BarbaraSummertimeHeadDiffuse.dds

[ResourceBarbaraSummertimeHeadLightMap]
filename = BarbaraSummertimeHeadLightMap.dds

[ResourceBarbaraSummertimeBodyDiffuse]
filename = BarbaraSummertimeBodyDiffuse.dds

[ResourceBarbaraSummertimeBodyLightMap]
filename = BarbaraSummertimeBodyLightMap.dds

[ResourceBarbaraSummertimeDressDiffuse]
filename = BarbaraSummertimeDressDiffuse.dds

[ResourceBarbaraSummertimeDressLightMap]
filename = BarbaraSummertimeDressLightMap.dds

[ResourceBarbaraSummertimeFaceHeadDiffuse]
filename = BarbaraSummertimeFaceHeadDiffuse.dds


; the identity mod of BarbaraSummertime: the game's own model out of its download folder (GI/BarbaraSummertime/4_0), built by AGIDMGen
