; WWMI BETA-2 INI

; Mod State -------------------------

[Constants]
global $required_wwmi_version = 0.91
global $object_guid = 253182
global $mesh_vertex_count = 59675
global $shapekey_vertex_count = 39390
global $mod_id = -1000
global $state_id = 0
global $mod_enabled = 0
global $object_detected = 0

[Present]
if $object_detected
    if $mod_enabled
        post $object_detected = 0
        run = CommandListInitializeBlendRemaps
        run = CommandListUpdateMergedSkeleton
    else
        if $mod_id == -1000
            run = CommandListRegisterMod
        endif
    endif
endif

[CommandListRegisterMod]
$\WWMIv1\required_wwmi_version = $required_wwmi_version
$\WWMIv1\object_guid = $object_guid
Resource\WWMIv1\ModName = ref ResourceModName
Resource\WWMIv1\ModAuthor = ref ResourceModAuthor
Resource\WWMIv1\ModDesc = ref ResourceModDesc
Resource\WWMIv1\ModLink = ref ResourceModLink
Resource\WWMIv1\ModLogo = ref ResourceModLogo
run = CommandList\WWMIv1\RegisterMod
$mod_id = $\WWMIv1\mod_id
if $mod_id >= 0
    $mod_enabled = 1
endif

[CommandListUpdateMergedSkeleton]
if $state_id
    $state_id = 0
else
    $state_id = 1
endif
ResourceMergedSkeleton = copy ResourceMergedSkeletonRW
ResourceExtraMergedSkeleton = copy ResourceExtraMergedSkeletonRW
run = CommandListRemapMergedSkeleton

[ResourceMergedSkeletonRemap]
[ResourceExtraMergedSkeletonRemap]

[ResourceBlendBufferOverride]
[ResourceExtraMergedSkeletonOverride]
[ResourceMergedSkeletonOverride]

[ResourceRemappedBlendBufferRW]
[ResourceRemappedSkeletonRW]
[ResourceExtraRemappedSkeletonRW]

[ResourceRemappedBlendBufferComponent7]
[ResourceRemappedSkeletonComponent7]
[ResourceExtraRemappedSkeletonComponent7]

[CommandListInitializeBlendRemaps]
local $blend_remaps_initialized
if !$blend_remaps_initialized
    ResourceRemappedSkeletonRW = copy ResourceMergedSkeletonRW
    ResourceExtraRemappedSkeletonRW = copy ResourceExtraMergedSkeletonRW
    $\WWMIv1\custom_vertex_count = $mesh_vertex_count
    $\WWMIv1\weights_per_vertex_count = 4
    cs-t34 = ref ResourceBlendRemapReverseBuffer
    cs-t35 = ref ResourceBlendRemapVertexVGBuffer
    $\WWMIv1\blend_remap_id = 0
    ResourceRemappedBlendBufferRW = copy ResourceBlendBufferNoStride
    cs-u4 = ref ResourceRemappedBlendBufferRW
    run = CustomShader\WWMIv1\BlendRemapper
    ResourceRemappedBlendBufferComponent7 = copy ResourceRemappedBlendBufferRW
    ResourceRemappedBlendBufferComponent7 = copy_desc ResourceBlendBuffer
    $blend_remaps_initialized = 1
endif

[CommandListRemapMergedSkeleton]
ResourceMergedSkeletonRemap = copy ResourceMergedSkeletonRW
ResourceExtraMergedSkeletonRemap = copy ResourceExtraMergedSkeletonRW
cs-t37 = ResourceBlendRemapForwardBuffer
$\WWMIv1\blend_remap_id = 0
$\WWMIv1\vg_count = 55
cs-t38 = ResourceMergedSkeletonRemap
cs-u5 = ResourceRemappedSkeletonRW
run = CustomShader\WWMIv1\SkeletonRemapper
ResourceRemappedSkeletonComponent7 = copy ResourceRemappedSkeletonRW
cs-t38 = ResourceExtraMergedSkeletonRemap
cs-u5 = ResourceExtraRemappedSkeletonRW
run = CustomShader\WWMIv1\SkeletonRemapper
ResourceExtraRemappedSkeletonComponent7 = copy ResourceExtraRemappedSkeletonRW

; Resources: Mod Info -------------------------

[ResourceModName]
type = Buffer
data = "Shorekeeper Identity"

[ResourceModAuthor]
type = Buffer
data = "Anime Game Remap"

[ResourceModDesc]
type = Buffer
data = "The identity mod of Shorekeeper: the game's own model out of WWMI-Assets, built by AGIDMGen"

[ResourceModLink]
; type = Buffer
; data = "Empty Mod Link"

[ResourceModLogo]
; filename = Textures/Logo.dds

; Shading: Draw Call Stacks Processing -------------------------

[TextureOverrideMarkBoneDataCB]
hash = f02baf77
match_priority = 0
filter_index = 3381.7777

[CommandListMergeSkeleton]
$\WWMIv1\custom_mesh_scale = 1.00
cs-cb8 = ref vs-cb4
cs-u6 = ResourceMergedSkeletonRW
run = CustomShader\WWMIv1\SkeletonMerger
cs-cb8 = ref vs-cb3
cs-u6 = ResourceExtraMergedSkeletonRW
run = CustomShader\WWMIv1\SkeletonMerger

[CommandListTriggerResourceOverrides]
CheckTextureOverride = ps-t0
CheckTextureOverride = ps-t1
CheckTextureOverride = ps-t2
CheckTextureOverride = ps-t3
CheckTextureOverride = ps-t4
CheckTextureOverride = ps-t5
CheckTextureOverride = ps-t6
CheckTextureOverride = ps-t7
CheckTextureOverride = vs-cb3
CheckTextureOverride = vs-cb4

[CommandListOverrideSharedResources]
ResourceBypassVB0 = ref vb0
ib = ResourceIndexBuffer
vb0 = ResourcePositionBuffer
vb1 = ResourceVectorBuffer
vb2 = ResourceTexcoordBuffer
vb3 = ResourceColorBuffer
if ResourceBlendBufferOverride === null
    vb4 = ResourceBlendBuffer
    if vs-cb3 == 3381.7777
        vs-cb3 = ref ResourceExtraMergedSkeleton
    endif
    if vs-cb4 == 3381.7777
        vs-cb4 = ref ResourceMergedSkeleton
    endif
else
    vb4 = ref ResourceBlendBufferOverride
    if vs-cb3 == 3381.7777
        vs-cb3 = ref ResourceExtraMergedSkeletonOverride
    endif
    if vs-cb4 == 3381.7777
        vs-cb4 = ref ResourceMergedSkeletonOverride
    endif
endif

[CommandListCleanupSharedResources]
vb0 = ref ResourceBypassVB0
if ResourceBlendBufferOverride !== null
    ResourceBlendBufferOverride = null
    ResourceMergedSkeletonOverride = null
    ResourceExtraMergedSkeletonOverride = null
endif

[TextureOverrideComponent0]
hash = 0266ab77
match_first_index = 0
match_index_count = 12846
$object_detected = 1
if $mod_enabled
    local $state_id_0
    if $state_id_0 != $state_id
        $state_id_0 = $state_id
        $\WWMIv1\vg_offset = 0
        $\WWMIv1\vg_count = 24
        run = CommandListMergeSkeleton
    endif
    if ResourceMergedSkeleton !== null
        handling = skip
        run = CommandListTriggerResourceOverrides
        run = CommandListOverrideSharedResources
        ; Draw Component 0
        drawindexed = 12846, 0, 0
        run = CommandListCleanupSharedResources
    endif
endif

[TextureOverrideComponent1]
hash = 0266ab77
match_first_index = 12846
match_index_count = 18207
$object_detected = 1
if $mod_enabled
    local $state_id_1
    if $state_id_1 != $state_id
        $state_id_1 = $state_id
        $\WWMIv1\vg_offset = 24
        $\WWMIv1\vg_count = 16
        run = CommandListMergeSkeleton
    endif
    if ResourceMergedSkeleton !== null
        handling = skip
        run = CommandListTriggerResourceOverrides
        run = CommandListOverrideSharedResources
        ; Draw Component 1
        drawindexed = 18207, 12846, 0
        run = CommandListCleanupSharedResources
    endif
endif

[TextureOverrideComponent2]
hash = 0266ab77
match_first_index = 31053
match_index_count = 13392
$object_detected = 1
if $mod_enabled
    local $state_id_2
    if $state_id_2 != $state_id
        $state_id_2 = $state_id
        $\WWMIv1\vg_offset = 40
        $\WWMIv1\vg_count = 1
        run = CommandListMergeSkeleton
    endif
    if ResourceMergedSkeleton !== null
        handling = skip
        run = CommandListTriggerResourceOverrides
        run = CommandListOverrideSharedResources
        ; Draw Component 2
        drawindexed = 13392, 31053, 0
        run = CommandListCleanupSharedResources
    endif
endif

[TextureOverrideComponent3]
hash = 0266ab77
match_first_index = 44445
match_index_count = 33537
$object_detected = 1
if $mod_enabled
    local $state_id_3
    if $state_id_3 != $state_id
        $state_id_3 = $state_id
        $\WWMIv1\vg_offset = 41
        $\WWMIv1\vg_count = 51
        run = CommandListMergeSkeleton
    endif
    if ResourceMergedSkeleton !== null
        handling = skip
        run = CommandListTriggerResourceOverrides
        run = CommandListOverrideSharedResources
        ; Draw Component 3
        drawindexed = 33537, 44445, 0
        run = CommandListCleanupSharedResources
    endif
endif

[TextureOverrideComponent4]
hash = 0266ab77
match_first_index = 77982
match_index_count = 102810
$object_detected = 1
if $mod_enabled
    local $state_id_4
    if $state_id_4 != $state_id
        $state_id_4 = $state_id
        $\WWMIv1\vg_offset = 92
        $\WWMIv1\vg_count = 100
        run = CommandListMergeSkeleton
    endif
    if ResourceMergedSkeleton !== null
        handling = skip
        run = CommandListTriggerResourceOverrides
        run = CommandListOverrideSharedResources
        ; Draw Component 4
        drawindexed = 102810, 77982, 0
        run = CommandListCleanupSharedResources
    endif
endif

[TextureOverrideComponent5]
hash = 0266ab77
match_first_index = 180792
match_index_count = 34452
$object_detected = 1
if $mod_enabled
    local $state_id_5
    if $state_id_5 != $state_id
        $state_id_5 = $state_id
        $\WWMIv1\vg_offset = 192
        $\WWMIv1\vg_count = 46
        run = CommandListMergeSkeleton
    endif
    if ResourceMergedSkeleton !== null
        handling = skip
        run = CommandListTriggerResourceOverrides
        run = CommandListOverrideSharedResources
        ; Draw Component 5
        drawindexed = 34452, 180792, 0
        run = CommandListCleanupSharedResources
    endif
endif

[TextureOverrideComponent6]
hash = 0266ab77
match_first_index = 215244
match_index_count = 1686
$object_detected = 1
if $mod_enabled
    local $state_id_6
    if $state_id_6 != $state_id
        $state_id_6 = $state_id
        $\WWMIv1\vg_offset = 238
        $\WWMIv1\vg_count = 1
        run = CommandListMergeSkeleton
    endif
    if ResourceMergedSkeleton !== null
        handling = skip
        run = CommandListTriggerResourceOverrides
        run = CommandListOverrideSharedResources
        ; Draw Component 6
        drawindexed = 1686, 215244, 0
        run = CommandListCleanupSharedResources
    endif
endif

[TextureOverrideComponent7]
hash = 0266ab77
match_first_index = 216930
match_index_count = 36252
$object_detected = 1
if $mod_enabled
    local $state_id_7
    if $state_id_7 != $state_id
        $state_id_7 = $state_id
        $\WWMIv1\vg_offset = 239
        $\WWMIv1\vg_count = 55
        run = CommandListMergeSkeleton
    endif
    if ResourceMergedSkeleton !== null
        handling = skip
        ResourceBlendBufferOverride = ref ResourceRemappedBlendBufferComponent7
        ResourceMergedSkeletonOverride = ref ResourceRemappedSkeletonComponent7
        ResourceExtraMergedSkeletonOverride = ref ResourceExtraRemappedSkeletonComponent7
        run = CommandListTriggerResourceOverrides
        run = CommandListOverrideSharedResources
        ; Draw Component 7
        drawindexed = 36252, 216930, 0
        run = CommandListCleanupSharedResources
    endif
endif

; Shading: Textures -------------------------

[ResourceTexture0]
filename = Textures/ShorekeeperTexture03284c19.dds

[TextureOverrideTexture0]
hash = 03284c19
match_priority = 0
if $object_detected
    this = ResourceTexture0
endif

[ResourceTexture1]
filename = Textures/ShorekeeperTexture13baf2f6.dds

[TextureOverrideTexture1]
hash = 13baf2f6
match_priority = 0
if $object_detected
    this = ResourceTexture1
endif

[ResourceTexture2]
filename = Textures/ShorekeeperTexture1cd5eb92.dds

[TextureOverrideTexture2]
hash = 1cd5eb92
match_priority = 0
if $object_detected
    this = ResourceTexture2
endif

[ResourceTexture3]
filename = Textures/ShorekeeperTexture2293ef8e.dds

[TextureOverrideTexture3]
hash = 2293ef8e
match_priority = 0
if $object_detected
    this = ResourceTexture3
endif

[ResourceTexture4]
filename = Textures/ShorekeeperTexture2b933cc9.dds

[TextureOverrideTexture4]
hash = 2b933cc9
match_priority = 0
if $object_detected
    this = ResourceTexture4
endif

[ResourceTexture5]
filename = Textures/ShorekeeperTexture41b0d744.dds

[TextureOverrideTexture5]
hash = 41b0d744
match_priority = 0
if $object_detected
    this = ResourceTexture5
endif

[ResourceTexture6]
filename = Textures/ShorekeeperTexture41bd7de9.dds

[TextureOverrideTexture6]
hash = 41bd7de9
match_priority = 0
if $object_detected
    this = ResourceTexture6
endif

[ResourceTexture7]
filename = Textures/ShorekeeperTexture4b0e4779.dds

[TextureOverrideTexture7]
hash = 4b0e4779
match_priority = 0
if $object_detected
    this = ResourceTexture7
endif

[ResourceTexture8]
filename = Textures/ShorekeeperTexture529645a1.dds

[TextureOverrideTexture8]
hash = 529645a1
match_priority = 0
if $object_detected
    this = ResourceTexture8
endif

[ResourceTexture9]
filename = Textures/ShorekeeperTexture5aa61d2f.dds

[TextureOverrideTexture9]
hash = 5aa61d2f
match_priority = 0
if $object_detected
    this = ResourceTexture9
endif

[ResourceTexture10]
filename = Textures/ShorekeeperTexture6e3d31e6.dds

[TextureOverrideTexture10]
hash = 6e3d31e6
match_priority = 0
if $object_detected
    this = ResourceTexture10
endif

[ResourceTexture11]
filename = Textures/ShorekeeperTexture83141b71.dds

[TextureOverrideTexture11]
hash = 83141b71
match_priority = 0
if $object_detected
    this = ResourceTexture11
endif

[ResourceTexture12]
filename = Textures/ShorekeeperTexture8383cbbf.dds

[TextureOverrideTexture12]
hash = 8383cbbf
match_priority = 0
if $object_detected
    this = ResourceTexture12
endif

[ResourceTexture13]
filename = Textures/ShorekeeperTexture87e93853.dds

[TextureOverrideTexture13]
hash = 87e93853
match_priority = 0
if $object_detected
    this = ResourceTexture13
endif

[ResourceTexture14]
filename = Textures/ShorekeeperTexture8e19fa21.dds

[TextureOverrideTexture14]
hash = 8e19fa21
match_priority = 0
if $object_detected
    this = ResourceTexture14
endif

[ResourceTexture15]
filename = Textures/ShorekeeperTexturea7c9acc3.dds

[TextureOverrideTexture15]
hash = a7c9acc3
match_priority = 0
if $object_detected
    this = ResourceTexture15
endif

[ResourceTexture16]
filename = Textures/ShorekeeperTexturea8ef808e.dds

[TextureOverrideTexture16]
hash = a8ef808e
match_priority = 0
if $object_detected
    this = ResourceTexture16
endif

[ResourceTexture17]
filename = Textures/ShorekeeperTextureb9136153.dds

[TextureOverrideTexture17]
hash = b9136153
match_priority = 0
if $object_detected
    this = ResourceTexture17
endif

[ResourceTexture18]
filename = Textures/ShorekeeperTexturec148034c.dds

[TextureOverrideTexture18]
hash = c148034c
match_priority = 0
if $object_detected
    this = ResourceTexture18
endif

[ResourceTexture19]
filename = Textures/ShorekeeperTextured2f2fe3e.dds

[TextureOverrideTexture19]
hash = d2f2fe3e
match_priority = 0
if $object_detected
    this = ResourceTexture19
endif

[ResourceTexture20]
filename = Textures/ShorekeeperTextureec2a6255.dds

[TextureOverrideTexture20]
hash = ec2a6255
match_priority = 0
if $object_detected
    this = ResourceTexture20
endif

[ResourceTexture21]
filename = Textures/ShorekeeperTexturefb389390.dds

[TextureOverrideTexture21]
hash = fb389390
match_priority = 0
if $object_detected
    this = ResourceTexture21
endif

; Skinning: Shape Keys Override -------------------------

[TextureOverrideShapeKeyOffsets]
hash = 78fd9b75
match_priority = 0
override_byte_stride = 24
override_vertex_count = $mesh_vertex_count

[TextureOverrideShapeKeyScale]
hash = eecaa360
match_priority = 0
override_byte_stride = 4
override_vertex_count = $mesh_vertex_count

[CommandListSetupShapeKeys]
$\WWMIv1\shapekey_checksum = 3637
cs-t33 = ResourceShapeKeyOffsetBuffer
cs-u5 = ResourceCustomShapeKeyValuesRW
cs-u6 = ResourceShapeKeyCBRW
run = CustomShader\WWMIv1\ShapeKeyOverrider

[CommandListLoadShapeKeys]
$\WWMIv1\shapekey_vertex_count = $shapekey_vertex_count
cs-t0 = ResourceShapeKeyVertexIdBuffer
cs-t1 = ResourceShapeKeyVertexOffsetBuffer
cs-u6 = ResourceShapeKeyCBRW
run = CustomShader\WWMIv1\ShapeKeyLoader

[TextureOverrideShapeKeyLoaderCallback]
hash = 78fd9b75
match_priority = 0
if $mod_enabled
    if cs == 3381.3333 && ResourceMergedSkeleton !== null
        handling = skip
        run = CommandListSetupShapeKeys
        run = CommandListLoadShapeKeys
    endif
endif

[CommandListMultiplyShapeKeys]
$\WWMIv1\custom_vertex_count = $mesh_vertex_count
run = CustomShader\WWMIv1\ShapeKeyMultiplier

[TextureOverrideShapeKeyMultiplierCallback]
hash = 78fd9b75
match_priority = 0
if $mod_enabled
    if cs == 3381.4444 && ResourceMergedSkeleton !== null
        handling = skip
        run = CommandListMultiplyShapeKeys
    endif
endif

; Resources: Shape Keys Override -------------------------

[ResourceShapeKeyCBRW]
type = RWBuffer
format = R32G32B32A32_UINT
array = 66

[ResourceCustomShapeKeyValuesRW]
type = RWBuffer
format = R32G32B32A32_FLOAT
array = 32

; Resources: Skeleton Override -------------------------

[ResourceMergedSkeleton]

[ResourceMergedSkeletonRW]
type = RWBuffer
format = R32G32B32A32_FLOAT
array = 1536

[ResourceExtraMergedSkeleton]

[ResourceExtraMergedSkeletonRW]
type = RWBuffer
format = R32G32B32A32_FLOAT
array = 1536

; Resources: Buffers -------------------------

[ResourceBypassVB0]

[ResourceIndexBuffer]
type = Buffer
format = DXGI_FORMAT_R32_UINT
stride = 12
filename = Meshes/Index.buf

[ResourcePositionBuffer]
type = Buffer
format = DXGI_FORMAT_R32G32B32_FLOAT
stride = 12
filename = Meshes/Position.buf

[ResourceBlendBuffer]
type = Buffer
format = DXGI_FORMAT_R8_UINT
stride = 8
filename = Meshes/Blend.buf

[ResourceBlendBufferNoStride]
type = Buffer
format = DXGI_FORMAT_R8_UINT
filename = Meshes/Blend.buf

[ResourceVectorBuffer]
type = Buffer
format = DXGI_FORMAT_R8G8B8A8_SNORM
stride = 8
filename = Meshes/Vector.buf

[ResourceColorBuffer]
type = Buffer
format = DXGI_FORMAT_R8G8B8A8_UNORM
stride = 4
filename = Meshes/Color.buf

[ResourceTexCoordBuffer]
type = Buffer
format = DXGI_FORMAT_R16G16_FLOAT
stride = 16
filename = Meshes/TexCoord.buf

[ResourceShapeKeyOffsetBuffer]
type = Buffer
format = DXGI_FORMAT_R32G32B32A32_UINT
stride = 16
filename = Meshes/ShapeKeyOffset.buf

[ResourceShapeKeyVertexIdBuffer]
type = Buffer
format = DXGI_FORMAT_R32_UINT
stride = 4
filename = Meshes/ShapeKeyVertexId.buf

[ResourceShapeKeyVertexOffsetBuffer]
type = Buffer
format = DXGI_FORMAT_R16_FLOAT
stride = 2
filename = Meshes/ShapeKeyVertexOffset.buf

[ResourceBlendRemapVertexVGBuffer]
type = Buffer
format = DXGI_FORMAT_R16_UINT
filename = Meshes/BlendRemapVertexVG.buf

[ResourceBlendRemapForwardBuffer]
type = Buffer
format = DXGI_FORMAT_R16_UINT
filename = Meshes/BlendRemapForward.buf

[ResourceBlendRemapReverseBuffer]
type = Buffer
format = DXGI_FORMAT_R16_UINT
filename = Meshes/BlendRemapReverse.buf

; Autogenerated -------------------------

; This mod.ini is the IDENTITY mod of Shorekeeper, generated by AGIDMGen (Anime Game Identity Mod Generator) from WWMI-Assets, in the shape WWMI Tools 1.3.4 generates (WWMI v0.9.1+)
