; Illuga

; Constants -------------------------

; Overrides -------------------------

[TextureOverrideIllugaBangsPosition]
hash = 02fe028c
vb0 = ResourceIllugaBangsPosition

[TextureOverrideIllugaBangsBlend]
hash = 87414a8f
vb1 = ResourceIllugaBangsBlend
handling = skip
draw = 1860,0

[TextureOverrideIllugaBangsTexcoord]
hash = 2cc21dbc
vb1 = ResourceIllugaBangsTexcoord

[TextureOverrideIllugaBangsVertexLimitRaise]
hash = e3a1e8f9

[TextureOverrideIllugaBangsIB]
hash = 822bd44a
handling = skip
drawindexed = auto

[TextureOverrideIllugaBangsA]
hash = 822bd44a
match_first_index = 0
ib = ResourceIllugaBangsAIB
ps-t0 = ResourceIllugaBangsANormalMap
ps-t1 = ResourceIllugaBangsADiffuse
ps-t2 = ResourceIllugaBangsALightMap
run = CommandList\global\ORFix\ORFix

[TextureOverrideIllugaEyesPosition]
hash = 71fb94ad
vb0 = ResourceIllugaEyesPosition

[TextureOverrideIllugaEyesBlend]
hash = 867f5b5e
vb1 = ResourceIllugaEyesBlend
handling = skip
draw = 324,0

[TextureOverrideIllugaEyesTexcoord]
hash = c21a763a
vb1 = ResourceIllugaEyesTexcoord

[TextureOverrideIllugaEyesVertexLimitRaise]
hash = fb0e451a

[TextureOverrideIllugaEyesIB]
hash = d8aac551
handling = skip
drawindexed = auto

[TextureOverrideIllugaEyesA]
hash = d8aac551
match_first_index = 0
ib = ResourceIllugaEyesAIB
ps-t0 = ResourceIllugaEyesADiffuse
ps-t1 = ResourceIllugaEyesALightMap
run = CommandList\global\ORFix\NNFix

[TextureOverrideIllugaBodyPosition]
hash = d84bff69
vb0 = ResourceIllugaBodyPosition

[TextureOverrideIllugaBodyBlend]
hash = 20b58753
vb1 = ResourceIllugaBodyBlend
handling = skip
draw = 24387,0

[TextureOverrideIllugaBodyTexcoord]
hash = 8dafefdc
vb1 = ResourceIllugaBodyTexcoord

[TextureOverrideIllugaBodyVertexLimitRaise]
hash = c249ba9d

[TextureOverrideIllugaBodyIB]
hash = 6515939e
handling = skip
drawindexed = auto

[TextureOverrideIllugaBodyA]
hash = 6515939e
match_first_index = 0
ib = ResourceIllugaBodyAIB
ps-t0 = ResourceIllugaBodyANormalMap
ps-t1 = ResourceIllugaBodyADiffuse
ps-t2 = ResourceIllugaBodyALightMap
run = CommandList\global\ORFix\ORFix

[TextureOverrideIllugaBodyB]
hash = 6515939e
match_first_index = 55254
ib = ResourceIllugaBodyBIB
ps-t0 = ResourceIllugaBodyBNormalMap
ps-t1 = ResourceIllugaBodyBDiffuse
ps-t2 = ResourceIllugaBodyBLightMap
run = CommandList\global\ORFix\ORFix

[TextureOverrideIllugaFaceHeadDiffuse]
hash = ee28a05a
ps-t0 = ResourceIllugaFaceHeadDiffuse


; CommandList -----------------------

; Resources -------------------------

[ResourceIllugaBangsPosition]
type = Buffer
stride = 40
filename = IllugaBangsPosition.buf

[ResourceIllugaBangsBlend]
type = Buffer
stride = 32
filename = IllugaBangsBlend.buf

[ResourceIllugaBangsTexcoord]
type = Buffer
stride = 12
filename = IllugaBangsTexcoord.buf

[ResourceIllugaEyesPosition]
type = Buffer
stride = 40
filename = IllugaEyesPosition.buf

[ResourceIllugaEyesBlend]
type = Buffer
stride = 32
filename = IllugaEyesBlend.buf

[ResourceIllugaEyesTexcoord]
type = Buffer
stride = 12
filename = IllugaEyesTexcoord.buf

[ResourceIllugaBodyPosition]
type = Buffer
stride = 40
filename = IllugaBodyPosition.buf

[ResourceIllugaBodyBlend]
type = Buffer
stride = 32
filename = IllugaBodyBlend.buf

[ResourceIllugaBodyTexcoord]
type = Buffer
stride = 12
filename = IllugaBodyTexcoord.buf

[ResourceIllugaBangsAIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = IllugaBangsA.ib

[ResourceIllugaEyesAIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = IllugaEyesA.ib

[ResourceIllugaBodyAIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = IllugaBodyA.ib

[ResourceIllugaBodyBIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = IllugaBodyB.ib

[ResourceIllugaBangsALightMap]
filename = IllugaBangsALightMap.dds

[ResourceIllugaBangsANormalMap]
filename = IllugaBangsANormalMap.dds

[ResourceIllugaBangsADiffuse]
filename = IllugaBangsADiffuse.dds

[ResourceIllugaEyesALightMap]
filename = IllugaEyesALightMap.dds

[ResourceIllugaEyesADiffuse]
filename = IllugaEyesADiffuse.dds

[ResourceIllugaBodyALightMap]
filename = IllugaBodyALightMap.dds

[ResourceIllugaBodyANormalMap]
filename = IllugaBodyANormalMap.dds

[ResourceIllugaBodyADiffuse]
filename = IllugaBodyADiffuse.dds

[ResourceIllugaBodyBLightMap]
filename = IllugaBodyBLightMap.dds

[ResourceIllugaBodyBNormalMap]
filename = IllugaBodyBNormalMap.dds

[ResourceIllugaBodyBDiffuse]
filename = IllugaBodyBDiffuse.dds

[ResourceIllugaFaceHeadDiffuse]
filename = IllugaFaceADiffuse.dds


; the identity mod of Illuga: the game's own model out of its download folder (tmpicrej3og), built by AGIDMGen
