; Lohen

; Constants -------------------------

; Overrides -------------------------

[TextureOverrideLohenBangsPosition]
hash = 3f308422
vb0 = ResourceLohenBangsPosition

[TextureOverrideLohenBangsBlend]
hash = 172d9b83
vb1 = ResourceLohenBangsBlend
handling = skip
draw = 1161,0

[TextureOverrideLohenBangsTexcoord]
hash = 632ca7aa
vb1 = ResourceLohenBangsTexcoord

[TextureOverrideLohenBangsVertexLimitRaise]
hash = 7e6da94e

[TextureOverrideLohenBangsIB]
hash = ab766b0a
handling = skip
drawindexed = auto

[TextureOverrideLohenBangsA]
hash = ab766b0a
match_first_index = 0
ib = ResourceLohenBangsAIB
ps-t0 = ResourceLohenBangsANormalMap
ps-t1 = ResourceLohenBangsADiffuse
ps-t2 = ResourceLohenBangsALightMap
run = CommandList\global\ORFix\ORFix

[TextureOverrideLohenEyesPosition]
hash = e89784de
vb0 = ResourceLohenEyesPosition

[TextureOverrideLohenEyesBlend]
hash = e3cb7f0c
vb1 = ResourceLohenEyesBlend
handling = skip
draw = 356,0

[TextureOverrideLohenEyesTexcoord]
hash = 69483c3b
vb1 = ResourceLohenEyesTexcoord

[TextureOverrideLohenEyesVertexLimitRaise]
hash = 5c7e0333

[TextureOverrideLohenEyesIB]
hash = 9f05d2de
handling = skip
drawindexed = auto

[TextureOverrideLohenEyesA]
hash = 9f05d2de
match_first_index = 0
ib = ResourceLohenEyesAIB
ps-t0 = ResourceLohenEyesADiffuse
ps-t1 = ResourceLohenEyesALightMap
run = CommandList\global\ORFix\NNFix

[TextureOverrideLohenBodyPosition]
hash = 308278b5
vb0 = ResourceLohenBodyPosition

[TextureOverrideLohenBodyBlend]
hash = ac82208a
vb1 = ResourceLohenBodyBlend
handling = skip
draw = 32313,0

[TextureOverrideLohenBodyTexcoord]
hash = e0d00a07
vb1 = ResourceLohenBodyTexcoord

[TextureOverrideLohenBodyVertexLimitRaise]
hash = 74627801

[TextureOverrideLohenBodyIB]
hash = afa69764
handling = skip
drawindexed = auto

[TextureOverrideLohenBodyA]
hash = afa69764
match_first_index = 0
ib = ResourceLohenBodyAIB
ps-t0 = ResourceLohenBodyANormalMap
ps-t1 = ResourceLohenBodyADiffuse
ps-t2 = ResourceLohenBodyALightMap
run = CommandList\global\ORFix\ORFix

[TextureOverrideLohenBodyB]
hash = afa69764
match_first_index = 62394
ib = ResourceLohenBodyBIB
ps-t0 = ResourceLohenBodyBNormalMap
ps-t1 = ResourceLohenBodyBDiffuse
ps-t2 = ResourceLohenBodyBLightMap
run = CommandList\global\ORFix\ORFix

[TextureOverrideLohenBodyC]
hash = afa69764
match_first_index = 101007
ib = ResourceLohenBodyCIB
ps-t0 = ResourceLohenBodyCDiffuse
ps-t1 = ResourceLohenBodyCLightMap
run = CommandList\global\ORFix\NNFix

[TextureOverrideLohenFaceHeadDiffuse]
hash = e25fe968
ps-t0 = ResourceLohenFaceHeadDiffuse


; CommandList -----------------------

; Resources -------------------------

[ResourceLohenBangsPosition]
type = Buffer
stride = 40
filename = LohenBangsPosition.buf

[ResourceLohenBangsBlend]
type = Buffer
stride = 32
filename = LohenBangsBlend.buf

[ResourceLohenBangsTexcoord]
type = Buffer
stride = 12
filename = LohenBangsTexcoord.buf

[ResourceLohenEyesPosition]
type = Buffer
stride = 40
filename = LohenEyesPosition.buf

[ResourceLohenEyesBlend]
type = Buffer
stride = 32
filename = LohenEyesBlend.buf

[ResourceLohenEyesTexcoord]
type = Buffer
stride = 12
filename = LohenEyesTexcoord.buf

[ResourceLohenBodyPosition]
type = Buffer
stride = 40
filename = LohenBodyPosition.buf

[ResourceLohenBodyBlend]
type = Buffer
stride = 32
filename = LohenBodyBlend.buf

[ResourceLohenBodyTexcoord]
type = Buffer
stride = 20
filename = LohenBodyTexcoord.buf

[ResourceLohenBangsAIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = LohenBangsA.ib

[ResourceLohenEyesAIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = LohenEyesA.ib

[ResourceLohenBodyAIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = LohenBodyA.ib

[ResourceLohenBodyBIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = LohenBodyB.ib

[ResourceLohenBodyCIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = LohenBodyC.ib

[ResourceLohenBangsALightMap]
filename = LohenBangsALightMap.dds

[ResourceLohenBangsANormalMap]
filename = LohenBangsANormalMap.dds

[ResourceLohenBangsADiffuse]
filename = LohenBangsADiffuse.dds

[ResourceLohenEyesALightMap]
filename = LohenEyesALightMap.dds

[ResourceLohenEyesADiffuse]
filename = LohenEyesADiffuse.dds

[ResourceLohenBodyALightMap]
filename = LohenBodyALightMap.dds

[ResourceLohenBodyANormalMap]
filename = LohenBodyANormalMap.dds

[ResourceLohenBodyADiffuse]
filename = LohenBodyADiffuse.dds

[ResourceLohenBodyBLightMap]
filename = LohenBodyBLightMap.dds

[ResourceLohenBodyBNormalMap]
filename = LohenBodyBNormalMap.dds

[ResourceLohenBodyBDiffuse]
filename = LohenBodyBDiffuse.dds

[ResourceLohenBodyCLightMap]
filename = LohenBodyCLightMap.dds

[ResourceLohenBodyCDiffuse]
filename = LohenBodyCDiffuse.dds

[ResourceLohenFaceHeadDiffuse]
filename = LohenFaceADiffuse.dds


; the identity mod of Lohen: the game's own model out of its download folder (GI/Lohen/6_8), built by AGIDMGen
