; Rosaria

; Constants -------------------------

; Overrides -------------------------

[TextureOverrideRosariaPosition]
hash = 748f40a5
vb0 = ResourceRosariaPosition

[TextureOverrideRosariaBlend]
hash = 4de959bd
vb1 = ResourceRosariaBlend
handling = skip
draw = 12515,0

[TextureOverrideRosariaTexcoord]
hash = 06b8fbf5
vb1 = ResourceRosariaTexcoord

[TextureOverrideRosariaVertexLimitRaise]
hash = 17fd47fe

[TextureOverrideRosariaIB]
hash = 65ccd309
handling = skip
drawindexed = auto

[TextureOverrideRosariaHead]
hash = 65ccd309
match_first_index = 0
ib = ResourceRosariaHeadIB
ps-t0 = ResourceRosariaHeadDiffuse
ps-t1 = ResourceRosariaHeadLightMap
run = CommandList\global\ORFix\NNFix

[TextureOverrideRosariaBody]
hash = 65ccd309
match_first_index = 11139
ib = ResourceRosariaBodyIB
ps-t0 = ResourceRosariaBodyDiffuse
ps-t1 = ResourceRosariaBodyLightMap
run = CommandList\global\ORFix\NNFix

[TextureOverrideRosariaDress]
hash = 65ccd309
match_first_index = 44088
ib = ResourceRosariaDressIB
ps-t0 = ResourceRosariaDressDiffuse
ps-t1 = ResourceRosariaDressLightMap
run = CommandList\global\ORFix\NNFix

[TextureOverrideRosariaExtra]
hash = 65ccd309
match_first_index = 45990
ib = ResourceRosariaExtraIB
ps-t0 = ResourceRosariaExtraDiffuse
ps-t1 = ResourceRosariaExtraLightMap
run = CommandList\global\ORFix\NNFix

[TextureOverrideRosariaFaceHeadDiffuse]
hash = 2abd61ee
ps-t0 = ResourceRosariaFaceHeadDiffuse


; CommandList -----------------------

; Resources -------------------------

[ResourceRosariaPosition]
type = Buffer
stride = 40
filename = RosariaPosition.buf

[ResourceRosariaBlend]
type = Buffer
stride = 32
filename = RosariaBlend.buf

[ResourceRosariaTexcoord]
type = Buffer
stride = 20
filename = RosariaTexcoord.buf

[ResourceRosariaHeadIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = RosariaHead.ib

[ResourceRosariaBodyIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = RosariaBody.ib

[ResourceRosariaDressIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = RosariaDress.ib

[ResourceRosariaExtraIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = RosariaExtra.ib

[ResourceRosariaHeadDiffuse]
filename = RosariaHeadDiffuse.dds

[ResourceRosariaHeadLightMap]
filename = RosariaHeadLightMap.dds

[ResourceRosariaBodyDiffuse]
filename = RosariaBodyDiffuse.dds

[ResourceRosariaBodyLightMap]
filename = RosariaBodyLightMap.dds

[ResourceRosariaDressDiffuse]
filename = RosariaDressDiffuse.dds

[ResourceRosariaDressLightMap]
filename = RosariaDressLightMap.dds

[ResourceRosariaExtraDiffuse]
filename = RosariaExtraDiffuse.dds

[ResourceRosariaExtraLightMap]
filename = RosariaExtraLightMap.dds

[ResourceRosariaFaceHeadDiffuse]
filename = RosariaFaceHeadDiffuse.dds


; the identity mod of Rosaria: the game's own model out of its download folder (tmpauoz_y9g), built by AGIDMGen
