; YaeMiko

; Constants -------------------------

; Overrides -------------------------

[TextureOverrideYaeMikoPosition]
hash = 3a7f71f5
vb0 = ResourceYaeMikoPosition

[TextureOverrideYaeMikoBlend]
hash = d9ee433a
vb1 = ResourceYaeMikoBlend
handling = skip
draw = 18840,0

[TextureOverrideYaeMikoTexcoord]
hash = 4aebeee0
vb1 = ResourceYaeMikoTexcoord

[TextureOverrideYaeMikoVertexLimitRaise]
hash = f7574bda

[TextureOverrideYaeMikoIB]
hash = 5d09aa00
handling = skip
drawindexed = auto

[TextureOverrideYaeMikoHead]
hash = 5d09aa00
match_first_index = 0
ib = ResourceYaeMikoHeadIB
ps-t0 = ResourceYaeMikoHeadDiffuse
ps-t1 = ResourceYaeMikoHeadLightMap
run = CommandList\global\ORFix\NNFix

[TextureOverrideYaeMikoBody]
hash = 5d09aa00
match_first_index = 19968
ib = ResourceYaeMikoBodyIB
ps-t0 = ResourceYaeMikoBodyDiffuse
ps-t1 = ResourceYaeMikoBodyLightMap
run = CommandList\global\ORFix\NNFix

[TextureOverrideYaeMikoDress]
hash = 5d09aa00
match_first_index = 62868
ib = ResourceYaeMikoDressIB
ps-t0 = ResourceYaeMikoDressDiffuse
ps-t1 = ResourceYaeMikoDressLightMap
run = CommandList\global\ORFix\NNFix

[TextureOverrideYaeMikoFaceHeadDiffuse]
hash = 267091ab
ps-t0 = ResourceYaeMikoFaceHeadDiffuse


; CommandList -----------------------

; Resources -------------------------

[ResourceYaeMikoPosition]
type = Buffer
stride = 40
filename = YaeMikoPosition.buf

[ResourceYaeMikoBlend]
type = Buffer
stride = 32
filename = YaeMikoBlend.buf

[ResourceYaeMikoTexcoord]
type = Buffer
stride = 20
filename = YaeMikoTexcoord.buf

[ResourceYaeMikoHeadIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = YaeMikoHead.ib

[ResourceYaeMikoBodyIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = YaeMikoBody.ib

[ResourceYaeMikoDressIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = YaeMikoDress.ib

[ResourceYaeMikoHeadDiffuse]
filename = YaeMikoHeadDiffuse.dds

[ResourceYaeMikoHeadLightMap]
filename = YaeMikoHeadLightMap.dds

[ResourceYaeMikoBodyDiffuse]
filename = YaeMikoBodyDiffuse.dds

[ResourceYaeMikoBodyLightMap]
filename = YaeMikoBodyLightMap.dds

[ResourceYaeMikoDressDiffuse]
filename = YaeMikoDressDiffuse.dds

[ResourceYaeMikoDressLightMap]
filename = YaeMikoDressLightMap.dds

[ResourceYaeMikoFaceHeadDiffuse]
filename = YaeMikoFaceHeadDiffuse.dds


; the identity mod of YaeMiko: the game's own model out of its download folder (tmpykrgi9yy), built by AGIDMGen
