; LumineHeaven

; Constants -------------------------

; Overrides -------------------------

[TextureOverrideLumineHeavenPosition]
hash = f44024e8
vb0 = ResourceLumineHeavenPosition

[TextureOverrideLumineHeavenBlend]
hash = 9d21697f
vb1 = ResourceLumineHeavenBlend
handling = skip
draw = 31179,0

[TextureOverrideLumineHeavenTexcoord]
hash = 3c73d0f8
vb1 = ResourceLumineHeavenTexcoord

[TextureOverrideLumineHeavenVertexLimitRaise]
hash = e3050e5d

[TextureOverrideLumineHeavenIB]
hash = 9634fc3d
handling = skip
drawindexed = auto

[TextureOverrideLumineHeavenHead]
hash = 9634fc3d
match_first_index = 0
ib = ResourceLumineHeavenHeadIB
ps-t0 = ResourceLumineHeavenHeadNormalMap
ps-t1 = ResourceLumineHeavenHeadDiffuse
ps-t2 = ResourceLumineHeavenHeadLightMap
run = CommandList\global\ORFix\ORFix

[TextureOverrideLumineHeavenBody]
hash = 9634fc3d
match_first_index = 57141
ib = ResourceLumineHeavenBodyIB
ps-t0 = ResourceLumineHeavenBodyNormalMap
ps-t1 = ResourceLumineHeavenBodyDiffuse
ps-t2 = ResourceLumineHeavenBodyLightMap
run = CommandList\global\ORFix\ORFix

[TextureOverrideLumineHeavenBangPosition]
hash = c04f6a33
vb0 = ResourceLumineHeavenBangPosition

[TextureOverrideLumineHeavenBangBlend]
hash = d64f34de
vb1 = ResourceLumineHeavenBangBlend
handling = skip
draw = 2740,0

[TextureOverrideLumineHeavenBangTexcoord]
hash = eb066bfa
vb1 = ResourceLumineHeavenBangTexcoord

[TextureOverrideLumineHeavenBangVertexLimitRaise]
hash = 6eedab0d

[TextureOverrideLumineHeavenBangIB]
hash = e4e2950f
handling = skip
drawindexed = auto

[TextureOverrideLumineHeavenBangA]
hash = e4e2950f
match_first_index = 0
ib = ResourceLumineHeavenBangAIB
ps-t0 = ResourceLumineHeavenHeadNormalMap
ps-t1 = ResourceLumineHeavenHeadDiffuse
ps-t2 = ResourceLumineHeavenHeadLightMap
run = CommandList\global\ORFix\ORFix

[TextureOverrideLumineHeavenEyePosition]
hash = f02928e4
vb0 = ResourceLumineHeavenEyePosition

[TextureOverrideLumineHeavenEyeBlend]
hash = 55f71eef
vb1 = ResourceLumineHeavenEyeBlend
handling = skip
draw = 246,0

[TextureOverrideLumineHeavenEyeTexcoord]
hash = 2f19fb2a
vb1 = ResourceLumineHeavenEyeTexcoord

[TextureOverrideLumineHeavenEyeVertexLimitRaise]
hash = cf21b035

[TextureOverrideLumineHeavenEyeIB]
hash = 36f018fc
handling = skip
drawindexed = auto

[TextureOverrideLumineHeavenEyeA]
hash = 36f018fc
match_first_index = 0
ib = ResourceLumineHeavenEyeAIB
ps-t0 = ResourceLumineHeavenEyeADiffuse
ps-t1 = ResourceLumineHeavenEyeALightMap
run = CommandList\global\ORFix\NNFix

[TextureOverrideLumineHeavenFaceHeadDiffuse]
hash = 1e92b57a
ps-t0 = ResourceLumineHeavenFaceHeadDiffuse


; CommandList -----------------------

; Resources -------------------------

[ResourceLumineHeavenPosition]
type = Buffer
stride = 40
filename = LumineHeavenPosition.buf

[ResourceLumineHeavenBlend]
type = Buffer
stride = 32
filename = LumineHeavenBlend.buf

[ResourceLumineHeavenTexcoord]
type = Buffer
stride = 12
filename = LumineHeavenTexcoord.buf

[ResourceLumineHeavenBangPosition]
type = Buffer
stride = 40
filename = LumineHeavenBangPosition.buf

[ResourceLumineHeavenBangBlend]
type = Buffer
stride = 32
filename = LumineHeavenBangBlend.buf

[ResourceLumineHeavenBangTexcoord]
type = Buffer
stride = 12
filename = LumineHeavenBangTexcoord.buf

[ResourceLumineHeavenEyePosition]
type = Buffer
stride = 40
filename = LumineHeavenEyePosition.buf

[ResourceLumineHeavenEyeBlend]
type = Buffer
stride = 32
filename = LumineHeavenEyeBlend.buf

[ResourceLumineHeavenEyeTexcoord]
type = Buffer
stride = 12
filename = LumineHeavenEyeTexcoord.buf

[ResourceLumineHeavenHeadIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = LumineHeavenHead.ib

[ResourceLumineHeavenBodyIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = LumineHeavenBody.ib

[ResourceLumineHeavenBangAIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = LumineHeavenBangA.ib

[ResourceLumineHeavenEyeAIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = LumineHeavenEyeA.ib

[ResourceLumineHeavenHeadDiffuse]
filename = LumineHeavenHeadDiffuse.dds

[ResourceLumineHeavenHeadLightMap]
filename = LumineHeavenHeadLightMap.dds

[ResourceLumineHeavenHeadNormalMap]
filename = LumineHeavenHeadNormalMap.dds

[ResourceLumineHeavenBodyDiffuse]
filename = LumineHeavenBodyDiffuse.dds

[ResourceLumineHeavenBodyLightMap]
filename = LumineHeavenBodyLightMap.dds

[ResourceLumineHeavenBodyNormalMap]
filename = LumineHeavenBodyNormalMap.dds

[ResourceLumineHeavenEyeADiffuse]
filename = LumineHeavenEyeADiffuse.dds

[ResourceLumineHeavenEyeALightMap]
filename = LumineHeavenEyeALightMap.dds

[ResourceLumineHeavenFaceHeadDiffuse]
filename = LumineHeavenFaceHeadDiffuse.dds


; the identity mod of LumineHeaven: the game's own model out of its download folder (tmp0rms3u1a), built by AGIDMGen
