; KleeBlossomingStarlight

; Constants -------------------------

; Overrides -------------------------

[TextureOverrideKleeBlossomingStarlightPosition]
hash = 0f5fedb4
vb0 = ResourceKleeBlossomingStarlightPosition

[TextureOverrideKleeBlossomingStarlightBlend]
hash = 652497c2
vb1 = ResourceKleeBlossomingStarlightBlend
handling = skip
draw = 24110,0

[TextureOverrideKleeBlossomingStarlightTexcoord]
hash = 4d6c496b
vb1 = ResourceKleeBlossomingStarlightTexcoord

[TextureOverrideKleeBlossomingStarlightVertexLimitRaise]
hash = ebd18105

[TextureOverrideKleeBlossomingStarlightIB]
hash = 4cf8240a
handling = skip
drawindexed = auto

[TextureOverrideKleeBlossomingStarlightHead]
hash = 4cf8240a
match_first_index = 0
ib = ResourceKleeBlossomingStarlightHeadIB
ps-t0 = ResourceKleeBlossomingStarlightHeadDiffuse
ps-t1 = ResourceKleeBlossomingStarlightHeadLightMap
run = CommandList\global\ORFix\NNFix

[TextureOverrideKleeBlossomingStarlightBody]
hash = 4cf8240a
match_first_index = 32553
ib = ResourceKleeBlossomingStarlightBodyIB
ps-t0 = ResourceKleeBlossomingStarlightBodyDiffuse
ps-t1 = ResourceKleeBlossomingStarlightBodyLightMap
run = CommandList\global\ORFix\NNFix

[TextureOverrideKleeBlossomingStarlightDress]
hash = 4cf8240a
match_first_index = 82101
ib = ResourceKleeBlossomingStarlightDressIB
ps-t0 = ResourceKleeBlossomingStarlightDressDiffuse
ps-t1 = ResourceKleeBlossomingStarlightDressLightMap
run = CommandList\global\ORFix\NNFix


; CommandList -----------------------

; Resources -------------------------

[ResourceKleeBlossomingStarlightPosition]
type = Buffer
stride = 40
filename = KleeBlossomingStarlightPosition.buf

[ResourceKleeBlossomingStarlightBlend]
type = Buffer
stride = 32
filename = KleeBlossomingStarlightBlend.buf

[ResourceKleeBlossomingStarlightTexcoord]
type = Buffer
stride = 20
filename = KleeBlossomingStarlightTexcoord.buf

[ResourceKleeBlossomingStarlightHeadIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = KleeBlossomingStarlightHead.ib

[ResourceKleeBlossomingStarlightBodyIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = KleeBlossomingStarlightBody.ib

[ResourceKleeBlossomingStarlightDressIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = KleeBlossomingStarlightDress.ib

[ResourceKleeBlossomingStarlightHeadDiffuse]
filename = KleeBlossomingStarlightHeadDiffuse.dds

[ResourceKleeBlossomingStarlightHeadLightMap]
filename = KleeBlossomingStarlightHeadLightMap.dds

[ResourceKleeBlossomingStarlightBodyDiffuse]
filename = KleeBlossomingStarlightBodyDiffuse.dds

[ResourceKleeBlossomingStarlightBodyLightMap]
filename = KleeBlossomingStarlightBodyLightMap.dds

[ResourceKleeBlossomingStarlightDressDiffuse]
filename = KleeBlossomingStarlightDressDiffuse.dds

[ResourceKleeBlossomingStarlightDressLightMap]
filename = KleeBlossomingStarlightDressLightMap.dds


; the identity mod of KleeBlossomingStarlight: the game's own model out of its download folder (tmpq8yl5hn0), built by AGIDMGen
