; Ningguang

; Constants -------------------------

; Overrides -------------------------

[TextureOverrideNingguangPosition]
hash = f9e1b52b
vb0 = ResourceNingguangPosition

[TextureOverrideNingguangBlend]
hash = 735eaea4
vb1 = ResourceNingguangBlend
handling = skip
draw = 12931,0

[TextureOverrideNingguangTexcoord]
hash = 1f0ab400
vb1 = ResourceNingguangTexcoord

[TextureOverrideNingguangVertexLimitRaise]
hash = 4c2f9a0a

[TextureOverrideNingguangIB]
hash = ad75352c
handling = skip
drawindexed = auto

[TextureOverrideNingguangHead]
hash = ad75352c
match_first_index = 0
ib = ResourceNingguangHeadIB
ps-t0 = ResourceNingguangHeadDiffuse
ps-t1 = ResourceNingguangHeadLightMap
run = CommandList\global\ORFix\NNFix

[TextureOverrideNingguangBody]
hash = ad75352c
match_first_index = 12384
ib = ResourceNingguangBodyIB
ps-t0 = ResourceNingguangBodyDiffuse
ps-t1 = ResourceNingguangBodyLightMap
run = CommandList\global\ORFix\NNFix

[TextureOverrideNingguangDress]
hash = ad75352c
match_first_index = 47157
ib = ResourceNingguangDressIB
ps-t0 = ResourceNingguangDressDiffuse
ps-t1 = ResourceNingguangDressLightMap
run = CommandList\global\ORFix\NNFix

[TextureOverrideNingguangFaceHeadDiffuse]
hash = 4cc85338
ps-t0 = ResourceNingguangFaceHeadDiffuse


; CommandList -----------------------

; Resources -------------------------

[ResourceNingguangPosition]
type = Buffer
stride = 40
filename = NingguangPosition.buf

[ResourceNingguangBlend]
type = Buffer
stride = 32
filename = NingguangBlend.buf

[ResourceNingguangTexcoord]
type = Buffer
stride = 20
filename = NingguangTexcoord.buf

[ResourceNingguangHeadIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = NingguangHead.ib

[ResourceNingguangBodyIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = NingguangBody.ib

[ResourceNingguangDressIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = NingguangDress.ib

[ResourceNingguangHeadDiffuse]
filename = NingguangHeadDiffuse.dds

[ResourceNingguangHeadLightMap]
filename = NingguangHeadLightMap.dds

[ResourceNingguangBodyDiffuse]
filename = NingguangBodyDiffuse.dds

[ResourceNingguangBodyLightMap]
filename = NingguangBodyLightMap.dds

[ResourceNingguangDressDiffuse]
filename = NingguangDressDiffuse.dds

[ResourceNingguangDressLightMap]
filename = NingguangDressLightMap.dds

[ResourceNingguangFaceHeadDiffuse]
filename = NingguangFaceHeadDiffuse.dds


; the identity mod of Ningguang: the game's own model out of its download folder (tmp2o_9nttp), built by AGIDMGen
