; LisaStudent

; Constants -------------------------

; Overrides -------------------------

[TextureOverrideLisaStudentPosition]
hash = 37c70461
vb0 = ResourceLisaStudentPosition

[TextureOverrideLisaStudentBlend]
hash = 5db2f8f4
vb1 = ResourceLisaStudentBlend
handling = skip
draw = 19683,0

[TextureOverrideLisaStudentTexcoord]
hash = d77ffc4f
vb1 = ResourceLisaStudentTexcoord

[TextureOverrideLisaStudentVertexLimitRaise]
hash = bfca9d94

[TextureOverrideLisaStudentIB]
hash = f30eece6
handling = skip
drawindexed = auto

[TextureOverrideLisaStudentHead]
hash = f30eece6
match_first_index = 0
ib = ResourceLisaStudentHeadIB
ps-t0 = ResourceLisaStudentHeadNormalMap
ps-t1 = ResourceLisaStudentHeadDiffuse
ps-t2 = ResourceLisaStudentHeadLightMap
run = CommandList\global\ORFix\ORFix

[TextureOverrideLisaStudentBody]
hash = f30eece6
match_first_index = 29730
ib = ResourceLisaStudentBodyIB
ps-t0 = ResourceLisaStudentBodyNormalMap
ps-t1 = ResourceLisaStudentBodyDiffuse
ps-t2 = ResourceLisaStudentBodyLightMap
run = CommandList\global\ORFix\ORFix

[TextureOverrideLisaStudentFaceHeadDiffuse]
hash = 95cb454c
ps-t0 = ResourceLisaStudentFaceHeadDiffuse


; CommandList -----------------------

; Resources -------------------------

[ResourceLisaStudentPosition]
type = Buffer
stride = 40
filename = LisaStudentPosition.buf

[ResourceLisaStudentBlend]
type = Buffer
stride = 32
filename = LisaStudentBlend.buf

[ResourceLisaStudentTexcoord]
type = Buffer
stride = 20
filename = LisaStudentTexcoord.buf

[ResourceLisaStudentHeadIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = LisaStudentHead.ib

[ResourceLisaStudentBodyIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = LisaStudentBody.ib

[ResourceLisaStudentHeadNormalMap]
filename = LisaStudentHeadNormalMap.dds

[ResourceLisaStudentHeadDiffuse]
filename = LisaStudentHeadDiffuse.dds

[ResourceLisaStudentHeadLightMap]
filename = LisaStudentHeadLightMap.dds

[ResourceLisaStudentBodyNormalMap]
filename = LisaStudentBodyNormalMap.dds

[ResourceLisaStudentBodyDiffuse]
filename = LisaStudentBodyDiffuse.dds

[ResourceLisaStudentBodyLightMap]
filename = LisaStudentBodyLightMap.dds

[ResourceLisaStudentFaceHeadDiffuse]
filename = LisaStudentFaceHeadDiffuse.dds


; the identity mod of LisaStudent: the game's own model out of its download folder (GI/LisaStudent/5_4), built by AGIDMGen
