; Albedo

; Constants -------------------------

; Overrides -------------------------

[TextureOverrideAlbedoPosition]
hash = df65bb00
vb0 = ResourceAlbedoPosition

[TextureOverrideAlbedoBlend]
hash = 3b4159ca
vb1 = ResourceAlbedoBlend
handling = skip
draw = 13377,0

[TextureOverrideAlbedoTexcoord]
hash = 9f6d193b
vb1 = ResourceAlbedoTexcoord

[TextureOverrideAlbedoVertexLimitRaise]
hash = 0ea2c585

[TextureOverrideAlbedoIB]
hash = 0d7dc936
handling = skip
drawindexed = auto

[TextureOverrideAlbedoHead]
hash = 0d7dc936
match_first_index = 0
ib = ResourceAlbedoHeadIB
ps-t0 = ResourceAlbedoHeadDiffuse
ps-t1 = ResourceAlbedoHeadLightMap
run = CommandList\global\ORFix\NNFix

[TextureOverrideAlbedoBody]
hash = 0d7dc936
match_first_index = 9933
ib = ResourceAlbedoBodyIB
ps-t0 = ResourceAlbedoBodyDiffuse
ps-t1 = ResourceAlbedoBodyLightMap
run = CommandList\global\ORFix\NNFix

[TextureOverrideAlbedoDress]
hash = 0d7dc936
match_first_index = 44766
ib = ResourceAlbedoDressIB
ps-t0 = ResourceAlbedoDressDiffuse
ps-t1 = ResourceAlbedoDressLightMap
run = CommandList\global\ORFix\NNFix

[TextureOverrideAlbedoFaceHeadDiffuse]
hash = 4ad12efe
ps-t0 = ResourceAlbedoFaceHeadDiffuse


; CommandList -----------------------

; Resources -------------------------

[ResourceAlbedoPosition]
type = Buffer
stride = 40
filename = AlbedoPosition.buf

[ResourceAlbedoBlend]
type = Buffer
stride = 32
filename = AlbedoBlend.buf

[ResourceAlbedoTexcoord]
type = Buffer
stride = 20
filename = AlbedoTexcoord.buf

[ResourceAlbedoHeadIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = AlbedoHead.ib

[ResourceAlbedoBodyIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = AlbedoBody.ib

[ResourceAlbedoDressIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = AlbedoDress.ib

[ResourceAlbedoHeadDiffuse]
filename = AlbedoHeadDiffuse.dds

[ResourceAlbedoHeadLightMap]
filename = AlbedoHeadLightMap.dds

[ResourceAlbedoBodyDiffuse]
filename = AlbedoBodyDiffuse.dds

[ResourceAlbedoBodyLightMap]
filename = AlbedoBodyLightMap.dds

[ResourceAlbedoDressDiffuse]
filename = AlbedoDressDiffuse.dds

[ResourceAlbedoDressLightMap]
filename = AlbedoDressLightMap.dds

[ResourceAlbedoFaceHeadDiffuse]
filename = AlbedoFaceHeadDiffuse.dds


; the identity mod of Albedo: the game's own model out of its download folder (tmpgv80jstm), built by AGIDMGen
