; WWMI BETA-2 INI

; Mod State -------------------------

[Constants]
global $required_wwmi_version = 0.91
global $object_guid = 114942
global $mesh_vertex_count = 31790
global $shapekey_vertex_count = 35593
global $mod_id = -1000
global $state_id = 0
global $mod_enabled = 0
global $object_detected = 0

[Present]
if $object_detected
    if $mod_enabled
        post $object_detected = 0
        run = CommandListUpdateMergedSkeleton
    else
        if $mod_id == -1000
            run = CommandListRegisterMod
        endif
    endif
endif

[CommandListRegisterMod]
$\WWMIv1\required_wwmi_version = $required_wwmi_version
$\WWMIv1\object_guid = $object_guid
Resource\WWMIv1\ModName = ref ResourceModName
Resource\WWMIv1\ModAuthor = ref ResourceModAuthor
Resource\WWMIv1\ModDesc = ref ResourceModDesc
Resource\WWMIv1\ModLink = ref ResourceModLink
Resource\WWMIv1\ModLogo = ref ResourceModLogo
run = CommandList\WWMIv1\RegisterMod
$mod_id = $\WWMIv1\mod_id
if $mod_id >= 0
    $mod_enabled = 1
endif

[CommandListUpdateMergedSkeleton]
if $state_id
    $state_id = 0
else
    $state_id = 1
endif
ResourceMergedSkeleton = copy ResourceMergedSkeletonRW
ResourceExtraMergedSkeleton = copy ResourceExtraMergedSkeletonRW

; Resources: Mod Info -------------------------

[ResourceModName]
type = Buffer
data = "RoverFemale Identity"

[ResourceModAuthor]
type = Buffer
data = "Anime Game Remap"

[ResourceModDesc]
type = Buffer
data = "The identity mod of RoverFemale: the game's own model out of WWMI-Assets, built by AGIDMGen"

[ResourceModLink]
; type = Buffer
; data = "Empty Mod Link"

[ResourceModLogo]
; filename = Textures/Logo.dds

; Shading: Draw Call Stacks Processing -------------------------

[TextureOverrideMarkBoneDataCB]
hash = f02baf77
match_priority = 0
filter_index = 3381.7777

[CommandListMergeSkeleton]
$\WWMIv1\custom_mesh_scale = 1.00
cs-cb8 = ref vs-cb4
cs-u6 = ResourceMergedSkeletonRW
run = CustomShader\WWMIv1\SkeletonMerger
cs-cb8 = ref vs-cb3
cs-u6 = ResourceExtraMergedSkeletonRW
run = CustomShader\WWMIv1\SkeletonMerger

[CommandListTriggerResourceOverrides]
CheckTextureOverride = ps-t0
CheckTextureOverride = ps-t1
CheckTextureOverride = ps-t2
CheckTextureOverride = ps-t3
CheckTextureOverride = ps-t4
CheckTextureOverride = ps-t5
CheckTextureOverride = ps-t6
CheckTextureOverride = ps-t7
CheckTextureOverride = vs-cb3
CheckTextureOverride = vs-cb4

[CommandListOverrideSharedResources]
ResourceBypassVB0 = ref vb0
ib = ResourceIndexBuffer
vb0 = ResourcePositionBuffer
vb1 = ResourceVectorBuffer
vb2 = ResourceTexcoordBuffer
vb3 = ResourceColorBuffer
vb4 = ResourceBlendBuffer
if vs-cb3 == 3381.7777
    vs-cb3 = ResourceExtraMergedSkeleton
endif
if vs-cb4 == 3381.7777
    vs-cb4 = ResourceMergedSkeleton
endif

[CommandListCleanupSharedResources]
vb0 = ref ResourceBypassVB0

[TextureOverrideComponent0]
hash = 3533a957
match_first_index = 0
match_index_count = 13164
$object_detected = 1
if $mod_enabled
    local $state_id_0
    if $state_id_0 != $state_id
        $state_id_0 = $state_id
        $\WWMIv1\vg_offset = 0
        $\WWMIv1\vg_count = 28
        run = CommandListMergeSkeleton
    endif
    if ResourceMergedSkeleton !== null
        handling = skip
        run = CommandListTriggerResourceOverrides
        run = CommandListOverrideSharedResources
        ; Draw Component 0
        drawindexed = 13164, 0, 0
        run = CommandListCleanupSharedResources
    endif
endif

[TextureOverrideComponent1]
hash = 3533a957
match_first_index = 13164
match_index_count = 17235
$object_detected = 1
if $mod_enabled
    local $state_id_1
    if $state_id_1 != $state_id
        $state_id_1 = $state_id
        $\WWMIv1\vg_offset = 28
        $\WWMIv1\vg_count = 24
        run = CommandListMergeSkeleton
    endif
    if ResourceMergedSkeleton !== null
        handling = skip
        run = CommandListTriggerResourceOverrides
        run = CommandListOverrideSharedResources
        ; Draw Component 1
        drawindexed = 17235, 13164, 0
        run = CommandListCleanupSharedResources
    endif
endif

[TextureOverrideComponent2]
hash = 3533a957
match_first_index = 30399
match_index_count = 10149
$object_detected = 1
if $mod_enabled
    local $state_id_2
    if $state_id_2 != $state_id
        $state_id_2 = $state_id
        $\WWMIv1\vg_offset = 52
        $\WWMIv1\vg_count = 1
        run = CommandListMergeSkeleton
    endif
    if ResourceMergedSkeleton !== null
        handling = skip
        run = CommandListTriggerResourceOverrides
        run = CommandListOverrideSharedResources
        ; Draw Component 2
        drawindexed = 10149, 30399, 0
        run = CommandListCleanupSharedResources
    endif
endif

[TextureOverrideComponent3]
hash = 3533a957
match_first_index = 40548
match_index_count = 43233
$object_detected = 1
if $mod_enabled
    local $state_id_3
    if $state_id_3 != $state_id
        $state_id_3 = $state_id
        $\WWMIv1\vg_offset = 53
        $\WWMIv1\vg_count = 99
        run = CommandListMergeSkeleton
    endif
    if ResourceMergedSkeleton !== null
        handling = skip
        run = CommandListTriggerResourceOverrides
        run = CommandListOverrideSharedResources
        ; Draw Component 3
        drawindexed = 43233, 40548, 0
        run = CommandListCleanupSharedResources
    endif
endif

[TextureOverrideComponent4]
hash = 3533a957
match_first_index = 83781
match_index_count = 29391
$object_detected = 1
if $mod_enabled
    local $state_id_4
    if $state_id_4 != $state_id
        $state_id_4 = $state_id
        $\WWMIv1\vg_offset = 152
        $\WWMIv1\vg_count = 39
        run = CommandListMergeSkeleton
    endif
    if ResourceMergedSkeleton !== null
        handling = skip
        run = CommandListTriggerResourceOverrides
        run = CommandListOverrideSharedResources
        ; Draw Component 4
        drawindexed = 29391, 83781, 0
        run = CommandListCleanupSharedResources
    endif
endif

[TextureOverrideComponent5]
hash = 3533a957
match_first_index = 113172
match_index_count = 1722
$object_detected = 1
if $mod_enabled
    local $state_id_5
    if $state_id_5 != $state_id
        $state_id_5 = $state_id
        $\WWMIv1\vg_offset = 191
        $\WWMIv1\vg_count = 1
        run = CommandListMergeSkeleton
    endif
    if ResourceMergedSkeleton !== null
        handling = skip
        run = CommandListTriggerResourceOverrides
        run = CommandListOverrideSharedResources
        ; Draw Component 5
        drawindexed = 1722, 113172, 0
        run = CommandListCleanupSharedResources
    endif
endif

[TextureOverrideComponent6]
hash = 3533a957
match_first_index = 114894
match_index_count = 48
$object_detected = 1
if $mod_enabled
    local $state_id_6
    if $state_id_6 != $state_id
        $state_id_6 = $state_id
        $\WWMIv1\vg_offset = 192
        $\WWMIv1\vg_count = 3
        run = CommandListMergeSkeleton
    endif
    if ResourceMergedSkeleton !== null
        handling = skip
        run = CommandListTriggerResourceOverrides
        run = CommandListOverrideSharedResources
        ; Draw Component 6
        drawindexed = 48, 114894, 0
        run = CommandListCleanupSharedResources
    endif
endif

; Shading: Textures -------------------------

[ResourceTexture0]
filename = Textures/RoverFemaleTexture04192868.dds

[TextureOverrideTexture0]
hash = 04192868
match_priority = 0
if $object_detected
    this = ResourceTexture0
endif

[ResourceTexture1]
filename = Textures/RoverFemaleTexture071744c8.dds

[TextureOverrideTexture1]
hash = 071744c8
match_priority = 0
if $object_detected
    this = ResourceTexture1
endif

[ResourceTexture2]
filename = Textures/RoverFemaleTexture09ec5d1d.dds

[TextureOverrideTexture2]
hash = 09ec5d1d
match_priority = 0
if $object_detected
    this = ResourceTexture2
endif

[ResourceTexture3]
filename = Textures/RoverFemaleTexture1091025c.dds

[TextureOverrideTexture3]
hash = 1091025c
match_priority = 0
if $object_detected
    this = ResourceTexture3
endif

[ResourceTexture4]
filename = Textures/RoverFemaleTexture1dcc0f1d.dds

[TextureOverrideTexture4]
hash = 1dcc0f1d
match_priority = 0
if $object_detected
    this = ResourceTexture4
endif

[ResourceTexture5]
filename = Textures/RoverFemaleTexture1eafc32c.dds

[TextureOverrideTexture5]
hash = 1eafc32c
match_priority = 0
if $object_detected
    this = ResourceTexture5
endif

[ResourceTexture6]
filename = Textures/RoverFemaleTexture2ff23d4c.dds

[TextureOverrideTexture6]
hash = 2ff23d4c
match_priority = 0
if $object_detected
    this = ResourceTexture6
endif

[ResourceTexture7]
filename = Textures/RoverFemaleTexture3365430a.dds

[TextureOverrideTexture7]
hash = 3365430a
match_priority = 0
if $object_detected
    this = ResourceTexture7
endif

[ResourceTexture8]
filename = Textures/RoverFemaleTexture372bd73a.dds

[TextureOverrideTexture8]
hash = 372bd73a
match_priority = 0
if $object_detected
    this = ResourceTexture8
endif

[ResourceTexture9]
filename = Textures/RoverFemaleTexture52c18227.dds

[TextureOverrideTexture9]
hash = 52c18227
match_priority = 0
if $object_detected
    this = ResourceTexture9
endif

[ResourceTexture10]
filename = Textures/RoverFemaleTexture68a6b802.dds

[TextureOverrideTexture10]
hash = 68a6b802
match_priority = 0
if $object_detected
    this = ResourceTexture10
endif

[ResourceTexture11]
filename = Textures/RoverFemaleTexture747ada83.dds

[TextureOverrideTexture11]
hash = 747ada83
match_priority = 0
if $object_detected
    this = ResourceTexture11
endif

[ResourceTexture12]
filename = Textures/RoverFemaleTexture8383cbbf.dds

[TextureOverrideTexture12]
hash = 8383cbbf
match_priority = 0
if $object_detected
    this = ResourceTexture12
endif

[ResourceTexture13]
filename = Textures/RoverFemaleTexture84025dca.dds

[TextureOverrideTexture13]
hash = 84025dca
match_priority = 0
if $object_detected
    this = ResourceTexture13
endif

[ResourceTexture14]
filename = Textures/RoverFemaleTexture917263d5.dds

[TextureOverrideTexture14]
hash = 917263d5
match_priority = 0
if $object_detected
    this = ResourceTexture14
endif

[ResourceTexture15]
filename = Textures/RoverFemaleTexture946ec36c.dds

[TextureOverrideTexture15]
hash = 946ec36c
match_priority = 0
if $object_detected
    this = ResourceTexture15
endif

[ResourceTexture16]
filename = Textures/RoverFemaleTexturea01c9b96.dds

[TextureOverrideTexture16]
hash = a01c9b96
match_priority = 0
if $object_detected
    this = ResourceTexture16
endif

[ResourceTexture17]
filename = Textures/RoverFemaleTexturea1c0d97c.dds

[TextureOverrideTexture17]
hash = a1c0d97c
match_priority = 0
if $object_detected
    this = ResourceTexture17
endif

[ResourceTexture18]
filename = Textures/RoverFemaleTextureab6288a3.dds

[TextureOverrideTexture18]
hash = ab6288a3
match_priority = 0
if $object_detected
    this = ResourceTexture18
endif

[ResourceTexture19]
filename = Textures/RoverFemaleTexturec79b5772.dds

[TextureOverrideTexture19]
hash = c79b5772
match_priority = 0
if $object_detected
    this = ResourceTexture19
endif

[ResourceTexture20]
filename = Textures/RoverFemaleTexturee02f1a3f.dds

[TextureOverrideTexture20]
hash = e02f1a3f
match_priority = 0
if $object_detected
    this = ResourceTexture20
endif

[ResourceTexture21]
filename = Textures/RoverFemaleTexturef85b1b15.dds

[TextureOverrideTexture21]
hash = f85b1b15
match_priority = 0
if $object_detected
    this = ResourceTexture21
endif

; Skinning: Shape Keys Override -------------------------

[TextureOverrideShapeKeyOffsets]
hash = ac681fc1
match_priority = 0
override_byte_stride = 24
override_vertex_count = $mesh_vertex_count

[TextureOverrideShapeKeyScale]
hash = 972c1750
match_priority = 0
override_byte_stride = 4
override_vertex_count = $mesh_vertex_count

[CommandListSetupShapeKeys]
$\WWMIv1\shapekey_checksum = 1498
cs-t33 = ResourceShapeKeyOffsetBuffer
cs-u5 = ResourceCustomShapeKeyValuesRW
cs-u6 = ResourceShapeKeyCBRW
run = CustomShader\WWMIv1\ShapeKeyOverrider

[CommandListLoadShapeKeys]
$\WWMIv1\shapekey_vertex_count = $shapekey_vertex_count
cs-t0 = ResourceShapeKeyVertexIdBuffer
cs-t1 = ResourceShapeKeyVertexOffsetBuffer
cs-u6 = ResourceShapeKeyCBRW
run = CustomShader\WWMIv1\ShapeKeyLoader

[TextureOverrideShapeKeyLoaderCallback]
hash = ac681fc1
match_priority = 0
if $mod_enabled
    if cs == 3381.3333 && ResourceMergedSkeleton !== null
        handling = skip
        run = CommandListSetupShapeKeys
        run = CommandListLoadShapeKeys
    endif
endif

[CommandListMultiplyShapeKeys]
$\WWMIv1\custom_vertex_count = $mesh_vertex_count
run = CustomShader\WWMIv1\ShapeKeyMultiplier

[TextureOverrideShapeKeyMultiplierCallback]
hash = ac681fc1
match_priority = 0
if $mod_enabled
    if cs == 3381.4444 && ResourceMergedSkeleton !== null
        handling = skip
        run = CommandListMultiplyShapeKeys
    endif
endif

; Resources: Shape Keys Override -------------------------

[ResourceShapeKeyCBRW]
type = RWBuffer
format = R32G32B32A32_UINT
array = 66

[ResourceCustomShapeKeyValuesRW]
type = RWBuffer
format = R32G32B32A32_FLOAT
array = 32

; Resources: Skeleton Override -------------------------

[ResourceMergedSkeleton]

[ResourceMergedSkeletonRW]
type = RWBuffer
format = R32G32B32A32_FLOAT
array = 768

[ResourceExtraMergedSkeleton]

[ResourceExtraMergedSkeletonRW]
type = RWBuffer
format = R32G32B32A32_FLOAT
array = 768

; Resources: Buffers -------------------------

[ResourceBypassVB0]

[ResourceIndexBuffer]
type = Buffer
format = DXGI_FORMAT_R32_UINT
stride = 12
filename = Meshes/Index.buf

[ResourcePositionBuffer]
type = Buffer
format = DXGI_FORMAT_R32G32B32_FLOAT
stride = 12
filename = Meshes/Position.buf

[ResourceBlendBuffer]
type = Buffer
format = DXGI_FORMAT_R8_UINT
stride = 8
filename = Meshes/Blend.buf

[ResourceVectorBuffer]
type = Buffer
format = DXGI_FORMAT_R8G8B8A8_SNORM
stride = 8
filename = Meshes/Vector.buf

[ResourceColorBuffer]
type = Buffer
format = DXGI_FORMAT_R8G8B8A8_UNORM
stride = 4
filename = Meshes/Color.buf

[ResourceTexCoordBuffer]
type = Buffer
format = DXGI_FORMAT_R16G16_FLOAT
stride = 16
filename = Meshes/TexCoord.buf

[ResourceShapeKeyOffsetBuffer]
type = Buffer
format = DXGI_FORMAT_R32G32B32A32_UINT
stride = 16
filename = Meshes/ShapeKeyOffset.buf

[ResourceShapeKeyVertexIdBuffer]
type = Buffer
format = DXGI_FORMAT_R32_UINT
stride = 4
filename = Meshes/ShapeKeyVertexId.buf

[ResourceShapeKeyVertexOffsetBuffer]
type = Buffer
format = DXGI_FORMAT_R16_FLOAT
stride = 2
filename = Meshes/ShapeKeyVertexOffset.buf

; Autogenerated -------------------------

; This mod.ini is the IDENTITY mod of RoverFemale, generated by AGIDMGen (Anime Game Identity Mod Generator) from WWMI-Assets, in the shape WWMI Tools 1.3.4 generates (WWMI v0.9.1+)
