#
# ===== populateMods =====
#
# Fills Mods/ with every character's identity mod, generated from its newest download folder, for users
# who do not want to run the library:
#
#   py -3 Tools/populateMods.py <AGRemap master export's 'Data/Mod Downloads'> [--only gi|wuwa] [--names Name ...]
#
# Each mod is written by IDModGenService into Mods/<GI|WuWa>/<Name>, as `python -m AGIDMGen <loader> --download`
# would, with AG Remap's files read from the export (Tools/Downloads/exportAGRemapDownloads.py) and this
# repo's from Data/Mod Downloads, so nothing is downloaded. Mods/README.md, the list of every mod, is
# rewritten from what is in Mods/. Every file under Mods/ is GENERATED: rerun this tool, never edit them.
#

import argparse
import os
import shutil
import sys

RepoRoot = os.path.abspath(os.path.join(os.path.dirname(os.path.abspath(__file__)), ".."))
sys.path.insert(0, os.path.join(RepoRoot, "AGIDMGen", "api", "src", "py"))
import AGIDMGen as IDMG
import FixRaidenBoss2 as FRB

ModsFolder = os.path.join(RepoRoot, "Mods")
OwnDownloads = os.path.join(RepoRoot, "Data", "Mod Downloads")
Games = {"gi": IDMG.ModLoaders.GIMI, "wuwa": IDMG.ModLoaders.WWMI}

ReadmeHeader = """# Mods

Ready-made **identity mods**: each character's own, unmodified model written out as a mod, generated by
AGIDMGen from the character's newest download folder. Copy a character's folder into your GIMI (GI) or WWMI
(WuWa) `Mods` folder.

Everything here is generated by `Tools/populateMods.py`; do not edit it by hand. The `.dds` / `.buf` / `.ib`
files are stored in [Git LFS](https://git-lfs.com).

"""


def generate(loader, names, agRemap: str):
    game = IDMG.ModDownloadGameFolders[loader]
    outputFolder = os.path.join(ModsFolder, game)
    for name in names:
        folder = os.path.join(outputFolder, name)
        if (os.path.isdir(folder)):
            shutil.rmtree(folder)

    logger = FRB.Logger()
    downloader = IDMG.ModDownloader(localFolders = {IDMG.ModDownloadRepos.AGRemap: agRemap, IDMG.ModDownloadRepos.AGIDMGen: OwnDownloads})
    service = IDMG.IDModGenService(loader, names = names, outputFolder = outputFolder, downloader = downloader, logger = logger)
    service.generate()
    return service.stats


def writeReadme():
    lines = [ReadmeHeader]
    for loader in Games.values():
        game = IDMG.ModDownloadGameFolders[loader]
        folder = os.path.join(ModsFolder, game)
        names = sorted(os.listdir(folder), key = str.lower) if (os.path.isdir(folder)) else []
        lines.append(f"## {game} ({loader.value}): {len(names)} mods\n")
        lines.append("| Character | Game version | From |")
        lines.append("| --- | --- | --- |")
        for name in names:
            download = IDMG.ModDownloader.find(loader, name)
            repos = " + ".join(sorted(set("AG Remap" if repo == IDMG.ModDownloadRepos.AGRemap else "AGIDMGen" for repo in download.files.values())))
            lines.append(f"| [{name}]({game}/{name}) | {download.version.replace('_', '.')} | {repos} |")
        lines.append("")

    with open(os.path.join(ModsFolder, "README.md"), "w", encoding = "utf-8", newline = "\n") as f:
        f.write("\n".join(lines))


def main() -> int:
    parser = argparse.ArgumentParser(description = "fill Mods/ with every character's identity mod")
    parser.add_argument("agRemap", help = "an export of AG Remap's master 'Data/Mod Downloads' (Tools/Downloads/exportAGRemapDownloads.py)")
    parser.add_argument("--only", choices = sorted(Games), default = None, help = "only one game")
    parser.add_argument("--names", nargs = "+", default = None, help = "only these characters")
    args = parser.parse_args()

    failed = []
    for key, loader in Games.items():
        if (args.only is not None and args.only != key):
            continue
        names = args.names if (args.names is not None) else IDMG.ModDownloader.getCharacters(loader)
        stats = generate(loader, names, args.agRemap)
        failed += [f"{loader.value} {name}: {error}" for name, error in stats.skipped.items()]

    writeReadme()
    print(f"\nwrote {os.path.join(ModsFolder, 'README.md')}; failed: {len(failed)}")
    for failure in failed:
        print(f"  {failure}")
    return 1 if (failed) else 0


if (__name__ == "__main__"):
    sys.exit(main())
