; Chevreuse

; Constants -------------------------

; Overrides -------------------------

[TextureOverrideChevreusePosition]
hash = 4d8d965a
vb0 = ResourceChevreusePosition

[TextureOverrideChevreuseBlend]
hash = 8e8fe0e3
vb1 = ResourceChevreuseBlend
handling = skip
draw = 23018,0

[TextureOverrideChevreuseTexcoord]
hash = 350c5b58
vb1 = ResourceChevreuseTexcoord

[TextureOverrideChevreuseVertexLimitRaise]
hash = 02993f26

[TextureOverrideChevreuseIB]
hash = 77208d51
handling = skip
drawindexed = auto

[TextureOverrideChevreuseHead]
hash = 77208d51
match_first_index = 0
ib = ResourceChevreuseHeadIB
ps-t0 = ResourceChevreuseHeadNormalMap
ps-t1 = ResourceChevreuseHeadDiffuse
ps-t2 = ResourceChevreuseHeadLightMap
run = CommandList\global\ORFix\ORFix

[TextureOverrideChevreuseBody]
hash = 77208d51
match_first_index = 45951
ib = ResourceChevreuseBodyIB
ps-t0 = ResourceChevreuseBodyNormalMap
ps-t1 = ResourceChevreuseBodyDiffuse
ps-t2 = ResourceChevreuseBodyLightMap
run = CommandList\global\ORFix\ORFix

[TextureOverrideChevreuseFaceHeadDiffuse]
hash = 04be9db3
ps-t0 = ResourceChevreuseFaceHeadDiffuse


; CommandList -----------------------

; Resources -------------------------

[ResourceChevreusePosition]
type = Buffer
stride = 40
filename = ChevreusePosition.buf

[ResourceChevreuseBlend]
type = Buffer
stride = 32
filename = ChevreuseBlend.buf

[ResourceChevreuseTexcoord]
type = Buffer
stride = 12
filename = ChevreuseTexcoord.buf

[ResourceChevreuseHeadIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = ChevreuseHead.ib

[ResourceChevreuseBodyIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = ChevreuseBody.ib

[ResourceChevreuseHeadNormalMap]
filename = ChevreuseHeadNormalMap.dds

[ResourceChevreuseHeadDiffuse]
filename = ChevreuseHeadDiffuse.dds

[ResourceChevreuseHeadLightMap]
filename = ChevreuseHeadLightMap.dds

[ResourceChevreuseBodyNormalMap]
filename = ChevreuseBodyNormalMap.dds

[ResourceChevreuseBodyDiffuse]
filename = ChevreuseBodyDiffuse.dds

[ResourceChevreuseBodyLightMap]
filename = ChevreuseBodyLightMap.dds

[ResourceChevreuseFaceHeadDiffuse]
filename = ChevreuseFaceHeadDiffuse.dds


; the identity mod of Chevreuse: the game's own model out of its download folder (GI/Chevreuse/6_8), built by AGIDMGen
