; JeanSea

; Constants -------------------------

; Overrides -------------------------

[TextureOverrideJeanSeaPosition]
hash = 16fef1eb
vb0 = ResourceJeanSeaPosition

[TextureOverrideJeanSeaBlend]
hash = ac801371
vb1 = ResourceJeanSeaBlend
handling = skip
draw = 14672,0

[TextureOverrideJeanSeaTexcoord]
hash = 3ffb0363
vb1 = ResourceJeanSeaTexcoord

[TextureOverrideJeanSeaVertexLimitRaise]
hash = 1ec879c9

[TextureOverrideJeanSeaIB]
hash = 69c0c24e
handling = skip
drawindexed = auto

[TextureOverrideJeanSeaHead]
hash = 69c0c24e
match_first_index = 0
ib = ResourceJeanSeaHeadIB
ps-t0 = ResourceJeanSeaHeadDiffuse
ps-t1 = ResourceJeanSeaHeadLightMap
run = CommandList\global\ORFix\NNFix

[TextureOverrideJeanSeaBody]
hash = 69c0c24e
match_first_index = 7662
ib = ResourceJeanSeaBodyIB
ps-t0 = ResourceJeanSeaBodyDiffuse
ps-t1 = ResourceJeanSeaBodyLightMap
run = CommandList\global\ORFix\NNFix

[TextureOverrideJeanSeaDress]
hash = 69c0c24e
match_first_index = 52542
ib = ResourceJeanSeaDressIB
ps-t0 = ResourceJeanSeaDressDiffuse
ps-t1 = ResourceJeanSeaDressLightMap
run = CommandList\global\ORFix\NNFix

[TextureOverrideJeanSeaFaceHeadDiffuse]
hash = c2d1a57e
ps-t0 = ResourceJeanSeaFaceHeadDiffuse


; CommandList -----------------------

; Resources -------------------------

[ResourceJeanSeaPosition]
type = Buffer
stride = 40
filename = JeanSeaPosition.buf

[ResourceJeanSeaBlend]
type = Buffer
stride = 32
filename = JeanSeaBlend.buf

[ResourceJeanSeaTexcoord]
type = Buffer
stride = 20
filename = JeanSeaTexcoord.buf

[ResourceJeanSeaHeadIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = JeanSeaHead.ib

[ResourceJeanSeaBodyIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = JeanSeaBody.ib

[ResourceJeanSeaDressIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = JeanSeaDress.ib

[ResourceJeanSeaHeadDiffuse]
filename = JeanSeaHeadDiffuse.dds

[ResourceJeanSeaHeadLightMap]
filename = JeanSeaHeadLightMap.dds

[ResourceJeanSeaBodyDiffuse]
filename = JeanSeaBodyDiffuse.dds

[ResourceJeanSeaBodyLightMap]
filename = JeanSeaBodyLightMap.dds

[ResourceJeanSeaDressDiffuse]
filename = JeanSeaDressDiffuse.dds

[ResourceJeanSeaDressLightMap]
filename = JeanSeaDressLightMap.dds

[ResourceJeanSeaFaceHeadDiffuse]
filename = JeanSeaFaceHeadDiffuse.dds


; the identity mod of JeanSea: the game's own model out of its download folder (GI/JeanSea/4_0), built by AGIDMGen
