; NilouBreeze

; Constants -------------------------

; Overrides -------------------------

[TextureOverrideNilouBreezePosition]
hash = 7d53d78f
vb0 = ResourceNilouBreezePosition

[TextureOverrideNilouBreezeBlend]
hash = 49bede49
vb1 = ResourceNilouBreezeBlend
handling = skip
draw = 21830,0

[TextureOverrideNilouBreezeTexcoord]
hash = b976b848
vb1 = ResourceNilouBreezeTexcoord

[TextureOverrideNilouBreezeVertexLimitRaise]
hash = 3f79fabb

[TextureOverrideNilouBreezeIB]
hash = 00439fbb
handling = skip
drawindexed = auto

[TextureOverrideNilouBreezeHead]
hash = 00439fbb
match_first_index = 0
ib = ResourceNilouBreezeHeadIB
ps-t0 = ResourceNilouBreezeHeadDiffuse
ps-t1 = ResourceNilouBreezeHeadLightMap
run = CommandList\global\ORFix\NNFix

[TextureOverrideNilouBreezeBody]
hash = 00439fbb
match_first_index = 44538
ib = ResourceNilouBreezeBodyIB
ps-t0 = ResourceNilouBreezeBodyDiffuse
ps-t1 = ResourceNilouBreezeBodyLightMap
run = CommandList\global\ORFix\NNFix

[TextureOverrideNilouBreezeDress]
hash = 00439fbb
match_first_index = 73644
ib = ResourceNilouBreezeDressIB
ps-t0 = ResourceNilouBreezeDressDiffuse
ps-t1 = ResourceNilouBreezeDressLightMap
run = CommandList\global\ORFix\NNFix

[TextureOverrideNilouBreezeFaceHeadDiffuse]
hash = 0957b10f
ps-t0 = ResourceNilouBreezeFaceHeadDiffuse


; CommandList -----------------------

; Resources -------------------------

[ResourceNilouBreezePosition]
type = Buffer
stride = 40
filename = NilouBreezePosition.buf

[ResourceNilouBreezeBlend]
type = Buffer
stride = 32
filename = NilouBreezeBlend.buf

[ResourceNilouBreezeTexcoord]
type = Buffer
stride = 20
filename = NilouBreezeTexcoord.buf

[ResourceNilouBreezeHeadIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = NilouBreezeHead.ib

[ResourceNilouBreezeBodyIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = NilouBreezeBody.ib

[ResourceNilouBreezeDressIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = NilouBreezeDress.ib

[ResourceNilouBreezeHeadDiffuse]
filename = NilouBreezeHeadDiffuse.dds

[ResourceNilouBreezeHeadLightMap]
filename = NilouBreezeHeadLightMap.dds

[ResourceNilouBreezeBodyDiffuse]
filename = NilouBreezeBodyDiffuse.dds

[ResourceNilouBreezeBodyLightMap]
filename = NilouBreezeBodyLightMap.dds

[ResourceNilouBreezeDressDiffuse]
filename = NilouBreezeDressDiffuse.dds

[ResourceNilouBreezeDressLightMap]
filename = NilouBreezeDressLightMap.dds

[ResourceNilouBreezeFaceHeadDiffuse]
filename = NilouBreezeFaceHeadDiffuse.dds


; the identity mod of NilouBreeze: the game's own model out of its download folder (tmptnwelydq), built by AGIDMGen
