; DilucFlamme

; Constants -------------------------

; Overrides -------------------------

[TextureOverrideDilucFlammePosition]
hash = a2d909c8
vb0 = ResourceDilucFlammePosition

[TextureOverrideDilucFlammeBlend]
hash = 105887c0
vb1 = ResourceDilucFlammeBlend
handling = skip
draw = 16897,0

[TextureOverrideDilucFlammeTexcoord]
hash = 16350d1b
vb1 = ResourceDilucFlammeTexcoord

[TextureOverrideDilucFlammeVertexLimitRaise]
hash = 274e5c1a

[TextureOverrideDilucFlammeIB]
hash = a5323853
handling = skip
drawindexed = auto

[TextureOverrideDilucFlammeHead]
hash = a5323853
match_first_index = 0
ib = ResourceDilucFlammeHeadIB
ps-t0 = ResourceDilucFlammeHeadDiffuse
ps-t1 = ResourceDilucFlammeHeadLightMap
run = CommandList\global\ORFix\NNFix

[TextureOverrideDilucFlammeBody]
hash = a5323853
match_first_index = 38061
ib = ResourceDilucFlammeBodyIB
ps-t0 = ResourceDilucFlammeBodyDiffuse
ps-t1 = ResourceDilucFlammeBodyLightMap
run = CommandList\global\ORFix\NNFix

[TextureOverrideDilucFlammeDress]
hash = a5323853
match_first_index = 56010
ib = ResourceDilucFlammeDressIB
ps-t0 = ResourceDilucFlammeDressDiffuse
ps-t1 = ResourceDilucFlammeDressLightMap
run = CommandList\global\ORFix\NNFix

[TextureOverrideDilucFlammeFaceHeadDiffuse]
hash = 8b50c50f
ps-t0 = ResourceDilucFlammeFaceHeadDiffuse


; CommandList -----------------------

; Resources -------------------------

[ResourceDilucFlammePosition]
type = Buffer
stride = 40
filename = DilucFlammePosition.buf

[ResourceDilucFlammeBlend]
type = Buffer
stride = 32
filename = DilucFlammeBlend.buf

[ResourceDilucFlammeTexcoord]
type = Buffer
stride = 20
filename = DilucFlammeTexcoord.buf

[ResourceDilucFlammeHeadIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = DilucFlammeHead.ib

[ResourceDilucFlammeBodyIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = DilucFlammeBody.ib

[ResourceDilucFlammeDressIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = DilucFlammeDress.ib

[ResourceDilucFlammeHeadDiffuse]
filename = DilucFlammeHeadDiffuse.dds

[ResourceDilucFlammeHeadLightMap]
filename = DilucFlammeHeadLightMap.dds

[ResourceDilucFlammeBodyDiffuse]
filename = DilucFlammeBodyDiffuse.dds

[ResourceDilucFlammeBodyLightMap]
filename = DilucFlammeBodyLightMap.dds

[ResourceDilucFlammeDressDiffuse]
filename = DilucFlammeDressDiffuse.dds

[ResourceDilucFlammeDressLightMap]
filename = DilucFlammeDressLightMap.dds

[ResourceDilucFlammeFaceHeadDiffuse]
filename = DilucFlammeFaceHeadDiffuse.dds


; the identity mod of DilucFlamme: the game's own model out of its download folder (tmpq0rf5384), built by AGIDMGen
