; WWMI BETA-2 INI

; Mod State -------------------------

[Constants]
global $required_wwmi_version = 0.91
global $object_guid = 216714
global $mesh_vertex_count = 47621
global $shapekey_vertex_count = 40592
global $mod_id = -1000
global $state_id = 0
global $mod_enabled = 0
global $object_detected = 0

[Present]
if $object_detected
    if $mod_enabled
        post $object_detected = 0
        run = CommandListUpdateMergedSkeleton
    else
        if $mod_id == -1000
            run = CommandListRegisterMod
        endif
    endif
endif

[CommandListRegisterMod]
$\WWMIv1\required_wwmi_version = $required_wwmi_version
$\WWMIv1\object_guid = $object_guid
Resource\WWMIv1\ModName = ref ResourceModName
Resource\WWMIv1\ModAuthor = ref ResourceModAuthor
Resource\WWMIv1\ModDesc = ref ResourceModDesc
Resource\WWMIv1\ModLink = ref ResourceModLink
Resource\WWMIv1\ModLogo = ref ResourceModLogo
run = CommandList\WWMIv1\RegisterMod
$mod_id = $\WWMIv1\mod_id
if $mod_id >= 0
    $mod_enabled = 1
endif

[CommandListUpdateMergedSkeleton]
if $state_id
    $state_id = 0
else
    $state_id = 1
endif
ResourceMergedSkeleton = copy ResourceMergedSkeletonRW
ResourceExtraMergedSkeleton = copy ResourceExtraMergedSkeletonRW

; Resources: Mod Info -------------------------

[ResourceModName]
type = Buffer
data = "Cantarella Identity"

[ResourceModAuthor]
type = Buffer
data = "Anime Game Remap"

[ResourceModDesc]
type = Buffer
data = "The identity mod of Cantarella: the game's own model out of WWMI-Assets, built by AGIDMGen"

[ResourceModLink]
; type = Buffer
; data = "Empty Mod Link"

[ResourceModLogo]
; filename = Textures/Logo.dds

; Shading: Draw Call Stacks Processing -------------------------

[TextureOverrideMarkBoneDataCB]
hash = f02baf77
match_priority = 0
filter_index = 3381.7777

[CommandListMergeSkeleton]
$\WWMIv1\custom_mesh_scale = 1.00
cs-cb8 = ref vs-cb4
cs-u6 = ResourceMergedSkeletonRW
run = CustomShader\WWMIv1\SkeletonMerger
cs-cb8 = ref vs-cb3
cs-u6 = ResourceExtraMergedSkeletonRW
run = CustomShader\WWMIv1\SkeletonMerger

[CommandListTriggerResourceOverrides]
CheckTextureOverride = ps-t0
CheckTextureOverride = ps-t1
CheckTextureOverride = ps-t2
CheckTextureOverride = ps-t3
CheckTextureOverride = ps-t4
CheckTextureOverride = ps-t5
CheckTextureOverride = ps-t6
CheckTextureOverride = ps-t7
CheckTextureOverride = vs-cb3
CheckTextureOverride = vs-cb4

[CommandListOverrideSharedResources]
ResourceBypassVB0 = ref vb0
ib = ResourceIndexBuffer
vb0 = ResourcePositionBuffer
vb1 = ResourceVectorBuffer
vb2 = ResourceTexcoordBuffer
vb3 = ResourceColorBuffer
vb4 = ResourceBlendBuffer
if vs-cb3 == 3381.7777
    vs-cb3 = ResourceExtraMergedSkeleton
endif
if vs-cb4 == 3381.7777
    vs-cb4 = ResourceMergedSkeleton
endif

[CommandListCleanupSharedResources]
vb0 = ref ResourceBypassVB0

[TextureOverrideComponent0]
hash = 5432f939
match_first_index = 0
match_index_count = 17322
$object_detected = 1
if $mod_enabled
    local $state_id_0
    if $state_id_0 != $state_id
        $state_id_0 = $state_id
        $\WWMIv1\vg_offset = 0
        $\WWMIv1\vg_count = 22
        run = CommandListMergeSkeleton
    endif
    if ResourceMergedSkeleton !== null
        handling = skip
        run = CommandListTriggerResourceOverrides
        run = CommandListOverrideSharedResources
        ; Draw Component 0
        drawindexed = 17322, 0, 0
        run = CommandListCleanupSharedResources
    endif
endif

[TextureOverrideComponent1]
hash = 5432f939
match_first_index = 17322
match_index_count = 30504
$object_detected = 1
if $mod_enabled
    local $state_id_1
    if $state_id_1 != $state_id
        $state_id_1 = $state_id
        $\WWMIv1\vg_offset = 22
        $\WWMIv1\vg_count = 26
        run = CommandListMergeSkeleton
    endif
    if ResourceMergedSkeleton !== null
        handling = skip
        run = CommandListTriggerResourceOverrides
        run = CommandListOverrideSharedResources
        ; Draw Component 1
        drawindexed = 30504, 17322, 0
        run = CommandListCleanupSharedResources
    endif
endif

[TextureOverrideComponent2]
hash = 5432f939
match_first_index = 47826
match_index_count = 13488
$object_detected = 1
if $mod_enabled
    local $state_id_2
    if $state_id_2 != $state_id
        $state_id_2 = $state_id
        $\WWMIv1\vg_offset = 48
        $\WWMIv1\vg_count = 5
        run = CommandListMergeSkeleton
    endif
    if ResourceMergedSkeleton !== null
        handling = skip
        run = CommandListTriggerResourceOverrides
        run = CommandListOverrideSharedResources
        ; Draw Component 2
        drawindexed = 13488, 47826, 0
        run = CommandListCleanupSharedResources
    endif
endif

[TextureOverrideComponent3]
hash = 5432f939
match_first_index = 61314
match_index_count = 82620
$object_detected = 1
if $mod_enabled
    local $state_id_3
    if $state_id_3 != $state_id
        $state_id_3 = $state_id
        $\WWMIv1\vg_offset = 53
        $\WWMIv1\vg_count = 113
        run = CommandListMergeSkeleton
    endif
    if ResourceMergedSkeleton !== null
        handling = skip
        run = CommandListTriggerResourceOverrides
        run = CommandListOverrideSharedResources
        ; Draw Component 3
        drawindexed = 82620, 61314, 0
        run = CommandListCleanupSharedResources
    endif
endif

[TextureOverrideComponent4]
hash = 5432f939
match_first_index = 143934
match_index_count = 33396
$object_detected = 1
if $mod_enabled
    local $state_id_4
    if $state_id_4 != $state_id
        $state_id_4 = $state_id
        $\WWMIv1\vg_offset = 166
        $\WWMIv1\vg_count = 37
        run = CommandListMergeSkeleton
    endif
    if ResourceMergedSkeleton !== null
        handling = skip
        run = CommandListTriggerResourceOverrides
        run = CommandListOverrideSharedResources
        ; Draw Component 4
        drawindexed = 33396, 143934, 0
        run = CommandListCleanupSharedResources
    endif
endif

[TextureOverrideComponent5]
hash = 5432f939
match_first_index = 177330
match_index_count = 35934
$object_detected = 1
if $mod_enabled
    local $state_id_5
    if $state_id_5 != $state_id
        $state_id_5 = $state_id
        $\WWMIv1\vg_offset = 203
        $\WWMIv1\vg_count = 54
        run = CommandListMergeSkeleton
    endif
    if ResourceMergedSkeleton !== null
        handling = skip
        run = CommandListTriggerResourceOverrides
        run = CommandListOverrideSharedResources
        ; Draw Component 5
        drawindexed = 35934, 177330, 0
        run = CommandListCleanupSharedResources
    endif
endif

[TextureOverrideComponent6]
hash = 5432f939
match_first_index = 213264
match_index_count = 1980
$object_detected = 1
if $mod_enabled
    local $state_id_6
    if $state_id_6 != $state_id
        $state_id_6 = $state_id
        $\WWMIv1\vg_offset = 257
        $\WWMIv1\vg_count = 1
        run = CommandListMergeSkeleton
    endif
    if ResourceMergedSkeleton !== null
        handling = skip
        run = CommandListTriggerResourceOverrides
        run = CommandListOverrideSharedResources
        ; Draw Component 6
        drawindexed = 1980, 213264, 0
        run = CommandListCleanupSharedResources
    endif
endif

[TextureOverrideComponent7]
hash = 5432f939
match_first_index = 215244
match_index_count = 1470
$object_detected = 1
if $mod_enabled
    local $state_id_7
    if $state_id_7 != $state_id
        $state_id_7 = $state_id
        $\WWMIv1\vg_offset = 258
        $\WWMIv1\vg_count = 6
        run = CommandListMergeSkeleton
    endif
    if ResourceMergedSkeleton !== null
        handling = skip
        run = CommandListTriggerResourceOverrides
        run = CommandListOverrideSharedResources
        ; Draw Component 7
        drawindexed = 1470, 215244, 0
        run = CommandListCleanupSharedResources
    endif
endif

; Shading: Textures -------------------------

[ResourceTexture0]
filename = Textures/CantarellaTexture0480d129.dds

[TextureOverrideTexture0]
hash = 0480d129
match_priority = 0
if $object_detected
    this = ResourceTexture0
endif

[ResourceTexture1]
filename = Textures/CantarellaTexture0c868365.dds

[TextureOverrideTexture1]
hash = 0c868365
match_priority = 0
if $object_detected
    this = ResourceTexture1
endif

[ResourceTexture2]
filename = Textures/CantarellaTexture21f813ba.dds

[TextureOverrideTexture2]
hash = 21f813ba
match_priority = 0
if $object_detected
    this = ResourceTexture2
endif

[ResourceTexture3]
filename = Textures/CantarellaTexture22ba1d3e.dds

[TextureOverrideTexture3]
hash = 22ba1d3e
match_priority = 0
if $object_detected
    this = ResourceTexture3
endif

[ResourceTexture4]
filename = Textures/CantarellaTexture3cda6614.dds

[TextureOverrideTexture4]
hash = 3cda6614
match_priority = 0
if $object_detected
    this = ResourceTexture4
endif

[ResourceTexture5]
filename = Textures/CantarellaTexture3ebe428b.dds

[TextureOverrideTexture5]
hash = 3ebe428b
match_priority = 0
if $object_detected
    this = ResourceTexture5
endif

[ResourceTexture6]
filename = Textures/CantarellaTexture52a54db3.dds

[TextureOverrideTexture6]
hash = 52a54db3
match_priority = 0
if $object_detected
    this = ResourceTexture6
endif

[ResourceTexture7]
filename = Textures/CantarellaTexture5bbb1f80.dds

[TextureOverrideTexture7]
hash = 5bbb1f80
match_priority = 0
if $object_detected
    this = ResourceTexture7
endif

[ResourceTexture8]
filename = Textures/CantarellaTexture5fb46aac.dds

[TextureOverrideTexture8]
hash = 5fb46aac
match_priority = 0
if $object_detected
    this = ResourceTexture8
endif

[ResourceTexture9]
filename = Textures/CantarellaTexture76a3b6f4.dds

[TextureOverrideTexture9]
hash = 76a3b6f4
match_priority = 0
if $object_detected
    this = ResourceTexture9
endif

[ResourceTexture10]
filename = Textures/CantarellaTexture787c92b8.dds

[TextureOverrideTexture10]
hash = 787c92b8
match_priority = 0
if $object_detected
    this = ResourceTexture10
endif

[ResourceTexture11]
filename = Textures/CantarellaTexture8383cbbf.dds

[TextureOverrideTexture11]
hash = 8383cbbf
match_priority = 0
if $object_detected
    this = ResourceTexture11
endif

[ResourceTexture12]
filename = Textures/CantarellaTexture87b19749.dds

[TextureOverrideTexture12]
hash = 87b19749
match_priority = 0
if $object_detected
    this = ResourceTexture12
endif

[ResourceTexture13]
filename = Textures/CantarellaTexture89e2bbf1.dds

[TextureOverrideTexture13]
hash = 89e2bbf1
match_priority = 0
if $object_detected
    this = ResourceTexture13
endif

[ResourceTexture14]
filename = Textures/CantarellaTexture8ecda31a.dds

[TextureOverrideTexture14]
hash = 8ecda31a
match_priority = 0
if $object_detected
    this = ResourceTexture14
endif

[ResourceTexture15]
filename = Textures/CantarellaTexture91bf0adb.dds

[TextureOverrideTexture15]
hash = 91bf0adb
match_priority = 0
if $object_detected
    this = ResourceTexture15
endif

[ResourceTexture16]
filename = Textures/CantarellaTexture9986ce50.dds

[TextureOverrideTexture16]
hash = 9986ce50
match_priority = 0
if $object_detected
    this = ResourceTexture16
endif

[ResourceTexture17]
filename = Textures/CantarellaTexture9a126c64.dds

[TextureOverrideTexture17]
hash = 9a126c64
match_priority = 0
if $object_detected
    this = ResourceTexture17
endif

[ResourceTexture18]
filename = Textures/CantarellaTextureb00d33d6.dds

[TextureOverrideTexture18]
hash = b00d33d6
match_priority = 0
if $object_detected
    this = ResourceTexture18
endif

[ResourceTexture19]
filename = Textures/CantarellaTextureb6deb6c2.dds

[TextureOverrideTexture19]
hash = b6deb6c2
match_priority = 0
if $object_detected
    this = ResourceTexture19
endif

[ResourceTexture20]
filename = Textures/CantarellaTextureb8fe5f0a.dds

[TextureOverrideTexture20]
hash = b8fe5f0a
match_priority = 0
if $object_detected
    this = ResourceTexture20
endif

[ResourceTexture21]
filename = Textures/CantarellaTexturef7dadc16.dds

[TextureOverrideTexture21]
hash = f7dadc16
match_priority = 0
if $object_detected
    this = ResourceTexture21
endif

; Skinning: Shape Keys Override -------------------------

[TextureOverrideShapeKeyOffsets]
hash = 4db8a26d
match_priority = 0
override_byte_stride = 24
override_vertex_count = $mesh_vertex_count

[TextureOverrideShapeKeyScale]
hash = 8194a58c
match_priority = 0
override_byte_stride = 4
override_vertex_count = $mesh_vertex_count

[CommandListSetupShapeKeys]
$\WWMIv1\shapekey_checksum = 2496
cs-t33 = ResourceShapeKeyOffsetBuffer
cs-u5 = ResourceCustomShapeKeyValuesRW
cs-u6 = ResourceShapeKeyCBRW
run = CustomShader\WWMIv1\ShapeKeyOverrider

[CommandListLoadShapeKeys]
$\WWMIv1\shapekey_vertex_count = $shapekey_vertex_count
cs-t0 = ResourceShapeKeyVertexIdBuffer
cs-t1 = ResourceShapeKeyVertexOffsetBuffer
cs-u6 = ResourceShapeKeyCBRW
run = CustomShader\WWMIv1\ShapeKeyLoader

[TextureOverrideShapeKeyLoaderCallback]
hash = 4db8a26d
match_priority = 0
if $mod_enabled
    if cs == 3381.3333 && ResourceMergedSkeleton !== null
        handling = skip
        run = CommandListSetupShapeKeys
        run = CommandListLoadShapeKeys
    endif
endif

[CommandListMultiplyShapeKeys]
$\WWMIv1\custom_vertex_count = $mesh_vertex_count
run = CustomShader\WWMIv1\ShapeKeyMultiplier

[TextureOverrideShapeKeyMultiplierCallback]
hash = 4db8a26d
match_priority = 0
if $mod_enabled
    if cs == 3381.4444 && ResourceMergedSkeleton !== null
        handling = skip
        run = CommandListMultiplyShapeKeys
    endif
endif

; Resources: Shape Keys Override -------------------------

[ResourceShapeKeyCBRW]
type = RWBuffer
format = R32G32B32A32_UINT
array = 66

[ResourceCustomShapeKeyValuesRW]
type = RWBuffer
format = R32G32B32A32_FLOAT
array = 32

; Resources: Skeleton Override -------------------------

[ResourceMergedSkeleton]

[ResourceMergedSkeletonRW]
type = RWBuffer
format = R32G32B32A32_FLOAT
array = 768

[ResourceExtraMergedSkeleton]

[ResourceExtraMergedSkeletonRW]
type = RWBuffer
format = R32G32B32A32_FLOAT
array = 768

; Resources: Buffers -------------------------

[ResourceBypassVB0]

[ResourceIndexBuffer]
type = Buffer
format = DXGI_FORMAT_R32_UINT
stride = 12
filename = Meshes/Index.buf

[ResourcePositionBuffer]
type = Buffer
format = DXGI_FORMAT_R32G32B32_FLOAT
stride = 12
filename = Meshes/Position.buf

[ResourceBlendBuffer]
type = Buffer
format = DXGI_FORMAT_R8_UINT
stride = 8
filename = Meshes/Blend.buf

[ResourceVectorBuffer]
type = Buffer
format = DXGI_FORMAT_R8G8B8A8_SNORM
stride = 8
filename = Meshes/Vector.buf

[ResourceColorBuffer]
type = Buffer
format = DXGI_FORMAT_R8G8B8A8_UNORM
stride = 4
filename = Meshes/Color.buf

[ResourceTexCoordBuffer]
type = Buffer
format = DXGI_FORMAT_R16G16_FLOAT
stride = 16
filename = Meshes/TexCoord.buf

[ResourceShapeKeyOffsetBuffer]
type = Buffer
format = DXGI_FORMAT_R32G32B32A32_UINT
stride = 16
filename = Meshes/ShapeKeyOffset.buf

[ResourceShapeKeyVertexIdBuffer]
type = Buffer
format = DXGI_FORMAT_R32_UINT
stride = 4
filename = Meshes/ShapeKeyVertexId.buf

[ResourceShapeKeyVertexOffsetBuffer]
type = Buffer
format = DXGI_FORMAT_R16_FLOAT
stride = 2
filename = Meshes/ShapeKeyVertexOffset.buf

; Autogenerated -------------------------

; This mod.ini is the IDENTITY mod of Cantarella, generated by AGIDMGen (Anime Game Identity Mod Generator) from WWMI-Assets, in the shape WWMI Tools 1.3.4 generates (WWMI v0.9.1+)
