; KeqingOpulent

; Constants -------------------------

; Overrides -------------------------

[TextureOverrideKeqingOpulentPosition]
hash = 0d7e3cc5
vb0 = ResourceKeqingOpulentPosition

[TextureOverrideKeqingOpulentBlend]
hash = 6f010b58
vb1 = ResourceKeqingOpulentBlend
handling = skip
draw = 16066,0

[TextureOverrideKeqingOpulentTexcoord]
hash = 52f78cb7
vb1 = ResourceKeqingOpulentTexcoord

[TextureOverrideKeqingOpulentVertexLimitRaise]
hash = 6629a84e

[TextureOverrideKeqingOpulentIB]
hash = 7c6fc8c3
handling = skip
drawindexed = auto

[TextureOverrideKeqingOpulentHead]
hash = 7c6fc8c3
match_first_index = 0
ib = ResourceKeqingOpulentHeadIB
ps-t0 = ResourceKeqingOpulentHeadDiffuse
ps-t1 = ResourceKeqingOpulentHeadLightMap
run = CommandList\global\ORFix\NNFix

[TextureOverrideKeqingOpulentBody]
hash = 7c6fc8c3
match_first_index = 19623
ib = ResourceKeqingOpulentBodyIB
ps-t0 = ResourceKeqingOpulentBodyDiffuse
ps-t1 = ResourceKeqingOpulentBodyLightMap
run = CommandList\global\ORFix\NNFix

[TextureOverrideKeqingOpulentFaceHeadDiffuse]
hash = c2b17f84
ps-t0 = ResourceKeqingOpulentFaceHeadDiffuse


; CommandList -----------------------

; Resources -------------------------

[ResourceKeqingOpulentPosition]
type = Buffer
stride = 40
filename = KeqingOpulentPosition.buf

[ResourceKeqingOpulentBlend]
type = Buffer
stride = 32
filename = KeqingOpulentBlend.buf

[ResourceKeqingOpulentTexcoord]
type = Buffer
stride = 20
filename = KeqingOpulentTexcoord.buf

[ResourceKeqingOpulentHeadIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = KeqingOpulentHead.ib

[ResourceKeqingOpulentBodyIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = KeqingOpulentBody.ib

[ResourceKeqingOpulentHeadDiffuse]
filename = KeqingOpulentHeadDiffuse.dds

[ResourceKeqingOpulentHeadLightMap]
filename = KeqingOpulentHeadLightMap.dds

[ResourceKeqingOpulentBodyDiffuse]
filename = KeqingOpulentBodyDiffuse.dds

[ResourceKeqingOpulentBodyLightMap]
filename = KeqingOpulentBodyLightMap.dds

[ResourceKeqingOpulentFaceHeadDiffuse]
filename = KeqingOpulentFaceHeadDiffuse.dds


; the identity mod of KeqingOpulent: the game's own model out of its download folder (GI/KeqingOpulent/4_0), built by AGIDMGen
