; Xingqiu

; Constants -------------------------

; Overrides -------------------------

[TextureOverrideXingqiuPosition]
hash = cc158a1e
vb0 = ResourceXingqiuPosition

[TextureOverrideXingqiuBlend]
hash = 07c7c5b6
vb1 = ResourceXingqiuBlend
handling = skip
draw = 20494,0

[TextureOverrideXingqiuTexcoord]
hash = 41426386
vb1 = ResourceXingqiuTexcoord

[TextureOverrideXingqiuVertexLimitRaise]
hash = 3944dfbd

[TextureOverrideXingqiuIB]
hash = 76df4025
handling = skip
drawindexed = auto

[TextureOverrideXingqiuHead]
hash = 76df4025
match_first_index = 0
ib = ResourceXingqiuHeadIB
ps-t0 = ResourceXingqiuHeadDiffuse
ps-t1 = ResourceXingqiuHeadLightMap
run = CommandList\global\ORFix\NNFix

[TextureOverrideXingqiuBody]
hash = 76df4025
match_first_index = 32508
ib = ResourceXingqiuBodyIB
ps-t0 = ResourceXingqiuBodyDiffuse
ps-t1 = ResourceXingqiuBodyLightMap
run = CommandList\global\ORFix\NNFix

[TextureOverrideXingqiuDress]
hash = 76df4025
match_first_index = 62103
ib = ResourceXingqiuDressIB
ps-t0 = ResourceXingqiuDressDiffuse
ps-t1 = ResourceXingqiuDressLightMap
run = CommandList\global\ORFix\NNFix

[TextureOverrideXingqiuFaceHeadDiffuse]
hash = b8017b84
ps-t0 = ResourceXingqiuFaceHeadDiffuse


; CommandList -----------------------

; Resources -------------------------

[ResourceXingqiuPosition]
type = Buffer
stride = 40
filename = XingqiuPosition.buf

[ResourceXingqiuBlend]
type = Buffer
stride = 32
filename = XingqiuBlend.buf

[ResourceXingqiuTexcoord]
type = Buffer
stride = 20
filename = XingqiuTexcoord.buf

[ResourceXingqiuHeadIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = XingqiuHead.ib

[ResourceXingqiuBodyIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = XingqiuBody.ib

[ResourceXingqiuDressIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = XingqiuDress.ib

[ResourceXingqiuHeadDiffuse]
filename = XingqiuHeadDiffuse.dds

[ResourceXingqiuHeadLightMap]
filename = XingqiuHeadLightMap.dds

[ResourceXingqiuBodyDiffuse]
filename = XingqiuBodyDiffuse.dds

[ResourceXingqiuBodyLightMap]
filename = XingqiuBodyLightMap.dds

[ResourceXingqiuDressDiffuse]
filename = XingqiuDressDiffuse.dds

[ResourceXingqiuDressLightMap]
filename = XingqiuDressLightMap.dds

[ResourceXingqiuFaceHeadDiffuse]
filename = XingqiuFaceHeadDiffuse.dds


; the identity mod of Xingqiu: the game's own model out of its download folder (tmpsz6xdumr), built by AGIDMGen
