#
# ===== buildDownloadManifest =====
#
# Writes AGIDMGen/api/src/py/AGIDMGen/data/ModDownloadData.py: every download folder an identity mod can be
# generated from, and the repo each of its files is kept in, read off AG Remap's Data/Mod Downloads and
# this repo's:
#
#   py -3 Tools/Downloads/buildDownloadManifest.py <AGRemap/Data/Mod Downloads>
#
# A version folder is listed when, with both repos' files together, it has the file that names its
# prefix: <prefix>Hash.json for GI, <prefix>Metadata.json for WuWa. A file both repos have is taken from
# AG Remap's. Run it after populateDownloads.py, and after AG Remap's master gains a download folder.
#
# AG Remap's files are listed from the local checkout given, so that checkout must match what AG Remap's
# GitHub master serves -- a folder only on a local branch would make the library ask for files that 404.
#

import argparse
import os
import pprint
import sys

from downloadTools import Games, OwnDownloads, RepoRoot, readAliases, getVersionFolders, findPrefix
import AGIDMGen as IDMG

Output = os.path.join(RepoRoot, "AGIDMGen", "api", "src", "py", "AGIDMGen", "data", "ModDownloadData.py")

Header = '''##### Credits

# ===== Anime Game Identity Mod Generator (AGIDMGen) =====
# Authors: Albert Gold#2696
#
# A sub-project of Anime Game Remap (AG Remap)
# if you used it to make your mods pls give credit for "Albert Gold#2696"

##### EndCredits

# GENERATED by Tools/Downloads/buildDownloadManifest.py -- do not edit by hand, rerun the tool.


##### ExtImports
from typing import Dict, Tuple
##### EndExtImports


##### Script
'''


def main() -> int:
    parser = argparse.ArgumentParser(description = "write the library's list of download folders")
    parser.add_argument("agRemap", help = "AG Remap's 'Data/Mod Downloads' folder (a checkout matching its GitHub master)")
    args = parser.parse_args()

    roots = [(IDMG.ModDownloadRepos.AGRemap, args.agRemap), (IDMG.ModDownloadRepos.AGIDMGen, OwnDownloads)]
    data = {}
    skipped = []
    for loader in Games.values():
        game = IDMG.ModDownloadGameFolders[loader]
        names = set()
        for _, root in roots:
            if (os.path.isdir(os.path.join(root, game))):
                names.update(n for n in os.listdir(os.path.join(root, game)) if os.path.isdir(os.path.join(root, game, n)))

        for name in sorted(names, key = str.lower):
            versions = set()
            for _, root in roots:
                versions.update(getVersionFolders(os.path.join(root, game, name)))

            for version in versions:
                files = {}
                for repo, root in roots:
                    folder = os.path.join(root, game, name, version)
                    if (os.path.isdir(folder)):
                        for fileName in sorted(os.listdir(folder)):
                            if (os.path.isfile(os.path.join(folder, fileName))):
                                files.setdefault(fileName, repo.name)

                prefix = findPrefix(loader, list(files), hashOnly = True)
                if (prefix is None):
                    skipped.append(f"{game}/{name}/{version}")
                    continue
                data.setdefault(game, {}).setdefault(name, {})[version] = (prefix, files)

    with open(Output, "w", encoding = "utf-8", newline = "\n") as f:
        f.write(Header)
        f.write("#: For each game folder, character and version folder: the prefix of the folder's files, and the repository (a :class:`ModDownloadRepos` name) each file is kept in\n")
        f.write("ModDownloadData: Dict[str, Dict[str, Dict[str, Tuple[str, Dict[str, str]]]]] = ")
        f.write(pprint.pformat(data, width = 160, sort_dicts = True))
        f.write("\n\n#: For each game folder, other names its characters are known by (eg. the asset repo's), and the name of their folder\n")
        f.write("ModDownloadAliases: Dict[str, Dict[str, str]] = ")
        f.write(pprint.pformat(readAliases(), width = 160, sort_dicts = True))
        f.write("\n##### EndScript\n")

    counts = {game: (len(characters), sum(len(v) for v in characters.values())) for game, characters in data.items()}
    print(f"wrote {os.path.relpath(Output, RepoRoot)}: " + ", ".join(f"{game} {c} characters / {v} versions" for game, (c, v) in counts.items()))
    print(f"skipped (no file names the prefix): {len(skipped)}" + (f" -- {', '.join(skipped)}" if skipped else ""))
    return 0


if (__name__ == "__main__"):
    sys.exit(main())
